### ISSUE TITLE
RFC: an inline_ function that dumps c/c++ code to the code emitter

### ISSUE THREAD

**Issue by nevion** [cython/cython#1440]
I was looking yet again at the parser for cython and I figured something like the print or exec statement handlings could also be used to add an inline_ statement - the purpose which would dump strings directly into the emitted code.  The idea is to use it globally and within functions.

Is the naming good?

Any ideas what this would break / be weary of?

Such a statement could be used to do macros, pull in includes, and modify/declare c-variables.

**Comment by robertwb** [comment]
Such a change, which would require significant discussion, should be proposed on cython-devel@ rather than as a github issue. 

However, one of the guiding principles is keeping Cython code as close to Python as possible, and embedding snippets of raw C code wouldn't work well with this. It would also place (often implicit) constraints on the structure (and naming conventions) of the generated code, as well as making it difficult to fully analyze the C code itself, so I don't think such a change would be accepted. In rare corner cases where one can't express what is wanted in Python syntax, writing a small C stub that is invoked form Cython is often the way to go.

**Comment by nevion** [comment]
@robertwb The problem is I use C++ in cython and it sucks at this.  Honestly I have no expectation it can get good because C++ is so hard to work with natively in compilers, I don't see how it can fully cross that bridge if we speak in all the issues templates bring.... I just ran into another issue to that I know wouldn't be a problem if I didn't have this cython language only constraint.

Not only that but while not mutually exclusive, there needs to be a single source capability for doing this if we ever hope to have amanagable way to do runtime compiled files (quasi JIT/AOC).

**Comment by nevion** [comment]
@robertwb can you approve my membership / moderated topics if any for the ML?  I think I'm in a half joined state still, waiting for moderation approval.
