### ISSUE TITLE
Coroutines can segfault on __name__ access

### ISSUE THREAD

**Issue by 1st1** [cython/cython#1493]
Specifically, see line [1]: somehow, under some conditions, programs using uvloop were segfaulting, because `self->gi_name` is set to `NULL` when coroutine is finalized (same issue with `__qualname__`).  I already raised this issue on cython mailing list, and was suggested to fix this myself. Unfortunately I don't have time atm, but this is something that has to be fixed in Cython 0.25.

Right now I'm forced to patch generated C files with an ugly hack in uvloop Makefile: [2]

[1] https://github.com/cython/cython/blob/master/Cython/Utility/Coroutine.c#L951
[2] https://github.com/MagicStack/uvloop/blob/master/Makefile#L95

**Comment by Eijebong** [comment]
Yeah, I had the same problem but I had problems with the mailing list and I just forgot about it.
Here is the mail:

> Hello,

> I've been playing with asyncio and cython and found that the attached
code segfaults.


>I looked at the generated C code and it tries to do
Py_INCREF(self->gi_qualname); when retrieving __qualname__
but self->gi_qualname is NULL here because __Pyx_Coroutine_clear has
already been called.
If I comment this line then it "works" and i just run into this bug:

>"[cython-users] cython coroutine object  does not have 'cr_code' and
'cr_frame' attributes."

And here is a simple example:

```python
import asyncio

def func():
    task = asyncio.Task(func2())
    def bug(task):
        print(task)

    task.add_done_callback(bug)


async def func2():
    await asyncio.sleep(1)

loop = asyncio.get_event_loop()
func()
loop.run_forever()
```

**Comment by 1st1** [comment]
Thanks a lot!
