### ISSUE TITLE
Don't generate trivial __new__

### ISSUE THREAD

**Issue by serhiy-storchaka** [cython/cython#1555]
Cython generates the `__new__` method even for classes without data. Recent [change](http://bugs.python.org/issue5322) in CPython broke multiple inheritance from Cython classes. That change was reverted for backward compatibility, but if Cython would not generate trivial `__new__` for empty classes, it would help to push that change back.

**Comment by scoder** [comment]
@serhiy-storchaka, I'm not sure what to make of this. Cython does not generate a `__new__` Python method directly. It only generates a `tp_new` slot function. CPython then generates the `__new__` method wrapper for it.

If Cython left `tp_new` empty, then the type couldn't be instantiated. So a `tp_new`, even an empty one that calls the base type's `tp_new`, is always needed.

We could try to inherit the `tp_new` function of the base type instead of creating an empty one that calls it, but I don't know if that changes anything. Is that what you were referring to?

**Comment by scoder** [comment]
Also, for a type without base types, we could then use `PyType_GenericNew` for `tp_new`, but that doesn't seem to be special-cased anywhere. So there doesn't seem to be a benefit to that, so is this only about a `tp_new` that calls the base class `tp_new`, i.e. types with parents ?

**Comment by scoder** [comment]
#2900 and #2909 should resolve this.
