### ISSUE TITLE
Support for C++ scoped enum class

### ISSUE THREAD

**Issue by TheJJ** [cython/cython#1603]
There is currently no sane way to represent `enum class` in `.pxd`.

``` cpp
namespace lol {
enum class rofl : int {
    SOMETHING,
    MOAR = 1337
};

// at this point, accessible as rofl::MOAR
}
// here, accessible as lol::rofl::MOAR
```

A possible way of representing it would be:

``` cython
cdef extern from "headername.h" namespace "lol":
    cdef enumclass rofl:
        SOMETHING
        MOAR

# accessed as
rofl.MOAR
```

Related:  #1567

**Comment by mic-e** [comment]
The best workaround for this issue that I found with current Cython:

    cdef extern from "headername.h" namespace "lol":
        cdef cppclass rofl:
            pass
        
        cdef rofl rofl_SOMETHING "rofl::SOMETHING"
        cdef rofl rofl_MOAR "rofl::MOAR"

This can be used in the `pyx` file like this:

    cdef void f(rofl arg):
        pass

    f(rofl_SOMETHING)

Which will generate the correct C++ code.

**Comment by kaeptmblaubaer1000** [comment]
I think this workaround is also good:

    cdef extern from "headername.h" namespace "lol":
        cdef enum rofl:
            SOMETHING "lol::rofl::SOMETHING",
            MOAR "lol::rofl::MOAR"

And then:

    cdef void f(rofl arg)
        pass
    
    f(rofl.SOMETHING)

**Comment by Thf772** [comment]
I recently used @kaeptmblaubaer1000 's solution with Cython 0.28.4, and it resulted in MSVC's compiler error C3431: `a scoped enumeration cannot be redeclared as an unscoped enumeration` when I tried using it in a `cdef` declaration.

```
cdef extern from "headername.h" namespace "lol":
    cdef enum rofl:
        SOMETHING "lol::rofl::SOMETHING",
        MOAR "lol::rofl::MOAR"

cdef void lololol():
    cdef rofl moarlol
```

The reason is that the enum is declared as `enum class rofl` and Cython generates

```C++
enum rofl __pyx_v_moarlol;
```

effectively declaring `rofl` as a regular enum, instead of 

```C++
rofl __pyx_v_moarlol;
```

The solution for me was to replace `cdef enum rofl` with `ctypedef enum rofl` which removes the `enum` keyword, as shown here: http://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#styles-of-struct-union-and-enum-declaration

**Comment by jrhemstad** [comment]
Would love to get support for this as we'd like to be able to use `enum class` parameters in our top-level APIs in [libcudf](https://github.com/rapidsai/cudf), the C++ backend for the cuDF Python library that provides GPU accelerated Pandas functionality.

**Comment by kkraus14** [comment]
Full example gist of using the workaround described by @Thf772 above: https://gist.github.com/kkraus14/1ad8c5decabfd994633ef7f71dad3bc8

Thanks!

**Comment by McSinyx** [comment]
Is there anyway to avoid exposing the enum class values to the parent namespace?  In other words only allow accessing the value via `enum_class.enum_value`, not just `enum_value`.

**Comment by justinfx** [comment]
I had this same problem and came to the same workaround solution back in 2013:
https://stackoverflow.com/a/15566540/496445

Someone brought this up to me today and I had a poke around to see if anything has improved around this since that time, but then I came across this ticket with the same workarounds.
