### ISSUE TITLE
Optional arguments "k=*" broken in master

### ISSUE THREAD

**Issue by tito** [cython/cython#1706]
Hi, i tried master today, and got this issue:

```
    cdef inline void remove_callback(self, BoundCallback callback, int force=*) except *
                                                                             ^
------------------------------------------------------------

build/kivy/x86_64/kivy/kivy/_event.pxd:55:78: Expected an identifier or literal
```

This works in 0.25.2 :)

**Comment by tito** [comment]
A git bisect (python setup.py develop + cython path_to_the_file) indicate the commit 9cb2af378b2f6b4ff1abde3e6469111a8f750409 for introducing the regression.

**Comment by jdemeyer** [comment]
It's pointless to **declare** a function (without implementing it) as `inline` in a `.pxd` file (in fact, Cython should probably warn or error for this). The reason is that you cannot "inline" a function call from one Cython module in another Cython module: a call across modules will never be inline.

Since I don't know your bigger picture (you just quoted one line of code), there are 3 cases, each with a solution:

(1) Your function is only called in the module where it is implemented => you don't need to declare it in the `.pxd` file at all.

(2) Your function is called from a different module and you don't care whether that call is inlined => remove the `inline` keyword in the `.pxd` file (you can still keep it in the `.pyx` file).

(3) You really want the function to be inline in all cases => implement the function in the `.pxd` file instead of the `.pyx` file.

**Comment by robertwb** [comment]
Allowing this for now, this will be an error in the future.
