### ISSUE TITLE
Make the cythonize command line more useful

### ISSUE THREAD

**Issue by netheril96** [cython/cython#1711]
A couple of more common build options, such as `--numpy`, `--include_path`, `--libraries`, `--cflags`, `--ldflags` should be added to `cythonize` command line so that it can be used easily for the majority of building tasks. 

Setting up a `setup.py` script for every `pyx` file I need to write is really, really tedious, which put me off from cython for years before I finally tried it for the first time (and that was in IPython notebook with cython magic, so I still don't know how to write `setup.py`). I am sure that many beginners to cython are just scared of the complicated build process like me, and never have the chance to actually try it. Please make it more accessible.

The `%%cython` magic in IPython has much better sane defaults and useful command line options than the `cythonize` script.

**Comment by netheril96** [comment]
I extracted the cython magic into a separate script at https://github.com/netheril96/utilities/blob/master/mycython.py. Since most Cython usage are for speedups of small section of Python code, or for wrapping up existing C/C++ libraries, the lightweight approach of a simple command line should be preferred to the heavy `setup.py` approach for the majority of time.

**Comment by ozars** [comment]
Just noting here something I noticed, cythonize CLI interface actually honors environment variables such as CC, CXX, LDSHARED, CFLAGS, CPPFLAGS, LDFLAGS... I assume this isn't documented under cythonize since this feature is provided by distutils.

Example:
```
~/tmp$ CFLAGS="-O3 -g0" CPPFLAGS="-DMYDEF1 -DMYDEF2" LDFLAGS="-lz" cythonize -3 -i test.pyx 
running build_ext
building 'test' extension
creating /home/omer/tmp/tmpvkvr9kqr/home
creating /home/omer/tmp/tmpvkvr9kqr/home/omer
creating /home/omer/tmp/tmpvkvr9kqr/home/omer/tmp
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -O3 -g0 -DMYDEF1 -DMYDEF2 -fPIC -I/usr/include/python3.7m -c /home/omer/tmp/test.c -o /home/omer/tmp/tmpvkvr9kqr/home/omer/tmp/test.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -lz -O3 -g0 -DMYDEF1 -DMYDEF2 /home/omer/tmp/tmpvkvr9kqr/home/omer/tmp/test.o -o /home/omer/tmp/test.cpython-37m-x86_64-linux-gnu.so
```

Additionally, setting DISTUTILS_DEBUG environment variable enables printing extra debug info.

**Comment by nickovs** [comment]
If should be noted that the current handling of `LDFLAGS` is **not** sufficient to properly link shared libraries into cython extensions on most platforms (including Linux) because file order matters to the linker, and the LDFLAGS get included in the wrong place. Consider this minimal example where I have a file `/tmp/math.pxd` which says:
```
cdef extern from "math.h":
     float sinf(float x)
```
and a test module `/tmp/text.pyx` that says:
```
cimport math

cpdef float sin2(float x):
      return math.sinf(x)
```
If I compile this with the command `LDFLAGS="-lm" cythonize -f -i test.pyx` then the compiler uses the following linking command:
```
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -lm /tmp/tmp2399tgsa/tmp/test.o -L/usr/lib -o build/lib.linux-armv7l-cpython-39/test.cpython-39-arm-linux-gnueabihf.so
```
Note the `-lm` is inserted *before* the reference to `test.o`. If I then run `ldd test.cpython-39-arm-linux-gnueabihf.so` I get the following output:
```
	linux-vdso.so.1 (0x7eea3000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76f0f000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76dbb000)
	/lib/ld-linux-armhf.so.3 (0x76f38000)
```
Note that there is no mention of `libm.so`.

If on the other hand I change the link command to the following, with the `-lm` *after* the `test.o`:
```
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 test.o -lm -L/usr/lib -o build/lib.linux-armv7l-cpython-39/test.so
```
then the output of `ldd test.so` is:
```
	linux-vdso.so.1 (0x7eb4f000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76f11000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76ea2000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d4e000)
	/lib/ld-linux-armhf.so.3 (0x76f3a000)
```

This is because file order matters to the linker. As it stands there is no straightforward way to use the command line `cythonize` to build a module that needs to reference other shared libraries.

As a result it would be *very* helpful at the very least for `cythonize` to support a `--libraries` flag to allow the specification of additional libraries to link against.
