### ISSUE TITLE
Spurious ImportWarnings on 3.6+

### ISSUE THREAD

**Issue by pitrou** [cython/cython#1720]
http://bugs.python.org/issue25791 introduced a new warning when an import is attempted with neither `__package__` nor `__spec__` defined in the current globals dict.  This warning now appears with many Cython-compiled extension modules (such as Pandas or multidict).

Diagnosing this is a bit tedious, but Andrew Svetlov's multidict package (https://github.com/aio-libs/multidict/issues/79) is a good starting point.  Apparently the warning isn't displayed when importing the Cythonized module itself but *when importing another module* from the Cython module's top-level.  Case-in-point:

```
$ python -We -c "import multidict"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antoine/multidict/multidict/__init__.py", line 24, in <module>
    __import__('_multidict', globals=globals(), level=1)
  File "multidict/_multidict.pyx", line 1, in init multidict._multidict (multidict/_multidict.c:14817)
    import sys
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

If I move around the "import sys" line in `_multidict.pyx` and re-compile the package, the line number in the traceback above also changes.

Cython may therefore need to define `__spec__` or `__package__` when executing top-level module code. The problem is where it should get it from, so perhaps this is really a CPython issue.

**Comment by pitrou** [comment]
@asvetlov @brettcannon @ncoghlan

**Comment by ncoghlan** [comment]
`__package__` is just a pre-calculated result for `__name__ if '__path__' in globals() else __name__.rpartition('.')[0]` (hence the "falling back on ..." wording in the warning), so the simplest way to get the warning to go away would be for Cython to start setting that attribute automatically during module initialisation.

Setting `__spec__` is trickier, and would probably entail switching Cython over to using multi-phase initialisation on 3.5+: https://github.com/cython/cython/issues/1715

**Comment by pitrou** [comment]
Ok, @ncoghlan and I managed to diagnose the issue: Cython emulates Python 2-style implicit relative imports on Python 3 (see https://bugs.python.org/issue25791#msg294668). To disable the Python 3.6 warning, one has to add `from __future__ import absolute_import` at the top of every Cython source file.

**Comment by seberg** [comment]
Maybe to note, probably had to add those future imports, but in the end on two cases had to do this change on top of that (there was no future import before):
```diff
-from . import _ufuncs
+from scipy.special import _ufuncs
```

**Comment by scoder** [comment]
From a user perspective, it's best to switch on `__future__.absolute_import` and use explicit relative imports (or write Py3 code), because it reduces the overhead at import time. So the warning has its merits. ;-)
I hope to find some time soon to look into multi-phase module initialisation. That should resolve the underlying problem (and then some).

**Comment by pitrou** [comment]
Well, it's a bit surprising to have to add a `__future__` import for a functionality that's actually standard i the Python version you're using ;-)

**Comment by seberg** [comment]
@scoder but the relative import with `form . import _ufuncs` did not seem to work for python modules? Then again, probably I completely misunderstood :).

**Comment by scoder** [comment]
Once Cython code is translated to C, its semantics are fixed. They should not change based on the *Python* version that you build/import the module into. CPython only avoids this issue by not allowing byte code to be reused across the Python 2/3 boundary.

**Comment by pitrou** [comment]
You could use preprocessor macros to switch between the 2.x and 3.x variants, no?

**Comment by scoder** [comment]
We obviously do :-)
With "semantics" I meant Python code semantics, not C code semantics. If the Cython code was written with Python 2.x semantics (and without future import), then the generated C code must emulate those semantics also in Python 3.x. Otherwise, the C code would no longer be platform independent.

**Comment by scoder** [comment]
(and before you ask: yes, there are cases where users still have to care about Py2/3 semantics and compatibility in Cython code themselves, but imports are not on that list.)

**Comment by pitrou** [comment]
I'm not sure what you mean by "platform independent" here. Obviously if I'm running a Cython-compiled module under Py3 I'm expecting it to adopt Py3 semantics, no?

**Comment by scoder** [comment]
Cython code uses Python 2 syntax and semantics by default, but you can switch to Python 3 syntax/semantics with a compiler option. That means that Cython will translate your code with Python 2 *or* Python 3 semantics, and once it's translated and the C code is generated, these semantics must not change anymore, whether you import your module into Python 2 or Python 3.

Changing *source code* semantics based on the *runtime* platform *after* compilation would be very surprising for users. Imagine a C compiler that compiles your code in C89 mode, and then the binary code is executed with C99 semantics because there happens to be a new libc installed in the runtime system.

A side effect of that requirement is that Cython handles many of the Py2/3 differences behind the scenes for you. Take it as a feature.

**Comment by seberg** [comment]
Well, if you compile your module with  `cython3` or `cython -3` you want Py3 semantics, what you run it in should not matter, since its one thing what language you write in and another thing entirely which language you interface to it from.

**Comment by seberg** [comment]
I am still a bit puzzled though, am I mistaking semantics? Why is the `from . import _ufunc` semantics causing a warning (with the `from __future__ import absolute_import` and the `from scipy.special import _ufunc` is not? Really just curious, I am fine with just changing it I think ;).

**Comment by pitrou** [comment]
> Changing source code semantics based on the runtime platform after compilation would be very surprising for users

Why so? What's surprising me is that it doesn't.

>  Imagine a C compiler that compiles your code in C89 mode, and then the binary code is executed with C99 semantics because there happens to be a new libc installed in the runtime system.

Trying to reason about Python (a language without explicit compliation step) by making analogies with C feels misleading to me. Since Cython claims to be compatible with Python semantics (not C semantics), it should follow the Python model of selecting semantics based on whatever runtime is executing the code.

> A side effect of that requirement is that Cython handles many of the Py2/3 differences behind the scenes for you. Take it as a feature.

Not if that displays warnings that are not expected for the given runtime...

**Comment by seberg** [comment]
@pitrou that seems dangerous to me as well. In Python we do this, but that is just a hack because having two code bases is harder then doing the dance of having a single that tries to do the same in two different environments.
Why should cython copy that difficulty when it can provide compatibility without forcing the user to think about both python semantics at the same time? The cython model seems much more sensible to me. With cython you can't get the problem of trying to run a script that has been written in python 2 in your python 3 env, and then get hideous incompatibilities.

**Comment by scoder** [comment]
> Why is the from . import _ufunc semantics causing a warning

You get the warning in that case because it's Python executing the relative import, and for that, it now requires the module to look a certain way, which extension modules don't (at least not while their module init function is executing). This can be changed, and there is an infrastructure for that, but Cython does not use that infrastructure yet. The reason is not the import but the difference between Python modules and extension modules here. This only really shows in Cython modules, because manually written extension modules do not tend to have a similar level of complexity as Cython translated ones. Especially the module level code can have an arbitrary complexity, which is unusual for non-Cython modules.

**Comment by pitrou** [comment]
> In Python we do this, but that is just a hack because having two code bases is harder then doing the dance of having a single that tries to do the same in two different environments.

The thing is, people are _used_ to write dual py2/py3 code. Those people would be familiar with such semantics and not be surprised if Cython worked the same way.

But for some strange reason, Cython goes out of its way to behave differently. That doesn't make sense to me: Cython generally goes to great efforts to try and reproduce CPython semantics (which can be very painful from C), but on this very point it decides to do something else that's completely unexpected *and* produces unduly warnings that are a pain to diagnose (because, first, I didn't expect Cython to do something so ridiculous; second, I had to dig in the generated C code -- not a pretty sight -- to finally understand what was happening).

> Why should cython copy that difficulty when it can provide compatibility without forcing the user to think about both python semantics at the same time?

*I* would rather have to think about Python semantics -- something I'm used to since I do it on a daily basis, like everyone who uses Cython probably -- than about Cython idiosyncracies (which do not seem documented anywhere).

> The cython model seems much more sensible to me. 

No, it's not sensible, it's ridiculous. Python 3 has been _designed_ to break compatibility in many ways. Claiming to bridge the gap using a superset (rather than a subset) of Python is doomed to failure.

**Comment by scoder** [comment]
> Since Cython claims to be compatible with Python semantics (not C semantics), it should follow the Python model of selecting semantics based on whatever runtime is executing the code.

Python actually does the same thing. When you run code in Python 2, it uses the Python 2 parser and generates Python 2 byte code. If you run it in Python 3, it uses a Python 3 parser and generates Python 3 byte code. If you ported the Python 2 parser to Python 3, you could pass Python 2 code into the Python 2 parser, and it could generate Python 3 byte code that runs on Python 3. If the byte code wasn't incompatible, you could also import Python 2 byte code into Python 3 and execute it there. That this has not been done yet is not my fault. ;-)

It's not true that Python has no compilation step. It compiles Python source code to Python byte code. Once that's done, the original source code semantics of that code should not change anymore, regardless of the Python version that you import that byte code into.

**Comment by scoder** [comment]
> Claiming to bridge the gap using a superset (rather than a subset) of Python is doomed to failure.

That's not what Cython does. It gives you Python 2 semantics *or* Python 3 semantics. But once you've translated your code, it does not change those semantics anymore.

You can happily try to take some old Python 2 code and translate it with `cython -3`, i.e. in Python 3 mode. That's probably going to fail. Cython is not different from Python here either.

I think you're missing the important point that the compilation step in Cython is *already* the point where the decision between Python 2 and Python 3 semantics is happening, in the same way that CPython takes that decision at import/parse time. Cython just makes this more visible by splitting parsing and building/importing into separate steps.

**Comment by pitrou** [comment]
> Python actually does the same thing

No, it doesn't. If I give a Python module to Python 2, it uses Python 2 semantics. If I give the same module to Python 3, it uses Python 3 semantics.

> That this has not been done yet is not my fault.

It has not been done because it would be completely counter-productive. The whole point of the Python 2 -> Python 3 transition is to have a clear break in semantics.

> It's not true that Python has no compilation step

Here is what I said: _"a language without **explicit** compliation step"_. Emphasis added so that you don't miss it now...

**Comment by pitrou** [comment]
> I think you're missing the important point that the compilation step in Cython is already the point where the decision between Python 2 and Python 3 semantics is happening

Please.

I'm not missing it, I'm just saying it's confusing and unexpected. I'm not the only one here. There are/were several Cython-based packages suffering from the warning described here... If I hadn't debugged this, those packages probably wouldn't be fixed still, and users would still get polluted with warnings they don't know what to do about.

But if you're fine with confusing your users and letting them painfully diagnose unexpected warnings without even documenting the issue, then why not. It's your decision.

**Comment by scoder** [comment]
Sorry, but it doesn't feel to me like this discussion is leading anywhere. Our users tend to be very happy about the way Cython works here, because it allows them to concentrate on more important issues than differences in Python 2/3 syntax (namely, their code and functionality). It's a very pragmatic approach that solves a real-world issue. If you are unhappy about it, I'll note your input, but I do not see this change as long as Python 2 syntax is still supported by Cython.

I have already freely admitted that the missing `__package__` and `__spec__` fields are something that Cython can improve on, and I've even proposed to invest my own time into solving the issue. I think that's the best I can do.

Thank you also for investing your time into debugging this issue. I was previously not aware of these warnings.

**Comment by bsipocz** [comment]
@scoder - Do you have a timeline for the first python3 only Cython version?

**Comment by scoder** [comment]
Depends on what you are actually asking. ;-)

Since Py2.7 is still maintained in various places until at least 2025, we'll probably keep supporting Python 2 about as long as that, or maybe longer, depending on how long other tools and libraries still support it. However, Cython has its own large user code bases out there, and they might never migrate, if only because they don't have to. The usual rule is, if your module fails to work with a new version of CPython, recompile it with a recent version of Cython. So this is probably even the wrong question to ask entirely.

Whether we switch to Python 3 syntax by default along the way, I don't know, probably yes, but it doesn't matter for the purpose of this question. You can just set the language_level=3 option in Cython, or call cython3, and you get Python 3 syntax and semantics from the compiler, regardless of whether you use your module in Py2 or Py3 afterwards. And that's entirely intentional. The same applies to language_level=2, if we ever switch to Py3 syntax by default. I very much encourage Cython users to write their code in Py3 syntax, simply because it's cleaner in many ways. But it's entirely up to them and doesn't impact the portability of the generated C code.

Does that answer your question, or were you asking something else?

**Comment by scoder** [comment]
Support for PEP 489 / #1715 is implemented in #1794

**Comment by Fil** [comment]
Hello everyone. What is the status of this issue? I think I updated cython to the most recent in miniconda, but I still get this warning.

```
> conda list | grep cython
cython                    0.27.3           py36h6ecb376_0

> conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.18.4
       root environment : /Users/fil/miniconda3  (writable)
    default environment : /Users/fil/miniconda3
       envs directories : /Users/fil/miniconda3/envs
                          /Users/fil/.conda/envs
          package cache : /Users/fil/miniconda3/pkgs
                          /Users/fil/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.0 Darwin/17.2.0 OSX/10.13.1
                UID:GID : 501:20
```

**Comment by jdemeyer** [comment]
> Hello everyone. What is the status of this issue?

The way I understand it: fixed in Cython master, but not yet in a released version.

**Comment by jebob** [comment]
When I run my code normally, I get no warnings, but when I treat warnings as errors (either via `-Werror` or `warnings.simplefilter("error")` I get warnings (converted to exceptions) again.

**Comment by eode** [comment]
@jebob That's probably because the default filter list for python excludes `ImportWarning`s.  'default' not to be confused with `-Wdefault`, which simply means 'warn once'.  The default python warnings filter list is:

```python
# Show deprecation warnings in __main__ once
default::DeprecationWarning:__main__
# Ignore these other warnings altogether.
ignore::DeprecationWarning
ignore::PendingDeprecationWarning
ignore::ImportWarning
ignore::ResourceWarning
```
Unfortunately, you can't get around this warning without disabling `ImportWarning`s altogether (at least in my case, dealing with it while using Pandas), since the `ImportWarning` comes from `importlib` itself.
