### ISSUE TITLE
ERROR: The name '__str__' is reserved for a special method.

### ISSUE THREAD

**Issue by carinancamm** [cython/cython#1797]
Good day,

I have a helper class in my package that replaces the __str__ of the input class when used as a decorator. I am in the process of cythonizing the project and I am encountering such error:
```
[1/1] Cythonizing src/auto_str.py

Error compiling Cython file:
------------------------------------------------------------
...
def auto_str(cls):
    def __str__(self):
   ^
------------------------------------------------------------

src\auto_str.py:2:4: The name '__str__' is reserved for a special method.
```

A simplified version of the project is attached [here](https://github.com/cython/cython/files/1173014/special.zip).

What would be the best approach for this? I'm pretty new with Cython, apologies if I missed some concepts.

Thank you for your patience and hard work!

Using Cython 0.25.2 with Win 7 x64 and Python 3.4.4

**Comment by scoder** [comment]
Thanks for the report, you found a bug in Cython.

I think this is because of the function closure, which Cython internally implements as a cdef class. When declaring `__str__` in the closure, it is incorrectly checked against a condition that only applies to extension types. I'll see what I can do.
