### ISSUE TITLE
Another memoryview memory leak

### ISSUE THREAD

**Issue by stefanmh** [cython/cython#1833]
It looks like there's still another memory leak when using a memoryview, though not as serious:

```py
# Compile: cythonize -bi a.py

# Run: python -c 'import a; x.main()'

from cpython cimport array
import array
import time
import psutil

cdef class X:
	cdef array.array x
	cdef double[:] x2

	def __init__(self):
		self.x = array.array('d', [0.0] * 10000)
		self.x2 = self.x # commenting this out prevents the leak

def mem():
	print str(round(psutil.Process().memory_info().rss/1024./1024., 2)) + ' MB'

def main():
	mem()

	# this somehow leaks less memory
	# for i in xrange(10000):
	# 	X()

	# this leaks memory
	x = [X() for _ in xrange(10000)]
	del x

	mem()
	time.sleep(1.0)
	mem()
```

```
$ rm a.{c,so,html}; cythonize -bi a.pyx && python -c 'import a; a.main()'
...
10.86 MB
70.13 MB
70.13 MB
```

**Comment by scoder** [comment]
Works for me with current master in Py2 but eats a lot of memory in Py3.

**Comment by scoder** [comment]
In Py3, the memory does not actually leak but the heap gets fragmented. You can see it if you change your code to this:
```
        # this leaks memory
        x = [X() for _ in xrange(10000)]
        _ = None  # discard latest integer, just in case
        mem()  # larger than what we will see next
        del x

        mem()  # memory has decreased here
        x = [X() for _ in xrange(1000)]
        mem()  # memory has not increased again, i.e. the heap is fragmented and the new list fits into it
        gc.collect()
        mem()  # no further decrease here

```

**Comment by stefanmh** [comment]
Ah, interesting, thanks for investigating! It's pretty weird that this effect only occurs when we do `self.x2 = self.x`. Commenting that line out prevents the memory issue, so the fragmentation can't have been caused by the `array.array`

**Comment by scoder** [comment]
I'll close this ticket, assuming that it's actually fixed in master. Please reopen (or file a new ticket) if you find that things (still) don't work on your side.

**Comment by stefanmh** [comment]
Well, the memory still goes to hundreds of megabytes in python3 (using master cython).

If the sole cause is indeed memory fragmentation, then maybe not much can be done about it, but I don't *think* that's the only issue here.

**Comment by scoder** [comment]
10000 * 10000 * 8 (64 bit double) = 800.000.000, and that's the size of the array data only. sys.getsizeof() says that the size of the list and all of its elements sum up to about 766MB, and the size of the whole process is 781M on my side. That seems pretty good. Somewhere along that way, memory is allocated that does not get freed by discarding the list, maybe an entry in a freelist or something like that.

Overall, this seems like a very uncommon use case. What application runs for a substantial amount of time and only allocates tons of memory once in its lifetime, just to free it right afterwards? Fragmentation is certainly an issue in CPython, but it's not a big issue for most real-world scenarios.

I'd be happy to see some evidence that there is something that Cython can do in order to improve this, but until then, I believe that my time is better spent in other corners of the project. I'll happily reopen this ticket if you can provide more insights, e.g. from a Python memory profiler. The mere process size is a rather bad measure for actual memory *usage*.

**Comment by stefanmh** [comment]
Yeah, fair enough.
