### ISSUE TITLE
Cython interprets absolute value output as unsigned

### ISSUE THREAD

**Issue by abrahamneben** [cython/cython#1837]
When I compile and import this cython code...
```
cdef int b = 1
print('%d'%(-abs(b)))
```
using these compile commands...
```
from subprocess import check_output

CFLAGS = check_output('python-config --cflags'.split()).decode('utf-8').strip()
LDFLAGS = check_output('python-config --ldflags'.split()).decode('utf-8').strip()

check_output('cython test.pyx'.split())

compile_call = ('clang -c test.c %s'%(CFLAGS)).split()
check_output(compile_call)

link_call = ('clang test.o -o test.so -shared %s'%(LDFLAGS)).split()
check_output(link_call)

import test
```
...I get 4294967295.

**Comment by abrahamneben** [comment]
If I add an `<int>` cast like `print('%d'%(-<int>abs(b)))`, then I get the right answer. What's going on here. Why does cython think the output of `abs` is unsigned?

**Comment by robertwb** [comment]
This is due to https://github.com/cython/cython/commit/0c5fa933b60e9689fac3fd9612ba648ded67d951

Basically, a signed int is not large enough to hold `abs(-MAX_INT-1)`, so the result was changed to return an unsigned value. On the other hand, I agree that using an unsigned value is quite confusing as well, especially as promotion of equally ranked integers is to the unsigned type so it's contagious. Unclear what the best course of action is here...

**Comment by abrahamneben** [comment]
It doesn't seem worth it to have a confusing return value of `abs(int ...)` just to fix an _extreme_ edge case.

**Comment by scoder** [comment]
To me, it doesn't seem worth to generate incorrect code just to simplify an uncommon use case like `-abs(x)`, so there you have it. ;)

Basically, there is no way to do this correctly and safely in C, that's why C chose the unsafe route and left it to the user. Cython tends to take the safer path by default, but here it's unclear which is safer. Obviously, the safest path would be to return a Python integer object (after all, you are calling a Python function here), but I doubt that users would be happy about that.

It might be helpful to generally warn about signed arithmetic with unsigned integer types.

**Comment by scoder** [comment]
The current implementations for `abs(C integer)` are [here](https://github.com/cython/cython/blob/0.26/Cython/Utility/Builtins.c#L230), BTW.

**Comment by robertwb** [comment]
Here's what I think we should do:

* `abs(Z)` returns an `Z` for all integral types `Z`. (Possibly promotion to an int for short and char would be acceptable.)
* We treat `abs(...)` as an arithmetic expression for the purposes of type inference, thus writing
```
a = 3
abs(a)
```
would result in a being typed as a Python object (unless one had `cdef int a` elsewhere, explicitly asking for `C` semantics).

**Comment by scoder** [comment]
That's essentially turning `abs()` from an optimised Python builtin into a distinct Cython language feature. I could get used to that, I guess, but that's not what it feels like to me when I use the function.

I'm sure most users with a non-C-but-Python background would not expect the undefined edge case and thus innocently write incorrect code. I guess you are arguing that this edge case is something to avoid in the first place when restricting the value range?

**Comment by scoder** [comment]
Code search suggests that people don't seem to take any special care:
https://github.com/search?utf8=%E2%9C%93&q=%22abs%28%22+language%3ACython+NOT+py_abs+NOT+%22cdef+int+f%28%29%22+NOT+%22math.h%22+NOT+%22libc.math%22&type=Code

That might mean that they either don't know about the undefined edge case, or that they rely on Cython to do it right, or that they know by design that their code is correct regardless. Probably a mix of all three...

**Comment by robertwb** [comment]
I view the `abs(MIN_INT) == MIN_INT` edge case as a wraparound/overflow error, similar to `MIN_INT == -MIN_INT` or `a + b < a` for large, positive `a` and `b`. Thus I'm suggesting we handle this consistently with other potential arithmetic overflows. Code written with explicit C `ints` (in C or Cython) generally ignore or otherwise guard against values large enough to cause overflows of all kinds, which is why we don't infer variables used in arithmetic to be of integer types by default. 

In context, expressions like `100 - abs(x)` behave very differently than had we used the Python builtin (which returns signed ints), so I think treating the result as an unsigned value is an incorrect optimization, and wrong for nearly all values of x rather than just one of them. 

The `overflowcheck` directive should disallow this edge case with an OverflowError when enabled.

**Comment by scoder** [comment]
Ok
