### ISSUE TITLE
Functions with C++ return type are `extern "C"`

### ISSUE THREAD

**Issue by kb-1000** [cython/cython#1839]
Thats a C++ compiler error.
All functions with C++ in their signatures should be `extern "C++"`.

**Comment by kaeptmblaubaer1000** [comment]
The whole error only exists when the function is `public`.

**Comment by scoder** [comment]
I've never come across "extern C++", so I'm probably the wrong person to review this, but I'd be happy to see a pull request that contains a test showing what goes wrong here, and preferably even adds a fix.

To write a test, look at the `.srctree` files under `/tests/run/`, e.g. this one:
https://github.com/cython/cython/blob/master/tests/run/cpp_assignment_overload.srctree
They are basically a bunch of separate files, separated by marker lines.

**Comment by kaeptmblaubaer1000** [comment]
In C++, `extern "C++"` is the default, but in this case, Cython overrides it with `extern "C"`.

**Comment by gerion0** [comment]
I also encountered this problem and made a minimal working example.

### Source

mwe.cpp
```cpp
#include "mwe.h"

#include <vector>
// this must come _after_ vector
#include "mwe_pyx.h"

std::vector<int> do_stuff() {
	std::vector<int> ret;
	std::vector<int> o = foo();
	for (auto i : o) {
		ret.emplace_back(2*i);
	}
	return ret;
}
```
mwe.h
```cpp
#include <vector>

std::vector<int> do_stuff();
```
c_mwe.pxd
```
from libcpp.vector cimport vector

cdef extern from "mwe.h":
    vector[int] do_stuff()
```
mwe.pyx
```py
from c_mwe cimport do_stuff
from libcpp.vector cimport vector

cdef public vector[int] foo():
    cdef vector[int] ret = [1, 2, 3]
    return [1, 2, 3]

def func():
    cdef vector[int] a = do_stuff()
    for i in a:
        print(i)
```
meson.build
```meson
project('cython-test', 'cpp',
  version : '0.1',
  default_options : ['warning_level=3', 'cpp_std=c++14'])

cython = find_program('cython', version: '>=0.29.14')
cython_flags = ['-Wextra', '--cplus', '-3']

mwe_pyx = custom_target('mwe_pyx',
  output: ['mwe_pyx.cpp', 'mwe_pyx.h'],
  input: files('mwe.pyx'),
  depend_files: files('c_mwe.pxd'),
  command: [cython, '@INPUT@', '-o', '@OUTPUT0@'] + cython_flags,
)
mwe_pyx_header = mwe_pyx[1]
mwe_pyx_cpp = mwe_pyx[0]

py3_mod = import('python')
py3 = py3_mod.find_installation('python3')

mwe_mod = py3.extension_module('mwe',
  mwe_pyx_cpp,
  'mwe.cpp',
  dependencies: [py3.dependency()]
)
```

### Compiling

```
[1/4] /usr/bin/cython ../mwe.pyx -o mwe_pyx.cpp -Wextra --cplus -3
[2/4] clang++ -Imwe.cpython-310-x86_64-linux-gnu.so.p -I. -I.. -I/usr/include/python3.10 -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++14 -O0 -g -fPIC -MD -MQ mwe.cpython-310-x86_64-linux-gnu.so.p/mwe.cpp.o -MF mwe.cpython-310-x86_64-linux-gnu.so.p/mwe.cpp.o.d -o mwe.cpython-310-x86_64-linux-gnu.so.p/mwe.cpp.o -c ../mwe.cpp
In file included from ../mwe.cpp:5:
./mwe_pyx.h:22:34: warning: 'foo' has C-linkage specified, but returns incomplete type 'std::vector<int>' which could be incompatible with C [-Wreturn-type-c-linkage]
__PYX_EXTERN_C std::vector<int>  foo(void);
                                 ^
1 warning generated.
[3/4] clang++ -Imwe.cpython-310-x86_64-linux-gnu.so.p -I. -I.. -I/usr/include/python3.10 -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++14 -O0 -g -fPIC -MD -MQ mwe.cpython-310-x86_64-linux-gnu.so.p/meson-generated_.._mwe_pyx.cpp.o -MF mwe.cpython-310-x86_64-linux-gnu.so.p/meson-generated_.._mwe_pyx.cpp.o.d -o mwe.cpython-310-x86_64-linux-gnu.so.p/meson-generated_.._mwe_pyx.cpp.o -c mwe_pyx.cpp
mwe_pyx.cpp:1176:34: warning: 'foo' has C-linkage specified, but returns incomplete type 'std::vector<int>' which could be incompatible with C [-Wreturn-type-c-linkage]
__PYX_EXTERN_C std::vector<int>  foo(void); /*proto*/
                                 ^
1 warning generated.
[4/4] clang++  -o mwe.cpython-310-x86_64-linux-gnu.so mwe.cpython-310-x86_64-linux-gnu.so.p/meson-generated_.._mwe_pyx.cpp.o mwe.cpython-310-x86_64-linux-gnu.so.p/mwe.cpp.o -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC
```

### Fix

Currently, `__PYX_EXTERN_C` is defined as:
```cpp
#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif
```

AFAIK, `extern` exports the symbol to the linker, while `extern "C"` additionally avoids name mangling and makes linking to C code possible.
I don't see why `extern "C"` should be necessary here at all since all code is compiled and linked with C++.
Therefore, I would just suggest:
```cpp
#ifndef __PYX_EXTERN_C
  #define __PYX_EXTERN_C extern
#endif
```
Applying this to the above MWE fixes the warning, while the module compiles, links, and runs as expected.

**Comment by EpigeneMax** [comment]
## Outside Cython
- A C function can only have C linkage. Period. `extern` merely indicates that the function is only *declared*, not defined, in the current compilation unit.
- A C++ function can have either C++ (the default) or C linkage. It is up to the programmer.
  + A function with C++ linkage can (in theory) only be linked (hence called) from C++ code.
  + A function with C linkage is more versatile: it can be called from either C or C++ code. Obviously versatility comes at a cost: all types in the function signature should be C (e.g. no C++ class, no reference). It is up to the programmer of `extern "C"` functions to make sure that they provides a header for both C and C++. It is usually a single file with conditional macros.

So C++ programmers can choose to expose a C interface, or a C++ interface, with a granularity at the level of the function.

## In Cython
C mode generates C code with C interface. 
Because `cdef public` can use C++ types (e.g. `std::vector`), I consider that C++ mode generates C++ code.
**Now the problem is that Cython in C++ mode provides no way to choose between C or C++ linkage.**
The current behavior is unconditionally C interface, the changes I propose in #5040 implement an unconditional C++ interface.

## Rephrasing the problem
Cython in C++ mode provides no way to choose between C or C++ linkage.

I really cannot think of a way to achieve C linkage for C++ functions in Cython, even considering convoluted designs such as C mode pyx file exposing the functions defined in another C++ mode pyx file.

## Possible solution
I am starting to think that the appropriate solution is to add a keyword to Cython.
Maybe a `cppdef`, commanding C++ linkage, while `cdef` would command C linkage. The downside is that a pyx file containing `cppdef` could only be cythonized in C++ mode.
Or a new keyword `clinkage` or `externc` that would have no effect when in C mode:
- `cdef public externc foo()` commands C linkage, both in C and C++ mode
- `cdef public foo()` commands C linkage when in C mode, C++ linkage when in C++ mode

**Comment by da-woods** [comment]
Thinking about it, there's an easier way (that actually already works): the user can declare the `__PYX_EXTERN_C` macro themselves. So I think the best thing to do is what you've done. You default it to `extern "C++"` when compiled in C++ mode. That's generally likely to be right. However, a user that has written an interface that's suitable for `extern "C"` can just define it themselves when they compile it.

**Comment by EpigeneMax** [comment]
OMG you are right!
I was overthinking the per-function granularity, though I do not think either that the issue is big enough to justify a new keyword.

It may be worth a few words in the documentation.
