### ISSUE TITLE
Update version number to 1.0

### ISSUE THREAD

**Issue by davidh-ssec** [cython/cython#1883]
Cython uses a "0.x" style of versioning. This can make it difficult to distinguish smaller bug fix releases from major feature releases. Many projects adopt a X.Y.Z style of versioning where the major (X) number denotes large project or API changes, the minor (Y) number denotes new or changed features, and the micro (Z) number denotes bug fixes or patches.

Also having a version less than 1 may cause the uninitiated to think that the project is unstable, in early development, or is not suited for operational use when in fact it is and has been used in this way for a while.

Is there any chance that Cython's next release or a release in the near future could be changed to 1.x.x?

**Comment by robertwb** [comment]
Cython follows this numbering, with minor (Y) releases denoting new or changed features, and micro (Z) numbers primarily bug fixes. We have not yet had a "large project or API change" that would merit bumping the major version number, and as this thread is about messaging, I'd like to point out that doing so would also send a message, so it's unlikely to "just happen" because time passed. 

We had discussions years ago about what 1.0 would look like: what we should be sure to get in, what we'd like to finally cut/simplify. That's a fine topic to open (though a wiki page or mailing list would be a more appropriate forum than a github issue).

**Comment by davidh-ssec** [comment]
You're absolutely right. This would have been better on the mailing list (I didn't realize there was one, sorry). I also didn't realize there was a 1.0 github milestone or that there have been any releases with the micro version number. Feel free to close.

**Comment by scoder** [comment]
Closing, since setting the version number to 1.0 is the last thing I'd expect us to forget once we're there.
