### ISSUE TITLE
Cython 0.27: Bug importing extension class twice on Python3

### ISSUE THREAD

**Issue by prabhuramachandran** [cython/cython#1894]
Cython 0.27 introduced a Python 3 specific issue that breaks re-importing a module containing an extension class twice.  Attached is a ZIP file containing two tiny files that reproduce the problem on MacOS and Linux. Simply unzip the archive, and run `test_load_twice.py` you'll get a traceback that looks like this:

```
Traceback (most recent call last):
  File "test_load_twice.py", line 24, in <module>
    load(name)
  File "test_load_twice.py", line 18, in load
    return imp.load_module(name, file, path, desc)
  File "/Users/prabhu/.edm/envs/py3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/prabhu/.edm/envs/py3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 913, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "cy_ext.pyx", line 2, in init cy_ext
    cdef class Thing:
AttributeError: type object 'cy_ext.Thing' has no attribute '__reduce_cython__'
```
This does not fail on Python 2.7.x and also does not fail on Cython 0.26.1.

[Archive.zip](https://github.com/cython/cython/files/1338479/Archive.zip)

**Comment by scoder** [comment]
Thanks. The quickest work-around is to define the C macro `CYTHON_PEP489_MULTI_PHASE_INIT=0`.

**Comment by scoder** [comment]
I've disabled that feature for 0.27.1. It's just too risky for now.

**Comment by prabhuramachandran** [comment]
Thank you!

**Comment by cschramm** [comment]
Hi, we're experiencing a similar issue (AttributeError for `__reduce_cython__`) in an embedded environment when we use Cython 0.26.1 to build lxml. It works fine if we use 0.25.2. The issue seems to be triggered by reinitializing the environment but unfortunately I was not able to find a minimal sample that replicates it yet.

It seems like the precise issue discussed here is thought to be caused by a feature added in 0.27.0, right? So that shouldn't be the very same issue we have with 0.26.1. However, e.g. https://github.com/openai/mujoco-py/issues/131#issuecomment-332636429 looks like others are having similar situations with 0.26 as well.

**Comment by scoder** [comment]
Likely not the same problem. If you can reproduce it with 0.27.2 (please also check the first line in the .c file), could you please open a new ticket?

**Comment by linas** [comment]
Seems to be duplicate of issue #1953 ? We are hitting this in https://github.com/opencog/atomspace/issues/1888
