### ISSUE TITLE
Dealing with double ref in cdef extern

### ISSUE THREAD

**Issue by Berserker66** [cython/cython#1929]
So, first time trying to access an external C library, a small one fortunately.

But running into this issue:

```
Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "open-simplex-noise.h":
    ctypedef struct osn_context:
        pass

    int open_simplex_noise(int64_t seed, struct osn_context **ctx)
                                                           ^
------------------------------------------------------------

opensimplex\copensimplex.pxd:5:60: Expected ')', found '**'
```

The documentation says that usually you can just copy the header - which I did. But this is apparently not easily copy-able, further I found nothing in the docs on how to deal with double ref in an extern C declaration. The entire thing is in this dropbox folder if you'd like to investigate:
https://www.dropbox.com/sh/m7hucwvpgzne5vo/AABWp9qtqNNkFjvoufRilX9Qa?dl=0

**Comment by Berserker66** [comment]
Ok, derp. Turns out removing struct from all the definitions clears up most errors. But how to deal with int64_t? it now complains about `'int64_t' is not a type identifier`

**Comment by robertwb** [comment]
This is a user support issue that would be better asked on the mailing list.

In any case, don't declare it as ``struct osn_context **ctx``, just ``osn_context **ctx``. You should also check whether you need ``cdef struct osn_context`` rather than ``ctypedef struct osn_context``, see https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#styles-of-struct-union-and-enum-declaration

(Whoever decided that ``struct X`` should live in a different namespace than ``typedef ... X`` I don't know, but we're still stuck with it years later...)

**Comment by robertwb** [comment]
``int64_t`` isn't a type unless you've declared or cimported it from somewhere.
