### ISSUE TITLE
Add CYTHON_NO_EXPORTS macro.

### ISSUE THREAD

**Issue by AraHaan** [cython/cython#1944]
The reason for this macro is for when someone wants to ``PyImport_AppendInittab`` an cython C code generated module on their own embedded python interpreter. As such then it avoid's exporting symbols on exe files which is a bad idea.

```diff
#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init[modulename](void); /*proto*/
PyMODINIT_FUNC init[modulename](void)
#else
+ #ifdef CYTHON_NO_EXPORTS
+ /* when compiling cython code in user made embedded python applications.*/
+ #undef PyMODINIT_FUNC
+ #define PyMODINIT_FUNC PyObject*
+ #endif
PyMODINIT_FUNC PyInit_[modulename](void); /*proto*/
```

And yes it's good to have this define constant in all cython generated modules to prevent the annoying exports. In this case of mine I must use cython on this module and I must not use cython for the embedding as I have to run some other things on it on top of the cython stuff that the cythonized module cant do.

When I added this it has no difference in runtime and it does not export the ``PyInit_`` function on the module it uses as I am embedding python 3.6.x.

**Comment by scoder** [comment]
I'm generally ok with adding something like this, but I would make the name more specific, like `CYTHON_NO_PYINIT_EXPORT`. And I would also like to avoid redefining `PyMODINIT_FUNC` and instead use a separate internal macro `__Pyx_PyMODINIT_FUNC`.

Please provide a pull request, including test and documentation. See the embedding test for that, under `Demos/embed`. Probably also something to consider in `cython_freeze`.

And since you asked: no, this is nothing to add in a bug-fix point release.

**Comment by AraHaan** [comment]
alright, mind assisting me on what file I got to edit to implement this thing and it is true I should change it to ``CYTHON_NO_PYINIT_EXPORT`` and not redefine ``PyMODINIT_FUNC``.

**Comment by AraHaan** [comment]
Alright so, I just need the test and a change of documentations in places.
