### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by easysg** [cython/cython#1972]
```
%%cython --annotate
def a(price:float=None, ndigits=4):
    print(price)

a(3.3)
```
output
```
TypeError: a float is required
```

change float to int work fine.
```
%%cython --annotate
def a(price:int=None, ndigits=4):
    print(price)

a(3.3)
```

python3 -V
```
Python 3.5.2
```
cython --version
```
Cython version 0.27.2
```

**Comment by scoder** [comment]
Oh well... It's the default argument. Cython infers C `double` for `price`, and fails to see that the Python object `None` is also being assigned.

Actually, it's not really correct to infer a C type for type-hinted arguments, since it prevents passing `None`, i.e. it changes semantics. I completely missed that case.

I'll see what I can do.
