### ISSUE TITLE
problems with user and group atts set on files in release tarball in Docker (ubuntu:latest)

### ISSUE THREAD

**Issue by cyrush** [cython/cython#2052]
It seems the Cython-0.25.2  source tarball fetched from pipy has some security attributes set related to users and groups, that undermine untarring for me when running Docker (ubuntu:latest)

Here is an example of tar erroring when trying to extract the files:

```
/bin/tar: Cython-0.25.2/.gitrev: Cannot change ownership to uid 96258, gid 5000: Invalid argument
.... (many many more errors)
/bin/tar: Cython-0.25.2/USAGE.txt: Cannot change ownership to uid 96258, gid 5000: Invalid argument
/bin/tar: Cython-0.25.2: Cannot change ownership to uid 96258, gid 5000: Invalid argument
/bin/tar: Exiting with failure status due to previous errors
```

**Comment by scoder** [comment]
1) GNU tar has an option `--no-same-owner` that would probably fix this (are you extracting the sdist as `root` user inside of the container?)
2) 0.25.2 is about a year old by now
3) consider using wheels instead of sdists

Closing, please reopen if it also applies to the latest sdist and the above does not help.

**Comment by cyrush** [comment]
@scoder, thanks!

I am not executing the untar directly  -- but I can lobby for ``--no-same-owner`` option for spack, which is building cython. 

I'll try to check if newer sdist has the same issue. 

Though I am building in docker, its to test a build process used to build from source on several HPC platforms where wheels aren't an option.
