### ISSUE TITLE
Failed when compiling builtin exception ConnectionRefusedError

### ISSUE THREAD

**Issue by ramonz** [cython/cython#2087]
I trying to compile python 3.5+ code and got the error:
```
✗ cython -3 -v -X always_allow_keywords=True -D /tmp/tmpbuleJY/file.py
Compiling /tmp/tmpbuleJY/file.py

Error compiling Cython file:
------------------------------------------------------------
...

                    if Settings.VERBOSE:
                        logging.debug(f'<- {repr(message)}')

                    await self._process_message(message)
        except ConnectionRefusedError:
              ^
------------------------------------------------------------

/tmp/tmpbuleJY/file.py:156:15: undeclared name not builtin: ConnectionRefusedError
✗ cython --version                                                                                 
Cython version 0.28a0
```

Any suggestions?

**Comment by scoder** [comment]
You're probably running Cython in Python 2.x, where this isn't a builtin yet. That's why Cython doesn't detect it automatically but needs to be told about it.

Since this isn't portable (you'd get a `NameError` at runtime for your code in Python 2.x), we should support this only as a non-cachable builtin that is really only looked up at need. Otherwise, the generated module would look it up at module init time and fail to import in Py2.

You may still want to use a portability fallback to OSError to make it work in Py2. Cython can't (easily) do that for you, since broadly catching `OSError` instead would not catch the semantics of code that wants some `ConnectionError`.
