### ISSUE TITLE
Large output size of compiled code

### ISSUE THREAD

**Issue by mrocklin** [cython/cython#2102]
Hi All, 

I'm trying to reduce the packaged size of the scientific computing ecosystem to make it friendlier for distributed deployments using tools like docker, kubernetes, etc..  An issue for this topic generally is here: https://github.com/ContinuumIO/anaconda-issues/issues/8242

One important issue that came up from @mingwandroid relates to Cython, see https://github.com/ContinuumIO/anaconda-issues/issues/8242#issuecomment-359524128

> It seems the shared libraries are chock full of instruction code

> PyInit_cython_special is huge; more than 1MB.

> why all of these movq instructions are not being coalesced into a memset.

In a separate conversation he said the following:

> Now ideally you'd like your compiler to be smart enough to coalesce all those clears over the whole object into 1 memset, and then even better, put them all together so that a single memset could do it.
> the package size on disk is swamped by the instructions to do these clears!
> instead of a call to a function to memset it's a huge amount of instructions, like tens of thousands.
> and that takes space on the extension module text segment.

To be honest, I don't have much expertise here, but I thought I'd raise an issue here in case this sort of problem can be resolved within Cython, or, if not, if anyone here has any additional helpful thoughts. 

Thank you all for your time.

**Comment by scoder** [comment]
Thanks for bringing this up. As a quick improvement, I enabled `-Os` (optimise for size instead of speed) only for the module init function, and only under gcc for now. For a couple of arbitrarily chosen, -O3 compiled and stripped .py modules, the total .so file size reduction that I could see was 0-3%. So, not useless, but also not impressive. More of a "no reason not to do it" kind of improvement. You can add `-DCYTHON_SMALL_CODE=` to your CFLAGS to disable it and see the difference.

I can't say without further investigation what all those `movq` commands do, but the module init function does a lot of initialisations of various objects, variables and structures. Probably worth taking a look, but it's not necessarily just "stupid code". The C code is most likely easier to analyse than the assembly.

**Comment by scoder** [comment]
@mingwandroid, would it be possible for you to figure out what generated C code leads to those ``movq`` instructions that were mentioned over in the anaconda ticket? Compiling with debug symbols might give some hints.

**Comment by scoder** [comment]
I disassembled another module now that I had lying around, and I think those ``movq`` series are simply the initialisation of local (temp) variables. The module init function in question just happens to have many of them. But the size is certainly dominated by the actual code, not the variable initialisation. So this is not an interesting track.

**Comment by mrocklin** [comment]
@scoder thank you for spending the time to look into this.  I appreciate it. 

Broadening out my question a bit, it seems like libraries that make heavy use of Cython tend to have large binaries (~10-50MB).  Are there things that can be done from within Cython to improve this situation?

**Comment by scoder** [comment]
Cython definitely generates a lot of C code and widely uses inline functions that result in even larger assembly code size. That's partly where the performance comes from. I can certainly see an argument for reducing the code optimisation inside of the module init function. I doubt that this would have a measurable negative impact on the import time, and it might even have a positive effect due to smaller modules.

I disabled method unpacking in module level code now, which gives another bit of size reduction, depending on the number of function calls at the module level.

We also considered a special "optimise for size" directive in Cython, but let's face it, you can't beat Python bytecode when it comes to size, so the best you can do if you want small modules is to *not* compile them, or at least not all of their code. (Although, now that I write this - Cython could obviously do that, too, i.e. it could detect longer pure Python code sections in the module init code and output them as interpreted Python code ... Probably not something to implement tonight...)

**Comment by mingwandroid** [comment]
The new `-Os` optimization seems to have shaved a good bit (~30% AFAIR) from the pandas cython_special init function, but overall it's still pretty large.

For clang `-Oz` is the best flag to pass for space optimization. Should I open an issue about that?

**Comment by scoder** [comment]
Cool, 30% is a lot, I didn't expect anything in that range.

Regarding clang, is there a compiler directive that would enable this flag locally, as for GCC? The docs that I found last time basically just said "directives in clang tend to be the same as for gcc", but the `optimize()` directive apparently isn't supported, at least by clang 3.8.

If anyone finds such an option for clang, I'd be happy to see a PR that adds it here:

https://github.com/cython/cython/blob/bd023b4e4f375ce0c90e85a2bf6302565f9276be/Cython/Utility/ModuleSetupCode.c#L696-L704

**Comment by scoder** [comment]
I compared all of Cython's own compiled modules (which are somewhat but not overly diverse in their feature usage) and found that the total size reduction for each of the module files in the latest master branch is a pretty consistent 3-4%. Definitely far from 30%, but I didn't check the separate segments or pure function sizes.

**Comment by jakirkham** [comment]
Sorry if this was already asked and I missed this, but is it possible to export a sizeable portion of Cython functionality to say an external shared object (e.g. `libcython.so`) that other packages can depend on? Would understand if not all things can go this way, but would like to find out how much could.

**Comment by scoder** [comment]
Yes, this idea keeps coming up from time to time. I couldn't find a ticket for it, so I created a new one to keep track of the discussion (#2356).

**Comment by cpcloud** [comment]
I spent a little bit of time seeing what adding `-Wl,--strip-all` to `extra_link_args` and `-Os -g0` to `extra_compile_args` of both scikit-image and scikit-learn, libraries that are known to leverage Cython quite heavily.

Adding these flags shaves about 7x off the total size of all of the SOs compiled by scikit-learn. The default compilation triggered by `python setup.py develop` yields a total of 35MB worth of SO files and with those flags the total size is 5MB.

For scikit-image the savings are similarly dramatic. Including debug symbols and using `-O3` instead of `-Os` the total size of all SOs is 58MB, with the above flags the total size is 7.3MB which is a savings of about 8x.

I'm not sure why the default flag of `-g` is included in C extensions, but this isn't a Cython issue per se. We should think about solving this issue for everyone and potentially changing the default, or at least providing a way to easily configure these flags for more complex distutils/setuptools setups (like scikit-image and scikit-learn)

**Comment by scoder** [comment]
Do you know (or could you find out) what the impact of only `-Os` vs. `-O3` is for these libraries? My guess is that the bulk of the difference in your tests actually came from stripping the libraries, so I would be interested in having real-world numbers only for the result of using `-Os`, as that is more specific to the code that Cython generates.

**Comment by cpcloud** [comment]
I don't have the numbers on hand, but I did look at that and it was about a factor of 2 in both cases iirc when just using `-Os`. So it's definitely the case that stripping removed the lion's share of the bulk. There are really two issues here: 1) it's unclear why the ecosystem at large doesn't ship their compiled libraries stripped, and 2) whether optimizing for size is something cython should handle. IMO both should be handled by library authors. Potentially there should be a flag for release and debug modes that is extensible so that folks can customize compiler and linker flags. That's a an issue that I will bring up on pypa if it hasn't been brought up already.

**Comment by mingwandroid** [comment]
>  it's unclear why the ecosystem at large doesn't ship their compiled libraries stripped

When debugging segfaults debug info is very useful, at least being able to see a stack trace at minimum is essential.

**Comment by cpcloud** [comment]
I understand why it's useful. C++ libraries have had to deal with this problem long before python existed. I don't think there's anything special about python that necessitates shipping user facing libraries that contain debug symbols.

**Comment by mingwandroid** [comment]
As someone on the Frontline of support when a package segfaults on and end user's machine I disagree. However I do agree that if we had a mechanism in place to split debug info into separate packages and another to make it easy for users to get these installed I'd definitely be interested in persuing that. This is what most Linux distros do with debug info.

**Comment by mingwandroid** [comment]
There's nothing special about python that *necessitates* it, it's just hugely useful to have that info when there's *any* C or C++ involved (which is the case with `Cython`). I can perform one of the hardest parts of diagnosing problems (where did it crash?) with just that info instead of needing to liaise with the user, make a debug build for them to try, hope it's the same from the perspective of this bug etc, etc.

I have also seen time and time again that stripping saves around 20-30%, while nothing to be sniffed at we're still far from 7x. Can you give exact reproduction steps for arriving at 7x? Are you using conda? conda-forge recipes?

I see two options for stripping:
1. Remove everything except function names.
2. Split the info into a separate package and make it easy for people to install these (but that would still introduce extra round trips of communication with the user in many cases I fear).

**Comment by mrocklin** [comment]
Checking in here.  It looks like there is an outstanding question for @cpcloud here::

> Can you give exact reproduction steps for arriving at 7x? Are you using conda? conda-forge recipes?

@mingwandroid I appreciate the need to make debugging smoother.  I also think that shipping around 100MB of debug information for pandas for the occasional bugfix (no matter how deep) is also costly in a few ways.  Obviously there is some tradeoff here to be mindful of in both directions.

My understanding is that shipping debug information by default is not the standard practice, and that instead it's common to include them in additional packages.  Is this possible and likely to happen with our current conda infrastructure?

**Comment by cpcloud** [comment]
@mrocklin I will post the steps to reproduce the size gains this weekend.

**Comment by mingwandroid** [comment]
> My understanding is that shipping debug information by default is not the standard practice, and that instead it's common to include them in additional packages. Is this possible and likely to happen with our current conda infrastructure?

Hopefully someday.

**Comment by cpcloud** [comment]
@mrocklin @mingwandroid Here's a gist with steps to reproduce: https://gist.github.com/cpcloud/995c80b1eeae09b8bd24e63a3f488bc2

**Comment by mrocklin** [comment]
Thank you for the script @cpcloud .  That was easy to replicate and modify.

People were asking about the relative effect of stripping vs the `-Os` flag, so I ran this on Pandas with only the `-Wl,--strip-all` linker flags (leaving the `-Os` and `-g0` compiler flags alone) and got a size reduction of 79MB->16MB.

```diff
diff --git a/setup.py b/setup.py
index 621655d..79f6ca4 100755
--- a/setup.py
+++ b/setup.py
@@ -460,6 +460,8 @@ else:
     # args to ignore warnings
     extra_compile_args = ['-Wno-unused-function']
 
+extra_link_args = ['-Wl,--strip-all']
+
 lib_depends = lib_depends + ['pandas/_libs/src/numpy_helper.h',
                              'pandas/_libs/src/parse_helper.h',
                              'pandas/_libs/src/compat_helper.h']
@@ -690,7 +692,8 @@ for name, data in ext_data.items():
                     include_dirs=include,
                     language=data.get('language', 'c'),
                     define_macros=data.get('macros', []),
-                    extra_compile_args=extra_compile_args)
+                    extra_compile_args=extra_compile_args,
+                    extra_link_args=extra_link_args)
 
     extensions.append(obj)
 
@@ -716,7 +719,8 @@ ujson_ext = Extension('pandas._libs.json',
                                     'pandas/_libs/src/ujson/lib',
                                     'pandas/_libs/src/datetime'],
                       extra_compile_args=(['-D_GNU_SOURCE'] +
-                                          extra_compile_args))
+                                          extra_compile_args),
+                      extra_link_args=extra_link_args)
 
 
 extensions.append(ujson_ext)
```

Two questions:

1.  I'd like to raise this topic for discussion more broadly, probably with a small blogpost and a lightning talk at SciPy.  @cpcloud any interest in writing something or delivering a lightning talk if you're around?  I can also draft up something small and credit you with the work if that's preferable
2.  I'd like to see what the size effect is of applying the stripping to the packages that Anaconda ships with.  Is there a way to apply this process to all so's in an environment in one go?

**Comment by jakirkham** [comment]
How does that compare to `-O2`?

**Comment by scoder** [comment]
>  Is there a way to apply this process to all so's in an environment in one go?

See the `strip` command.

**Comment by cpcloud** [comment]
>> Is there a way to apply this process to all so's in an environment in one go?

> See the strip command.

I'd recommend against `strip`ping all of the SOs in a conda environment. `conda` will spew a ton of warnings when performing any operations that require verification of the checksum of any SOs.

**Comment by cpcloud** [comment]
@mrocklin I'd be happy to write something up. Is there a public place we can chat in real time about this or a place that doesn't require us to hijack this thread? :)

**Comment by mrocklin** [comment]
I'd be happy with any of gchat, video call, gitter, etc.. If you're
swinging by Hugo's place on the 4th we could also figure things out there.

**Comment by jjhelmus** [comment]
Chiming in with another set of metrics on package sizes.  
I built pandas 0.23.1 using the recipe from [AnacondaRecipes/pandas-feedstock](https://github.com/AnacondaRecipes/pandas-feedstock) using the set of compilers flags (-O2, no -g) in the gcc 7.2 compiler activation script in the `defaults` channel.  I then rebuilt the package using `-Os -g0` and/or `-Wl,--strip-all`.  The results are as follows:

| Setting | package size packaged | package size unpacked |size of shared libraries |
| ------- | ------------------------ | ----------------------- | --------------------- |
| -O2 | 12 MB | 57 MB | 17.98 MB |
| -Wl,--stip-all | 11MB | 56MB | 16.09 MB |
| -Os -g0 | 10 MB | 53 MB | 13.46 MB |
| -Os -g0 AND -Wl,--strip-all | 10 MB | 51 MB | 11.53 MB |

Stripping drops the size of the shared libraries by ~10% where as `-Os` drops the size by 25% at the expense of losing some performance optimizations.  These can be combined for a ~35% size decrease.

**Comment by jjhelmus** [comment]
I suspect that the larger size reductions was a result of comparing against libraries which were build with a high level of debugging information. For example compiling pandas with `-g` (debug level 2) gives a shared library size of 74 MB.

**Comment by mrocklin** [comment]
Do we have a sense for why the unpacked package size is 50MB?

**Comment by jjhelmus** [comment]
> Do we have a sense for why the unpacked package size is 50MB?

Python files are second in size next to the shared libraries followed by .pyc files.  
For the conda package in defaults the size of the various extensions are:

| extension | size of all files with extension (bytes) |
| -- | -- |
.so     |    17_980_608
.py     |    12_289_852
.pyc    |    9_885_825
.xpt     |   5_979_840
.sas7bdat |  3_260_416
.csv      |  2_357_772
.pickle  |   2_010_058
.msgpack |   581_494
.html     |  551_714
.h5        | 411_276
.json      | 392_749
.xls        | 387_072
.xlsx      | 242_727
.xlsm     |  201_672
.dta       | 141_561
.txt       | 58_551
.gz        | 12_576
.tar        | 10_240
.yaml      | 3_546
.tpl       | 2_045
.bz2     |   1_906
.zip      |  1_166
.template |  1_122
.feather   | 672
.sh        | 404
.xz        | 336
.mp       |  309
.jsonl     | 33

**Comment by mrocklin** [comment]
I'm curious, how did you produce that table?

**Comment by jjhelmus** [comment]
I used the bash snippet from [this stack overflow question](https://serverfault.com/questions/367185/calculating-total-file-size-by-extension-in-shell) to find the sizes of all the files for each extensions and then formatted the output into GitHub flavored markdown.

**Comment by scoder** [comment]
@jwilk noted in #2494 that the `optimize` attribute in GCC is apparently somewhat ill designed and its use discouraged. That's unfortunate, since the usage was simple and brought a visible effect.

However, the numbers in the previous comments were (IIUC) referring to building the entire library with `-Os`, and not just the module init functions. Therefore, they probably overstate the impact of using the `optimize` attribute quite substantially.

**Comment by scoder** [comment]
I found the GCC attribute [cold](https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Common-Function-Attributes.html#index-cold-function-attribute), which seems to match exactly our purpose and its usage is not discouraged. The docs say that it's ignored when PGO is used, but the profile should equally detect that the module init function is almost never called. :)

**Comment by mingwandroid** [comment]
Nice!

[Beware that older GCCs do not support](https://gcc.gnu.org/onlinedocs/gcc-4.9.4/gcc/Function-Attributes.html#Function-Attributes) `cold`:

```
The cold attribute on functions is not implemented in GCC versions earlier than 4.3.

The cold attribute on labels is used to inform the compiler that the path following the label is unlikely to be executed. This attribute is used in cases where __builtin_expect cannot be used, for instance with computed goto or asm goto.

The cold attribute on labels is not implemented in GCC versions earlier than 4.8. 
```

**Comment by jakirkham** [comment]
FWIW there is a [proposal]( https://github.com/cython/cython/issues/2356#issuecomment-399752159 ) to have a per package shared object, which would gather together all functions used by other Cython shared objects in the package and would be dynamically linked to them. This may also help cutdown on redundant copies of functions.

**Comment by hmaarrfk** [comment]
For reference, it seems that @matthew-brett already incorporated this in his multibuild scripts.
https://github.com/matthew-brett/multibuild/blob/fd9e458361ce01033b350978b1c768e7576d84de/configure_build.sh#L32

Does conda-forge do the same.

**Comment by mingwandroid** [comment]
Please no. Blanket stripping of symbols makes debugging impossible.

**Comment by mingwandroid** [comment]
*Splitting* the debug info into separate packages I would support, but someone would have to do some work for that. PRs to conda-build to add this would be welcome.

**Comment by mingwandroid** [comment]
Since most of you appear to be pythonistas, can I just ask how you'd feel and how it'd effect your workflow if every python package stripped its symbols (somehow) and all your backtraces were useless?

So asking people to do the same for C/C++ is asking use C/C++ people to put up with exactly the same. No. Please no.

**Comment by scoder** [comment]
FWIW, from the PoV of a maintainer, I also prefer having debug symbols in libraries. gcc's default level is 2, so maybe passing `-g1` would provide a better tradeoff. The most helpful thing in remote debugging is a properly named stack trace, everything else may or may not provide an advantage in a given situation but contributes to the library size.
```
   -glevel
      Request debugging information and also use level to specify how much
          information. The default level is 2.
      Level 0 produces no debug information at all.  Thus, -g0 negates -g.
      Level 1 produces minimal information, enough for making backtraces in
          parts of the program that you don't plan to debug.  This includes
          descriptions of functions and external variables, and line number
          tables, but no information about local variables.
      Level 3 includes extra information, such as all the macro definitions
          present in the program.  Some debuggers support macro expansion
          when you use -g3.
```

**Comment by hmaarrfk** [comment]
@scoder I will definitely bring that up.

FWIW, fedora automatically strips binaries (I'm not sure to what level) and creates `debuginfo` packages for when that information is necessary. I wonder if such a solution could be implemented with python.

```
pip install numpy-debuginfo
```
```
conda install numpy-debuginfo
```

**Comment by mingwandroid** [comment]
@hmaarrfk please read the comments before repeating the ideas I already proposed!

**Comment by scoder** [comment]
FYI, I implemented #2292, deduplication of constant tuples and slices. It might reduce the constant setup code a little, depending on your code.

**Comment by mingwandroid** [comment]
Looking forward to trying this out.. when's the next release planned?

**Comment by scoder** [comment]
You can try it right away with the latest master, just grab the zip download from github. We're close to the release, so any feedback is reassuring.

**Comment by mingwandroid** [comment]
> .pyc | 9_885_825

I wonder if we shouldn't package dummy, empty .pyc files and compile them en-masse at install time, or, for Python >= 3.7.1, let the interpreter do it lazily and automatically?

I guess this is pretty similar to the `noarch: python` stuff (which needs some optimizing, it invokes python for each `.pyc` that is compiled. This takes ages on Windows.

**Comment by scoder** [comment]
I'll close this ticket. Some work was done in Cython to reduce the size of both the generated C code and the generated shared library. Additionally, it was found that a major reason for the large extension module size if really the embedded debug information, which each project can control on its own (especially when building binary wheels). The effect of lowering the debug settings of the C compiler is much larger than that of reducing the output code size.

**Comment by mrocklin** [comment]
Thank you for tracking this and spending time on the issue @scoder 

I appreciate it
