### ISSUE TITLE
Implementation of next() looks inefficient

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2116]
This is the C code that Cython uses to implement the builtin `next()`:
```C
static CYTHON_INLINE PyObject *__Pyx_PyIter_Next2(PyObject* iterator, PyObject* defval) {
    PyObject* next;
    // we always do a quick slot check because always PyIter_Check() is so wasteful
    iternextfunc iternext = Py_TYPE(iterator)->tp_iternext;
    if (likely(iternext)) {
#if CYTHON_USE_TYPE_SLOTS
        next = iternext(iterator);
        if (likely(next))
            return next;
        #if PY_VERSION_HEX >= 0x02070000
        if (unlikely(iternext == &_PyObject_NextNotImplemented))
            return NULL;
        #endif
#else
        // note: PyIter_Next() crashes if the slot is NULL in CPython
        next = PyIter_Next(iterator);
        if (likely(next))
            return next;
#endif
    } else if (CYTHON_USE_TYPE_SLOTS || !PyIter_Check(iterator)) {
        __Pyx_PyIter_Next_ErrorNoIterator(iterator);
        return NULL;
    }
    return __Pyx_PyIter_Next2Default(defval);
}

static PyObject *__Pyx_PyIter_Next2Default(PyObject* defval) {
    PyObject* exc_type;
    __Pyx_PyThreadState_declare
    __Pyx_PyThreadState_assign
    exc_type = __Pyx_PyErr_Occurred();
    if (unlikely(exc_type)) {
        if (unlikely(!__Pyx_PyErr_GivenExceptionMatches(exc_type, PyExc_StopIteration)))
            return NULL;
        if (defval) {
            __Pyx_PyErr_Clear();
            Py_INCREF(defval);
        }
        return defval;
    }
    if (defval) {
        Py_INCREF(defval);
        return defval;
    }
    __Pyx_PyErr_SetNone(PyExc_StopIteration);
    return NULL;
}
```

1. The logic if `CYTHON_USE_TYPE_SLOTS` is false looks wrong: it should not use `tp_iternext`. Instead, it should first check `PyIter_Check` and then call `PyIter_Next`.

2. The function `__Pyx_PyIter_Next2Default` is called only from one place, so why not fold the implementation inside `__Pyx_PyIter_Next2`?

3. `__Pyx_PyIter_Next2Default` checks `__Pyx_PyErr_Occurred()` but it seems to me that this is always true.

4. If `defval is NULL`, then there is no need to check whether the exception is `StopIteration`: it should immediately `return NULL`.

**Comment by scoder** [comment]
1) I was trying to be smart there and assumed that `CYTHON_USE_TYPE_SLOTS` would only be disabled on platforms that potentially do not set `tp_iternext`. Since users can also `-D`define it themselves, that might not be a safe assumption. Definitely the kind of code that would have deserved a couple of comments...

2) I split both to limit the scope of the `CYTHON_INLINE` request. The second function is a non-critical fallback, and I want the C compiler to understand the difference.

3) `tp_iternext` is allowed to return `NULL` without setting an exception when the iteration terminates.

4) Sounds good.
