### ISSUE TITLE
Strange float behaviour

### ISSUE THREAD

**Issue by inferrna** [cython/cython#2189]
The code
```cython
from time import time

def show_the_trick():
    z = 0
    cdef float x = time()
    y = time()
    z = x
    print("y = {}, z = {}".format(y, z))
```
gives very strange result:
```sh
>>> show_the_trick()
y = 1522347701.6019838, z = 1522347648.0
>>> show_the_trick()
y = 1522347702.2980115, z = 1522347648.0
>>> show_the_trick()
y = 1522347702.9860392, z = 1522347648.0
>>> show_the_trick()
y = 1522347703.6420138, z = 1522347648.0
>>> show_the_trick()
y = 1522347704.2820802, z = 1522347648.0
>>> show_the_trick()
y = 1522347705.6421106, z = 1522347648.0
>>> show_the_trick()
y = 1522347753.8016214, z = 1522347776.0
>>> 
```
so, if assignment from cython variable to python variable is incorrect, it would be nice to say it at Cythonizing stage. Versions tested were 
cython - 0.26.1 (can't find a deb for 0.28.xx and too lazy to compile)
python - 3.5 and 3.6 versions

**Comment by robertwb** [comment]
The issue here is that the line `cdef float x = time()` explicitly assigns the result of time() to a lower-precision C type `float`. For most applications, there's little if any reason to uses single-precision floats these days, especially for something like timestamps (which only allow for multi-minute granularity). Better to just use `double`s everywhere.
