### ISSUE TITLE
Implement reversed C++ iteration

### ISSUE THREAD

**Issue by scoder** [cython/cython#2225]
Normal C++ iteration using the `.begin/.end` methods is supported in for-loops. Reversed iteration witn `.rbegin/.rend` should be supported using the `reversed()` function.

- implement transformation in `Optimize.py`, `IterationTransform._transform_reversed_iteration()`, maybe setting a flag attribute that changes the direction of the `IterationNode`.
- Generate the correct C++ code from `IteratorNode` in `ExprNodes.py`.
- Add tests in `tests/run/cpp_iterators.pyx`.

**Comment by Yoshi325** [comment]
I'm willing to attempt to implement this Issue. However, I'm still pretty new to cython development. Could you give me a few more thoughts, pointers, or examples that would help me understand how to go about it? I'd especially be interested in what the tests to go into `tests/run/cpp_iterators.cpp` would look like since I don't think the file currently exists.

**Comment by scoder** [comment]
Sorry, wrong file name. I updated the description a little, but would suggest that you work on your other pull request first.

**Comment by Yoshi325** [comment]
I absolutely will work on the other one first. Just trying to gather a few opportunities. I have a vested interest in better understanding and contributing to cython's development.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/d329339ba05ac76e0a83f539f173996e80cc89e1
