### ISSUE TITLE
RecursionError: maximum recursion depth exceeded when compiling an extremely complicated but valid Python file

### ISSUE THREAD

**Issue by jcrudy** [cython/cython#2247]
This use case is probably unusual.  I have a machine-generated Python file which contains some complicated mathematical calculations.  By complicated, I mean that they are very long.  This file can be compiled and run by Python, but I decided to try compiling it with Cython.  When I attempt to compile it, I get the `RecursionError` below.  The file contains some very long expressions, which I'm guessing is the issue.  I'm able to avoid the error by raising the recursion limit, but my system then runs out of memory.  The stack trace is below.  I'm using Cython version 0.26 on Python 3.6.2 on a macbook air with 8GB of memory.

```
aph_models/hepatitis_c_one_year.pyx:12017:8730: Compiler crash in NormalizeTree

ModuleNode.body = StatListNode(hepatitis_c_one_year.pyx:2:0)
StatListNode.stats[4005] = DefNode(hepatitis_c_one_year.pyx:8016:0,
    modifiers = [...]/0,
    name = '_f4000',
    num_required_args = 186,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
DefNode.body = StatListNode(hepatitis_c_one_year.pyx:8017:4)
StatListNode.stats[4000] = ReturnStatNode(hepatitis_c_one_year.pyx:12017:4,
    is_terminator = True)
ReturnStatNode.value = AddNode(hepatitis_c_one_year.pyx:12017:52414,
    infix = True,
    operator = '+',
    result_is_used = True,
    use_managed_ref = True)
AddNode.operand1 = AddNode(hepatitis_c_one_year.pyx:12017:52277,
    infix = True,
    operator = '+',
    result_is_used = True,
    use_managed_ref = True)

[... lots of AddNode's here ...]

AddNode.operand1 = AddNode(hepatitis_c_one_year.pyx:12017:8858,
    infix = True,
    operator = '+',
    result_is_used = True,
    use_managed_ref = True)
AddNode.operand1 = AddNode(hepatitis_c_one_year.pyx:12017:8730,
    infix = True,
    operator = '+',
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    ext_modules = cythonize(ext_modules, compiler_directives=directives) if cythonize_switch else ext_modules,
  File "/Users/jason/anaconda/envs/aphsuperriskcalculatordev/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1016, in cythonize
    cythonize_one(*args)
  File "/Users/jason/anaconda/envs/aphsuperriskcalculatordev/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1138, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: aph_models/hepatitis_c_one_year.pyx
```

**Comment by scoder** [comment]
Yeah, I've seen this kind of problem with generated Python/Cython code before. Basically, syntax trees of that size will always run into some kind of resource limit, either in Cython or the C compiler. There were already some improvements in the past that reduced the Python stack usage (and it's always best to try the latest release), but compilers are inherently recursive, and there will always be limits at that front.

You didn't say what you are doing this for (presumably to gain speedups), but be aware that even if the translation to C succeeds, and the C compiler manages to compile the generated C code, you will probably end up with a huge shared library. Can't say if that would be usable for you.

Since you are generating the code anyway, you can certainly try to simplify the expressions, e.g. by splitting them in multiple assignments, or adding parentheses around subexpressions to reduce their tree depth (e.g. "a+b+c+d+e+f+g" -> "(a+b+c)+(d+e+f+g)" reduces the recursion depth of the expression tree by about half). Also, if you type your variables with (numeric) C types instead of Python object types (assuming that's possible), that will reduce the overall size of the C file and the shared library considerably, since it replaces complex Python operations with simple C operations.

Finally, I'll close this ticket as I do not consider it a bug that we can really do something about. Please ask on the cython-users mailing list if you want further help with this, we'll be happy to help.

**Comment by scoder** [comment]
That being said, I actually wonder if switching to async dispatch methods for the tree traversal could help here. Instead of calling the `handler_method` directly in `TreeVisitor._visit()` in `Visitor.py`, and thus recursing down the tree, the handler could be `await`-ed back to an iterative traversal engine and called from there.

I'll leave the ticket closed anyway, because this is a lot of code modification since all handler methods would have to become `async` (or at least generators), and there are hundreds of them, and b) since async/await is only supported in Py3.5+, we'd actually have to use generators instead or Cython would no longer be runnable from sources in Py2.x and Py<3.5 (only in compiled binary form). That sounds like a lot of hassle to go through, and it almost certainly will slow down the processing as well...
