### ISSUE TITLE
Pyximport does not use cythonize() internally.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [cython/cython#2304]
From @scoder 's comment in #2298 about pyximport internals: 

> Right, and that is totally a bug. It should really use cythonize(). Definitely something to list under "limitations" below.

Since pyximport does not use Cythonize internally, it prevents the use of compiler directives at the top of the `.py` or `.pyx` files. Also, using Cythonize could potentially remove quite a bit of code (potentially, all the code in `cython/pyximport/pyxbuild.py` could be removed).

**Comment by navytux** [comment]
Indeed `pyximport` does not currently use `cythonize` internally as it is currently building on `old_build_ext`: https://github.com/cython/cython/blob/3de7a4b8fb7ce045222e13ca02541f6a70e89c2e/pyximport/pyxbuild.py#L13

Besides preventing to use compiler directives at the top of `.py` or `.pyx`, it also makes `pyximport` to miss recompiling when build dependency change (see e.g. https://github.com/cython/cython/issues/3121).

So if we switch `pyximport` to use `new_build_ext`, or to use just `from Cython.Distutils import build_ext` and switch that build_ext to new implementation that is based on `cythonize` (#3541), then this issue will be automatically fixed.

**Comment by scoder** [comment]
PR very welcome that does what @navytux and @gabrieldemarmiesse have described above.

**Comment by mattip** [comment]
Setuptools has [distutils extensions](https://setuptools.readthedocs.io/en/latest/userguide/extension.html#creating-distutils-extensions) to allow extending the universe of commands and options available when building an `Extension`.

For instance, CFFI [adds a setuptools entry point `distutils.setup_keywords`](https://foss.heptapod.net/pypy/cffi/-/blob/branch/default/setup.py#L219) function  `cffi_modules` so you can do this in `setup.py`:
```
from setuptools import setup

setup(
    name="example",
    version="0.1",
    py_modules=["readdir"],
    setup_requires=["cffi>=1.0.dev0"],
    cffi_modules=["readdir_build.py:ffi"],
    install_requires=["cffi>=1.0.dev0"],
    zip_safe=False,
)
```

The function `cffi_modules`'s signature is 
```
def cffi_modules(dist, attr, value):
    assert attr == 'cffi_modules'
```
where `dist` is a `Distribution`, value is `["readdir_build.py:ffi"]`, and the call adds a new Extension to `dist`. 

Maybe cython could add something similar:  add a `distutils.setup_keywords` function something like `cython_modules=["myfile1.pyx", "myfile2.pxd:myfile2.pyx"]`. The `cython_module` function would add a `Extension` to `dist` for each value. This would encapsulate the call to `cythonize` as a separate step, so cython would not override `build_ext` but could pass it compilation flags.

Another option would be to add a `distutils.command` for cythonize, but I am not sure how to tie that in so that `setup.py build_ext` would notice it needs to convert `pyx` files to `c` via `cythonize`.

I willing to put some work into this.
