### ISSUE TITLE
Behavior in windows 10

### ISSUE THREAD

**Issue by kuribo678** [cython/cython#2318]
I used an authorized installer but the operation of the pip command fails

Environment is windows 10

```
c:\users\user\appdata\local\programs\python\python36\include\pyconfig.h(59): fatal error C1083: include ファイルを開けません。'io.h':No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

I can't download scrapy'library

first challenge is downloaded python3.7
python3.7 can't use pip's command
I got error message libxml2'libraly

I tryed same Environment 
second challenge is downloaded python3.6

Problem seems to be pyconfig.h
Problem's code seems to be io.h

**Comment by scoder** [comment]
Definitely use Py3.6 instead of 3.7. Py3.7 is not finally released yet, and therefore lacks binary packages of third party modules.

Apart from that, this looks like a general support request for installing Python packages. It's not related to any bugs in Cython, nor is it even specific to Cython. Please ask on the Python mailing list instead.
