### ISSUE TITLE
Overflow error not raised on variable assignment

### ISSUE THREAD

**Issue by philipCrunchboards** [cython/cython#2410]
Assignment of a large Python integer object to a Cython int variable appears to cause an overflow without raising an error.
This happens with either value of the `overflowcheck` directive.

If this is intended behaviour, could someone point me towards the documentation please?

```
def int_test():
    cdef object object_var = 1000000000000000000  # i.e. 10 ** 18
    cdef int int_var = 1000000000000000000  # i.e. 10 ** 18

    print(object_var)  #  Correct: 1000000000000000000
    print(int_var)  #  Incorrect: -1486618624

int_test()
```

Cython: 0.28.3
Python: 3.6.5
OS: MacOS Seirra 10.12.6 (16G29)

**Comment by scoder** [comment]
I understand that you are giving an example here, but is there actual real-world code where you run into this problem?

**Comment by philipCrunchboards** [comment]
@scoder Yeah, when you call the builtin Python `hash()`, you get back an int with a greater range than the Cython int type, so you get an overflow which causes hash collision.

**Comment by scoder** [comment]
Well, Cython can actually infer the type of such a variable based on the assignment (unless you do unsafe operations with it later on, in which case it will play the safer "object" card). So, you may get away with not typing it at all.

In any case, the correct C integer type for the result of a Python hash function is `Py_hash_t`, not `int`.

Basically, your code above is explicitly asking for trouble. Cython could issue a warning in this case about a (potential) implicit value range reduction, but since it cannot know the final platform specific sizes when generating the (portable) C code, such a warning would be by best effort and would result in false positives. Meaning, it could easily end up being more annoying than helpful, especially for existing code bases. Your C compiler should be able to generate such a warning for you, though, and correctly so.

**Comment by philipCrunchboards** [comment]
This works correctly when Cython infers the type, so I'll stick with that.
I see what you mean about warnings. I'm not sure why my C compiler isn't generating a warning when there's an overflow converting from `Py_hash_t` to `int`.
It looks like there's nothing that can realistically be done about this in Cython, so I'm closing this issue.

Thanks for your help with this @scoder.
