### ISSUE TITLE
Change directive default to `binding=True`

### ISSUE THREAD

**Issue by scoder** [cython/cython#2564]
This is a breaking change. It replaces the generation of Python `PyCFunction`instanced for compiled Python functions to use `CyFunction`.

**Comment by mhham** [comment]
Could you please explain how this will impact future cython code (higher performance ? more compatibilty/flexibility ? ...), I have trouble understanding the role of this compiler directive :/

Thanks !

**Comment by TeamSpen210** [comment]
The binding directive makes Cython functions/methods use a custom type, instead of Python’s normal C-function type. So `type(my_cython_func) is not type(len)` (though `inspect` works correctly), but the custom type allows them to behave more like pure-Python functions instead of inheriting the builtins’ behaviour. 

The most obvious change (why it’s called “binding”) is that builtins functions can’t be bound - if you do `myClass.len = len`, calling that on an instance won’t pass self as the first argument. It also allows emulating function attributes, so for example `__defaults__` is set to the right thing - though you can’t write to it.
