### ISSUE TITLE
Can Cython use Python type hints?

### ISSUE THREAD

**Issue by Star-Hub** [cython/cython#2587]
Can Cython use Python type hints?

**Comment by scoder** [comment]
Yes. Did you search anywhere for an answer before opening a bug ticket? I don't see how this is a bug.

**Comment by anthrotype** [comment]
I only see it mentioned in the changelog. It would be worth mentioning this more prominently in the Cython documentation as well.
I recently listened to a popular python podcast where they were comparing cython to another similar project (https://github.com/JukkaL/mypyc) and the speaker wrongly assumed that cython did not support PEP-484 and PEP-526 type annotations.

**Comment by scoder** [comment]
We could probably advertise it more prominently, but it's at least documented in the "expected" place:
http://docs.cython.org/en/latest/src/tutorial/pure.html#static-typing

**Comment by anthrotype** [comment]
oh, thanks for the link, I missed that.

**Comment by anentropic** [comment]
Here would also be a good place: http://docs.cython.org/en/latest/src/quickstart/cythonize.html

The title of that page is "Faster code via static typing" but it only talks about types in the context of Cython code AFAICT, not Python-with-type-annotations.

**Comment by da-woods** [comment]
@anentropic Improvements to the documentation are obviously always welcome, and you're probably right that it's a bit sparse in type hints. I'd think it'd be better in https://cython.readthedocs.io/en/latest/src/tutorial/pure.html.

The "quickstart" guide should be quick rather than comprehensive, and it's probably sensible for it to focus on Cython's "main" syntax.

**Comment by dave-doty** [comment]
@scoder @da-woods 

I echo the confusion of @anentropic and @anthrotype.

On this page: http://docs.cython.org/en/latest/src/tutorial/pure.html#static-typing, I don't see any examples using Python type hints that use the syntax of [PEP 484](https://www.python.org/dev/peps/pep-0484/) and [PEP 526](https://www.python.org/dev/peps/pep-0526/). Instead, that page explains how to take Python code that is not annotated with type hints in the syntax of [PEP 484](https://www.python.org/dev/peps/pep-0484/) and [PEP 526](https://www.python.org/dev/peps/pep-0526/), and add a `.pxd` file supplying types in Cython syntax.

But all of the pure Python code on that page is unannotated with Python types, instead looking like this:

```python
def myfunction(x, y=2):
    a = x - y
    return a + x * y

def _helper(a):
    return a + 1

class A:
    def __init__(self, b=0):
        self.a = 3
        self.b = b

    def foo(self, x):
        print(x + _helper(1.0))
```

whereas type hints using [PEP 484](https://www.python.org/dev/peps/pep-0484/) and [PEP 526](https://www.python.org/dev/peps/pep-0526/) would look like this:

```python
def myfunction(x: int, y: int = 2) -> int:
    a: int = x - y
    return a + x * y

def _helper(a: float) -> float:
    return a + 1

class A:
    def __init__(self, b: int = 0):
        self.a = 3
        self.b = b

    def foo(self, x):
        print(x + _helper(1.0))
```

Is it possible to use Python type hints, using the standard Python type hints syntax, without the need to manually generate a separate `.pxd` file with Cython-syntax type hints? If so, is there a page that describes how to do that?

**Comment by da-woods** [comment]
@dave-doty There is a small amount of documentation for type hints - the section starting

> Since version 0.27, Cython also supports the variable annotations defined in PEP 526.

(I see you've spotted this yourself too)

Obviously it could be better documented and improvements are always welcome. As you note `int` is the main pain point. The other "limitation" is that things like `Dict[int, str]` (containers with fixed types in) are useless to Cython and that's unlikely to change.

**Comment by da-woods** [comment]
@dave-doty (and other people that complained about this...) - I've [tried to improve the documentation a little](https://github.com/cython/cython/pull/3799). It doesn't add a lot of extra information but it does put annotation typing in its own section, which should hopefully make it easier to find for people who are searching for it. Obviously further improvements from others are still welcome.

**Comment by Timtam** [comment]
Probably a bit late to the discussion, but i'm trying to work out a way to properly work with typings and Cython as well. I've got a rather large library that is written in Cython entirely and should do the following:

* provide Python 3 typing annotations, so that e.g. mypy can ensure type compatibility when used
* allow Cython to properly know the types of specific function arguments to optimize speed etc
* don't write doubled code if possible
* type-check function arguments for cpdef methods at runtime in cases where mypy isn't used 

To be honest, i'm not entirely sure where to start:

* can typings and Cython type annotations be mixed / can one of both be dropped so that I don't need to double things? e.g. can code like this work in a pxd/pyx:

        cdef class foo:

          cpdef bar(baz: int) -> None

* Will it understand all the stuff imported from typings? I guess Optional theoretically isn't needed since Cython accepts None as arguments too by default.
* Will mypy automatically be able to derive typings when used, or do I still need to create pyi files? Or would there be a way to automatically generate pyi files from my Cython modules somehow?
* Can I add type-checking at runtime somehow? I thought about using a module like [typecheck-decorator](https://pypi.org/project/typecheck-decorator/)

Just my thought processes though. I didn't find a go-to solution for me yet. For now, i'm using Cython type annotations within my code and write dedicated pyi files as a workaround, but it feels rather error-prone since i'm unable to test my pyi files for now and type-checks need to be done manually within every method, and i've got alot of them.
Deffinitely not a Cython issue per-se, but probably an interesting topic to think and discuss about.

**Comment by scoder** [comment]
See the `Shadow.py` module, which implements Cython types for Python (it's what you get when you `import cython`).
https://github.com/cython/cython/blob/master/Cython/Shadow.py
https://github.com/cython/cython/blob/master/Cython/Shadow.pyi

The documentation is [currently being rewritten](https://github.com/cython/cython/issues/4187) to make Python style typing more visible.

Otherwise, type annotations behave pretty much like they do in Python (minus a few bugs). See PEP-484/526 on that.

**Comment by da-woods** [comment]
> * Will it understand all the stuff imported from typings? I guess Optional theoretically isn't needed since Cython accepts None as arguments too by default.

Not yet, but https://github.com/cython/cython/pull/3910 is a proposed changed to implement some the `typing` module.

> * Will mypy automatically be able to derive typings when used, or do I still need to create pyi files? Or would there be a way to automatically generate pyi files from my Cython modules somehow?

Not at the moment. https://github.com/cython/cython/pull/3818 is a PR that proposes to do this (but I think is at quite an early stage)

> * Can I add type-checking at runtime somehow?

Cython largely does do runtime type-checking when you specify the types of arguments.

**Comment by moi90** [comment]
https://github.com/cython/cython/pull/3818 was abandoned, but the work was continued in https://github.com/Vizonex/CyStub .

**Comment by Code4SAFrankie** [comment]
After reading all this I'm still left wondering whether just Python type hints will give me a large speedup with Cython, which to my mind would be a fantastic benefit to Python. Stating the answer in simple language somewhere in the introductory documentation would surely be of huge benefit. That is can I use `a: int` instead of `cdef int`, and both would have the same speedup in Cython. If not will this happen in the future?

**Comment by da-woods** [comment]
> That is can I use `a: int` instead of `cdef int`, and both would have the same speedup in Cython. If not will this happen in the future?

There's a relatively comprehensive table in the documentation: https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#reference-table

However - please ask further support questions on the cython-user's mailing list rather than on closed issues though. The conversation here isn't really intended to be an authoritative source of anything.

**Comment by sinloss** [comment]
> Thanks for bringing this up, BTW, and sorry for sounding a bit harsh initially. It does seem like a common misconception to think that "you have to change your code in order to use Cython" and "Cython can't compile Python code". Both of these hydra myths are really hard to cut off, and can easily prevent people from letting Cython solve their problems.

Exactly what I've experienced! I've been using Nuitka for the last 6 months only to realize that Cython can perfectly compile pure python code!
