### ISSUE TITLE
`__defaults__` behavior different under cpython/cython

### ISSUE THREAD

**Issue by mambocab** [cython/cython#2650]
We use a (admittedly hacky) behavior to change default kwargs in some of our tests:

```
def set_default_beta_flag_true():
    defaults = list(Cluster.__init__.__defaults__)
    defaults = (defaults[:28] + [True] + defaults[29:])
    try:
        Cluster.__init__.__defaults__ = tuple(defaults)
    except:
        Cluster.__init__.__func__.__defaults__ = tuple(defaults)
```

(see [our `tests/integration/__init__.py`](https://github.com/datastax/python-driver/blob/5c8fac636af99cd6e5a93f04eac4a68aeb304bca/tests/integration/__init__.py#L165-L171) for context)

Subsequent calls to `Cluster.__init__` respect the new defaults when running under cpython 2.7.12, but not when running after cython compilation under `Cython==0.28.5`.

I've written a [minimal test case](https://gist.github.com/mambocab/273a5916c2481e82e07acb77535fa263#file-defaults_demo-py) and a [script that demonstrates the behavior in this case](https://gist.github.com/mambocab/273a5916c2481e82e07acb77535fa263#file-script-sh). I've captured [my local output](https://gist.github.com/mambocab/273a5916c2481e82e07acb77535fa263#file-script-out) in that gist at well. Note the difference in the second `ClassWithDefaults` instance.

Happy to give any further information if requested.

**Comment by TeamSpen210** [comment]
It's not really hacky, `__defaults__` is a writable attribute documented to appear on functions, it's entirely reasonable to set it like that. However it's probably a bit difficult for Cython to implement the ability to change that.

**Comment by scoder** [comment]
Did you try it with the `binding=True` directive?

**Comment by mambocab** [comment]
You're talking about the `binding` directive [documented here](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives)? I have not.

Should I expect it to make a difference for a method (i.e., my `Cluster.__init__`)? The documentation specifically says it affects the behavior of "free methods".

**Comment by TeamSpen210** [comment]
Binding makes Cython functions use a custom type, instead of the normal Python type for builtin methods/functions. That makes them behave identically to normal functions for bound/unbound method behavior, and also adds a `__defaults__` attribute. However checking the generated C code shows it's not actually used when actually calling the method. The reason is that Cython adds the values that are set directly into the argument unpacking code it generates. It shouldn't be difficult to make object arguments do a fast lookup on the tuple, but for C-converted arguments it'll need to store those elsewhere. Perhaps add a setter which converts the C args whenever `__defaults__` is set?

**Comment by da-woods** [comment]
Looking at this: (with `binding=True`) Cython has `__defaults__` and `__kwdefaults__` arguments for introspection only, but doesn't actually use any changes to them. Realistically that's unlikely to change since it's likely to be quite hard to convert them back into the C-converted arguments that it actually uses.

That suggests to me that they should be read-only attributes of `CyFunction`, rather than the current version where they're read-write but ignored.

**Comment by scoder** [comment]
> That suggests to me that they should be read-only attributes of `CyFunction`, rather than the current version where they're read-write but ignored.

It doesn't really make a difference since both values are mutable even if you prevent assignments to the attributes. I'd say the line of reasoning is that more code "doesn't fail" when they can be assigned without effect to than if we block off assignments.

**Comment by da-woods** [comment]
> > That suggests to me that they should be read-only attributes of `CyFunction`, rather than the current version where they're read-write but ignored.
> 
> It doesn't really make a difference since both values are mutable even if you prevent assignments to the attributes. I'd say the line of reasoning is that more code "doesn't fail" when they can be assigned without effect to than if we block off assignments.

Fair point. I might try to add a warning at runtime when they're re-assigned - it obviously doesn't cover all changes but it might save some confusion (while not breaking anything)
