### ISSUE TITLE
Cython bug on threading?

### ISSUE THREAD

**Issue by Patton-L** [cython/cython#2698]
cython compiled .py file:
cython_test.py
```python
import threading,time

def thread_func():
    print("Running at {}".format(time.time()))
    print("Still Running at {}".format(time.time()))
    print("Still Running!")

def test():
    f = threading.Thread(target=thread_func)
    f.start()
    st = time.time()
    while time.time() - st < 5:
        pass
    print("main thread done")
```
This file is compiled with `cythonize("cython_test.py")`

Test file:
```python
import cython_test # Cython Compiled
cython_test.run()
```
### Normal behavior with python:
print "_Running at xxx_" and "_Still Running at xxx_" in a sequence, with no interval more than 5s and before main thread prints : "_main thread done_"
```
Running at X
Still Running at X
Still Running!
main thread done
```

### Cython compiled py file's behavior:
 the first "Running at" prints right away, but the second "Still Running at " print after "_main thread done_ " displayed.
```
Running at X
main thread done
Still Running at X
Still Running!
```

Tested on Python 3.7.1; Cython 0.29 ; Ubuntu 16.04

======

Is that saying cython never switch back to thread_func once it context switched to main thread?

**Comment by scoder** [comment]
CPython frees the GIL every couple of byte code executions and can thus switch threads between any two byte codes. Cython does not have byte code. I/O operations might still free the GIL, however, but in any case, that's outside of Cython's control.

Your example code implements a busy loop in the main thread that does not allow other threads to run, since it does not free the GIL. If you want to allow other threads to run, either free the GIL when you don't need it, or release and re-acquire it every so-many operations to allow for a thread-switch. In any case, as long as you require the GIL in more than one thread, you will not get any parallelism.
