### ISSUE TITLE
Type Annotation Performance

### ISSUE THREAD

**Issue by acbraith** [cython/cython#2724]
```python
# fib.pyx
def fibonacci_cy(n):
    a = 0
    b = 1
    for _ in range(1, n):
        a, b = b, a + b
    return b
def fibonacci_cy_hint(n:int) -> int:
    a:int = 0
    b:int = 1
    for _ in range(1, n):
        a, b = b, a + b
    return b
def fibonacci_cy_static(n):
    #cdef int _
    cdef int a=0
    cdef int b=0
    for _ in range(1, n):
        a, b = b, a + b
    return b

# # # # #

# test.py 

def fibonacci_py(n):
    a, b = 0, 1
    for _ in range(1, n):
        a, b = b, a + b
    return b

# first need to run 
# py -3 setup.py build_ext --inplace

if __name__ == '__main__':
    import timeit
    import fib

    print("pure",timeit.timeit(lambda: fibonacci_py(70), number=10000))
    print("cy",timeit.timeit(lambda: fib.fibonacci_cy(70), number=10000))
    print("cy hint",timeit.timeit(lambda: fib.fibonacci_cy_hint(70), number=10000))
    print("cy static",timeit.timeit(lambda: fib.fibonacci_cy_static(70), number=10000))
```

I find that `fibonacci_cy_hint` is actually a bit slower than `fibonacci_cy`, and compiles to roughly the same code. 
I was hoping for `fibonacci_cy_hint` to be closer to `fibonacci_cy_static` (http://docs.cython.org/en/latest/src/tutorial/pure.html#static-typing)
Is this expected?

**Comment by scoder** [comment]
fib(70) > 2**32, so `int` is not the right data type here. Also, I'd be surprised if fib(70) took any time at all to calculate in C, so what you're measuring is probably not what you want to measure. Besides that, my guess is that the C compiler simply deletes the body of the "static" function, because it can calculate the final result (0) at compile time. ;)

I'd suggest to look for a more interesting example.
