### ISSUE TITLE
_getframe bug: ValueError: call stack is not deep enough

### ISSUE THREAD

**Issue by mingwugmail** [cython/cython#2735]
```
$ cat getframe_bug.py 
# python -m nuitka --follow-imports getframe_bug.py
import sys

def _S(expr):
  frame = sys._getframe(1)
  result = '%s = %s ' % (expr, repr(eval(expr, frame.f_globals, frame.f_locals)))
  return result

def main():
  a = 10
  print(_S('a+10'))

if __name__ == '__main__':
  main()
```

```
$ python getframe_bug.py
a+10 = 20 

$ cython getframe_bug.py --embed
/home/.../miniconda3/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/.../test/python/getframe_bug.py
  tree = Parsing.p_module(s, pxd, full_module_name)

$ gcc getframe_bug.c `python-config --includes --ldflags --libs` -fno-lto
$ ./a.out 
Traceback (most recent call last):
  File "getframe_bug.py", line 14, in init getframe_bug
    main()
  File "getframe_bug.py", line 11, in getframe_bug.main
    print(_S('a+10'))
  File "getframe_bug.py", line 5, in getframe_bug._S
    frame = sys._getframe(1)
ValueError: call stack is not deep enough



$ python --version
Python 2.7.12
x86_64 GNU/Linux
```

**Comment by jiayoustone** [comment]
any update?  Will this bug be solved?

**Comment by da-woods** [comment]
I think Cython makes the deliberate decision not to generate stack frames for its functions, so this behaviour is expected. Generating them would add significant work to a function call (especially if you want a useful level of detail)

**Comment by scoder** [comment]
Note that this might work (better) if you enable profiling support for your code.

I don't think it's something we'll change any time soon. It just has too many downsides compared to the single advantage of allowing highly dynamic code – which is best implemented in Python and not compiled. Just imagine the tremendous overhead that frame creation would add to an otherwise inlined C function like
```cython
cdef (int, int) divmod(int a, int b):
    return a // b, a % b
```

I'm happy to hear about real use cases for this, but will leave the ticket closed until someone comes up with a convincing argument for adding frames to functions.

**Comment by Delgan** [comment]
@scoder Hi. Accessing the frames is mainly required for logging utilities.

It can cause `ValueError` if misused from a cythonized function, and most importantly, prevents to display contextual information.

It is perfectly reasonable, though, that Cython decides to discard frames for obvious optimization reasons. Just sharing a legitimate use case in case a workaround can exist. :+1:
