### ISSUE TITLE
Python 2: __qualname__ is wrong (when subclassed or on metaclass)

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2772]
When defining a Python `class` using Cython, the `__qualname__` attribute is always set, even on Python 2. When this Cython-defined class is either subclassed or used as metaclass in pure Python code, that new class gets the wrong `__qualname__` from Cython.

Examples:
```
# In Cython
class X(type): pass
```
```
# In Python
>>> class Y(X): pass
>>> Y.__qualname__
X
```
```
# In Python
>>> class Y(object): __metaclass__ = X
>>> Y.__qualname__
X
```
As you can see, we get a wrong `__qualname__` in both cases. This confuses for example tools like Sphinx, where it produces incorrect output.

Since `__qualname__` is useless on Python 2, I suggest to simply not set `__qualname__` on Python 2. For Sphinx, not having a `__qualname__` is fine, since it will simply use `__name__` which is correct.

**Comment by scoder** [comment]
Personally, I consider `__qualname__` a useful debugging feature all by itself, so I'd prefer keeping it if/where possible. But the problem here is that Python doesn't override it for its own subtypes, so I understand that it gets in the way for classes. Functions should be ok (although, see #2562).

Should we remove it only from classes in Py2?

**Comment by jdemeyer** [comment]
> Should we remove it only from classes in Py2?

I don't really have an opinion for functions. Maybe it's fine to keep `__qualname__`.
