### ISSUE TITLE
Implement PEP-487: customisation of class creation

### ISSUE THREAD

**Issue by fduxiao** [cython/cython#2781]
```python3
class ABC:
    def __init_subclass__(cls):
        print(cls)


class SubClass(ABC):
    pass

```
If you run this with python directly, it gives:
```
<class '__main__.SubClass'>
```
But after I compile it with cython, it gives:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-a0954f22e2a4> in <module>
----> 1 import test

test.pyx in init test()

TypeError: __init_subclass__() takes exactly one argument (0 given)
```
How to solve it?

**Comment by scoder** [comment]
The relevant bits of [PEP-487](https://www.python.org/dev/peps/pep-0487/) need to get implemented. Specifically, `__init_subclass__()` is an implicit class method and must be treated as such, and class creation should call the `__init_subclass__()` method in older Python versions (before 3.6).

I assume you were using Py3.6 or later for your tests, right?

**Comment by scoder** [comment]
PR welcome, seems relatively easy. If you want to give it a try, see the [HackerGuide](https://github.com/cython/cython/wiki/HackerGuide) for hints how to get started, and ask on the cython-dev mailing list whenever you feel like needing help.

**Comment by rayzchen** [comment]
Python 3.9 error still isn't fixed

**Comment by rayzchen** [comment]
Test:

```python
# subclass.py
class A:
    def __init_subclass__(cls):
        print(cls)
        return cls

class B(A):
    pass
```

Run:

`cythonize -3 -q -i subclass.py`
```
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:22:44) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subclass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "subclass.py", line 6, in init subclass
    class B(A):
TypeError: __init_subclass__() takes exactly one argument (0 given)
```

```
$ ls
__pycache__  sub.c  sub.cp39-win32.def  sub.cp39-win32.pyd  sub.o  sub.py
```

**Comment by da-woods** [comment]
> Python 3.9 error still isn't fixed

No. Your example works fine on the current Cython 3 alpha version. You're probably using an older version where this feature isn't supported.

**Comment by rayzchen** [comment]
I use AppVeyor for building wheels and it uses the latest Cython version (using `pip install cython`). Is the fix in a release that I need to specify manually?

**Comment by da-woods** [comment]
It's in the 3.0 alpha release (since 3.0a2 I think). It isn't (and won't be) in the 0.29.x branch. Since the 3.0 branch is still an alpha branch you probably do need to specify it manually. The alpha branch is pretty usable at this stage and is where most new features are going, so it may be worth your while trying it.

**Comment by rayzchen** [comment]
How do I install it with pip?

**Comment by rayzchen** [comment]
What about just choosing the latest prerelease?

**Comment by rayzchen** [comment]
Never mind, `pip install --pre cython` works!

**Comment by rayzchen** [comment]
I don't know what is going on now, but the error is still there. Here is the build: https://ci.appveyor.com/project/rayzchen/pyunity/build/job/i011xbqufc0tj03o

Lines 39-533 are the main focus. Line 39 installs cython 3.0a8, line 57 creates the cython files (using `cythonize -3 -q file.py`) and the rest is just creating the bdist. However, when I install the wheel provided (tested on both python 3.9 win32 and win_amd64) and run an example, the error happens when subclassing from `pyunity.Behaviour`, which defines `__init_subclass__`.

**Comment by rayzchen** [comment]
I don't know what is going on now, but the error is still there. Here is the build: https://ci.appveyor.com/project/rayzchen/pyunity/build/job/i011xbqufc0tj03o

Lines 39-533 are the main focus. Line 39 installs cython 3.0a8, line 57 creates the cython files (using `cythonize -3 -q file.py`) and the rest is just creating the bdist. However, when I install the wheel provided (tested on both python 3.9 win32 and win_amd64) and run an example, the error happens when subclassing from `pyunity.Behaviour`, which defines `__init_subclass__`. But for some reason, it works randomly on another computer that I have open. I really am too confused right now.

**Comment by rayzchen** [comment]
If that was too confusing, here is the summary:

https://ci.appveyor.com/api/buildjobs/i011xbqufc0tj03o/artifacts/dist%2Fpyunity-0.7.0-cp39-cp39-win32.whl - win32 python 3.9 build
https://ci.appveyor.com/api/buildjobs/i011xbqufc0tj03o/artifacts/dist%2Fpyunity-0.7.0-cp39-cp39-win_amd64.whl - win_amd64 python 3.9 build

I have 3 computers: 2 win32 computers, 1 win_amd64 computer (this is python version)
Install correct wheels on each computer
All compiled using cython 3.0a8 (see above build)
2 computers fail on a line which is just `class Rotator(Behaviour):`
The error is `TypeError: __init_subclass__() takes exactly one argument (0 given)`
The `Behaviour` class defines `__init_subclass__` with two arguments, `self` and `cls`

python 3.9 win32 1                        python 3.9 win32 2                    python 3.9 win_amd64
             Fail                                                    Pass                                          Fail

There is no difference on the computers, I've even tested using a venv.

**Comment by rayzchen** [comment]
I don't really know how I fixed it but its fixed now...
