### ISSUE TITLE
`__cinit__` docstring is lost

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2793]
If I define a class with `__cinit__` but not `__init__`:
```python
cdef class C:
    def __cinit__(self):
        """Construct a C"""
```

the constructor docstring is not picked up by [autodoc](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) and similar tools. Therefore I have to define a dummy `__init__` method simply to attach the constructor's docstring to it.

It would be nice if the `__cinit__`'s docstring was reflected in `C.__init__.__doc__` (assuming `__init__` is left undefined).

**Comment by scoder** [comment]
Hmm. But there is not `__init__` in that case. Where should we stick the docstring?

**Comment by pitrou** [comment]
Ah! I would have thought that Cython always generates a `__init__`. Perhaps in the `__new__`? Though I'm not sure autodoc would pick it up correctly.

**Comment by scoder** [comment]
I think your best choice is to put the user facing docstring into the class, rather than `__cinit__`. I'd be surprised if documentation tools didn't pick it up from there. `__cinit__` is mostly meant for low-level initialisation, anything that needs to be done before calling up the `__init__` chain, which might execute arbitrary user code in subclasses (or not be executed at all). So whatever docstring `__cinit__` has might not even be meant to be seen by users.

Regarding `__init__` and `__new__`, Cython does the same as Python. If they are not defined, they are simply inherited from the parent, so there is no place to copy a docstring to.
```python
>>> class T(object): pass
>>> T.__new__
<built-in method __new__ of type object at 0x9d1260>
>>> T.__init__
<slot wrapper '__init__' of 'object' objects>
```
