### ISSUE TITLE
Cython differs from CPython: unexpected integer overflow 

### ISSUE THREAD

**Issue by mbuzdalov** [cython/cython#2866]
The following purely Python code produces different answers in CPython and Cython:

```
def countingsort(list_to_sort):
    help = [10 ** _ for _ in range(0, 30)]
    with open('output.txt', 'wt') as ttt:
        ttt.write(str(sum(help)))

def main():
    countingsort([1])

main()
```

CPython produces the expected answer, 111111111111111111111111111111. However Cython produces a different answer: 119304647 on Windows (where `long` is a 32-bit type) and 12861934301395841479 on Linux (with a 64-bit `long`).

The problem is supposedly in the list generator, where 10 is not promoted to a big integer before raising to a very large power.

Relevant software versions:
- Cython version 0.29.5
- Python 3.7.2
- gcc (GCC) 8.2.1 20181127

Note that with Python 2 this problem is not reproduced.

**Comment by scoder** [comment]
Thanks for the report. IIRC, `**` is already considered an unsafe integer operation that defaults to Python object operations if no types are provided, so maybe this goes wrong due to the integer range loop. Maybe the integer range-loop optimision should _only_ be handled in type inference and not enforced anywhere else.

**Comment by 0dminnimda** [comment]
I cannot reproduce the described behavior with cython 3.0.0a10 on windows, python 3.9.0
This probably can be considered fixed
