### ISSUE TITLE
Better readability?

### ISSUE THREAD

**Issue by hmaarrfk** [cython/cython#2890]
Sometimes it is useful to read the C code that is generated from Cython. Unfortuantely, it really looks bad.

For example, all variables are prefixed by `__pyx_`? 

Simple for loops, create temporary variables and assign then to the variable that we actually want to iterate over.

```
  /* "_shared/interpolation.pxd":179
 * 
 *     # row-wise cubic interpolation
 *     for pr in range(3):             # <<<<<<<<<<<<<<
 *         for pc in range(3):
 *             fc[pc] = get_pixel2d(image, rows, cols,
 */
  for (__pyx_t_1 = 0; __pyx_t_1 < 3; __pyx_t_1+=1) {
    __pyx_v_pr = __pyx_t_1;
```

Is there a way to make this code more natural?

Is there a good reason to prefix every single variable?

Thanks for the awesome stuff?

**Comment by scoder** [comment]
> Is there a good reason to prefix every single variable?

It's C, so there is only one global namespace and the function namespaces. We prefix everything in order to prevent collisions with names defined outside of Cython code.

Personally, I would say: once you get used to ignoring the prefixes, it's actually not that bad.

> Is there a way to make this code more natural?

Well, it's generated code, with the intention of covering several different cases. We often generate more code, and then let the C compiler cut it down again, e.g. when inlining helper functions. It's really good at doing these things. :)

Specifically for the case of chained conditions, though, e.g. "a or b and c or d", the generated code is often excessively verbose. I wouldn't mind improving that. PR welcome, although also in that case, there are several different code patterns that the generated code covers, so it's not like _everything_ that looks complex can be easily simplified.

**Comment by hmaarrfk** [comment]
gah the global namespace thing makes sense.

Reading the c code is really helpful to understand where things might be optimized, thanks for the reply!!!!
