### ISSUE TITLE
Implement @dataclass for cdef classes

### ISSUE THREAD

**Issue by scoder** [cython/cython#2903]
[PEP 557](https://www.python.org/dev/peps/pep-0557/) defines dataclasses, a new feature in Py3.7. It would be nice if Cython could generate equivalent code for cdef classes directly at translation time when it finds an `@dataclass` constructor on them.

This can be done by generating Cython code and injecting it into the module, similar to what we do for fused types (see `FusedNode.py`) or auto-pickling (see the `AnalyseDeclarationsTransform` in `ParserTreeTransforms.py`). The latter would probably also be a good place to implement the `@dataclass` decorator, although it seems worth keeping the main part of the implementation in a separate module instead of the transform itself, e.g. `Cython.Compiler.Dataclasses`.

Since this only applies to cdef classes, it seems better to use a safe and dedicated separate decorator `@cython.dataclass` than to rely on the generic Python decorator, at least initially.

**Comment by da-woods** [comment]
I have a 60% complete implementation of this. A few design questions:

What attributes should be included? Definitely annotated variables. Maybe regular `cdef` variables?

What should the visibility of the attributes be? There's a few options:
1. Default to invisible, like for a standard `cdef class`. This is obviously consistent. The issue with this is that there's a few functions in the `dataclasses` module like [`asdict`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) which assume that every attribute declared in `__dataclass_fields__` is readable. If they aren't then the classes won't be compatible with those interfaces.

     If so, should non-public attributes be omitted from `__dataclass_fields__`? This seems inconsistent since they do appear in the destructor, the repr, and affect the comparisons.

2. Default to visible. This is inconsistent with the standard `cdef class` behaviour, but would make them as compatible as possible with standard `dataclasses`. It would also make sense for most use-cases I think. One problem is that the syntax doesn't really exist of override that (only `public` and `readonly` are defined).

3. Annotated variables default to visible, `cdef` variables to invisible? It kind of makes sense and gives a way to control visibility, but it seems a little odd to me.

This deviates from the normal `cdef class` behaviour where
```
cdef class C:
   a: `int` = 0
```
makes a class variable. I think this is unavoidable and makes sense in this case, but any other ideas?

------------------------

None of these questions are major blockers for progressing on it though.

**Comment by Anaphory** [comment]
I have a bit of Python code with several `@dataclass` classes in there. Once you have figured out the desing choices, how will using them in Cython look like?

For example, if I have a

    @dataclass
    class House:
        rooms: int
        inhabitants: List[Person] = field(default_factory=list)

will that just become
    @dataclass
    @cython.cclass
    class House:
        rooms: cython.int
        inhabitants: List[Person] = field(default_factory=list)

or will there be more tweaking necessary? Currently, I encounter a whole load of problems (enough to discourage me from using Cython) when sticking `@dataclass` on a class and then compiling that with Cython, should I expect it to be easier or harder with `@cython.cclass`es?

**Comment by da-woods** [comment]
>  I encounter a whole load of problems (enough to discourage me from using Cython) when sticking `@dataclass` on a class and then compiling that with Cython

Well currently Cython doesn't support dataclasses at all on either `cdef class` (because my implementation of it needs finishing) or on regular classes (because class-level annotations aren't yet supported). So if you want to use dataclasses then right now you definitely shouldn't use them with Cython. However, that needn't stop you from compiling other modules with Cython (you can pick and choose what to compile).

>  how will using them in Cython look like?

Probably pretty similar to what you've outlined. Note that `List[Person]` will accomplish nothing in terms of typing (but hopefully shouldn't break anything). You may have to [c]import `field` and `dataclass` from Cython, but that should be the main difference.

--------------------------------------------

The main design decision is just figuring out how public (i.e. visible from Python) the attributes should be. They probably should be public where possible, but this is a bit of a design break from regular cdef classes.

I'm not really sure how useful a special implementation for cdef classes is - adding class annotations so they dataclasses can work on regular classes is probably a more useful solution generally.

**Comment by GliderGeek** [comment]
great initiative! iam greatly helped if this is implemented. ideally native dataclasses are supported, but this would also be a very good alternative.

**Comment by amal-khailtash** [comment]
What is the status of this?  It will be very useful for me as well.  Much appreciated.

**Comment by da-woods** [comment]
> What is the status of this?

The status is basically:

* Regular (i.e. non-cdef) dataclasses should work in the latest alpha release, although there's probably [a few bugs you may run into if using `dataclasses.Field`](https://github.com/cython/cython/issues/4198).
* There's a [workable PR](https://github.com/cython/cython/pull/3400) that implements `cdef class` dataclasses (i.e. this issue). If you're feeling adventurous you can check out that code and use it yourself right now. Any feedback you have from trying to use it would be useful.
* The exact implementation of the PR may change, but the features probably won't (because they're largely fixed by the need to copy Python). Therefore any code you write to work with the PR will probably work whenever it's released.
* The PR needs further review before it can be merged. Unfortunately it's quite a large change (and some of the code may be "mixed" quality) which makes it quite a slow process to review.
* Hopefully it might make it in the next alpha release (or the one after that). But nobody would like to make promises to give dates.

**Comment by scoder** [comment]
cdef dataclasses have landed. Happy to get feedback.
