### ISSUE TITLE
parser fails to parse starred expression with language_level=3

### ISSUE THREAD

**Issue by jahodfra** [cython/cython#2939]
```
(env) vagrant@h2o:~/h2oai$ cython -3 test.pyx 

Error compiling Cython file:
------------------------------------------------------------
...
def results_check(*args):
    "%s %s" % ('2', *args)
                   ^
------------------------------------------------------------

test.pyx:2:20: starred expression is not allowed here
(env) vagrant@h2o:~/h2oai$ python3 test.pyx 
(env) vagrant@h2o:~/h2oai$ cython -2 test.pyx 
(env) vagrant@h2o:~/h2oai$ python2 test.pyx 
  File "test.pyx", line 2
    "%s %s" % ('2', *args)
                    ^
SyntaxError: invalid syntax
```

**Comment by jahodfra** [comment]
I failed to post a cython version "Cython version 0.28.3"

**Comment by scoder** [comment]
Interesting. I can confirm that it generates the correct code with language level 2, but fails with language level 3. My guess was that this is due to the string formatting optimisation into f-strings, which was added in 0.28 and only applies to unicode strings (not Py2 byte strings). The expression then becomes `f"{'2'} {*args}"`, and that does not work. Looks like we have to explicitly exclude star-expressions.

**Comment by scoder** [comment]
Thanks for the report and the short reproducer.

**Comment by jahodfra** [comment]
Thank you for confirmation and fast response.
