### ISSUE TITLE
Spurious warning "local variable might be referenced before assignment" when using with blocks

### ISSUE THREAD

**Issue by LordAro** [cython/cython#2942]
With the following pure python:

```python
def fizz():
    with open("foo.txt") as f:
        contents = f.readlines()
    print(contents)
```
Compiling with -Wextra gives:

```
 $ cython -Wextra --3str -o test.c test.py
warning: test.py:4:10: local variable 'contents' might be referenced before assignment
```

Which is a bit annoying when you're trying to compile with -Werror

`with` blocks should not be considered to be a decision block - `contents` will always be set
I had to put the code inside a function to get the warning - with the code at the top level there is no warning

**Comment by scoder** [comment]
This warning is actually correct.

Cython does not look into context managers, and thus does not know if it swallows the exception or not. Obviously, the context manager returned by `open()` does not (currently) do that, but others might. If the `f.readlines()` above fails, and the context manager decides to ignore the exception, then `contents` would not be initialised, and the following `print()` would raise an `UnboundLocalError`.

While we could special-case `open` in Cython, I'd rather not, because then you would still get the warning in cases where Cython does not (or cannot) know the behaviour of the context manager, which would be even more confusing.

**Comment by LordAro** [comment]
Ok, that's fair enough. In which case, why isn't there a warning at the top level?
