### ISSUE TITLE
What is the fastest way to create new numpy arrays in a cython function?

### ISSUE THREAD

**Issue by MaxNoe** [cython/cython#2964]
If I run `cython -a` on my cython files, lines like `np.zeros` are highlighted as involving a lot of python calls but the docs don't really mention another way to create numpy arrays.

Is there a more efficient way, to create a new numpy array in a cython function than calling (python) functions like `np.zeros`?

**Comment by TeamSpen210** [comment]
It looks like you could [`cimport numpy`](https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd), then use the [`PyArray_SimpleNew()`](https://www.numpy.org/devdocs/reference/c-api.array.html#c.PyArray_SimpleNew) C-API function to construct an array. I don't imagine it'd have a significant speed up though. Constructing things are  expensive anyway since you have to allocate all the memory, and construct the Python object. This would mostly just hide it from the annotated file. You'd need to measure to find out.

**Comment by robertwb** [comment]
Agree, this is probably the fastest way, though there's non-trivial overhead that can't be avoided when creating new array objects (and isn't reflected in the annotation; you have to profile to be sure). If you find this is a bottleneck, consider (if possible) creating a single larger array of a higher dimension. 

Closing as this isn't really an issue (and probably more appropriate for cython-users@googlegroups.com).
