### ISSUE TITLE
Passing pointers into extension type constructor

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3008]
In some cases it can be useful to wrap up some C level details into a Python object. This can be handy for Python users to pass around without needing to be concerned about the C level details. Also it can be useful for different C libraries that need to interact at this lower level.

For example `memoryview`s are a nice, common demonstration of this use case. Though not all use cases map to a `memoryview`. Sometimes we need to roll our own solution for this problem.

Take for instance the use case of sharing a pointer between two libraries. Python need not be concerned with this pointer. However C libraries will definitely need access to the pointer. In these cases it would be handy to build a Python object that can be passed around in Python code. At the C level libraries can access this pointer to facilitate operations that may require it.

In the interest of solving this use case, it would be nice to write some code that looks roughly like this. However today this code won't compile as a pointer cannot be passed to `__cinit__`.

```cython
cdef class hdl:
    cdef void* ptr

    def __cinit__(self, void* new_ptr):
        self.ptr = new_ptr
```

This is also the subject of at least a few StackOverflow questions and [some discussion on the Python mailing list]( https://mail.python.org/pipermail/cython-devel/2012-June/002734.html ).

* https://stackoverflow.com/q/18695402/3877089
* https://stackoverflow.com/q/31701550/3877089
* https://stackoverflow.com/q/35088883/3877089

One could work around this by changing the input to `size_t`. However this is a bit kludgy. It also may lose any type checking we might have had (supposing we want a specific pointer type).

```diff
diff --git a/code.pyx b/code.pyx
index 339d4cb..2c5573b 100644
--- a/code.pyx
+++ b/code.pyx
@@ -1,5 +1,5 @@
 cdef class hdl:
     cdef void* ptr
 
-    def __cinit__(self, void* new_ptr):
-        self.ptr = new_ptr
+    def __cinit__(self, size_t new_ptr):
+        self.ptr = <void*>new_ptr
```

Alternatively one can eschew the constructor and pass in the pointer after the object is made. Though this is even more kludgy than the workaround above and shifts more of the burden to users of this hand rolled object.

It would be nice to have a solution for this use case. Would be curious to hear thoughts on how best to proceed. 🙂

**Comment by TeamSpen210** [comment]
The problem is that the constructor arguments are passed around to a number of methods through Python's object code in rather specific ways - the magic methods always receive them in a tuple and dict. So the arguments must be passed in as Python objects to be storeable in those safely. Specifically `type.__call__()` -> Cython-generated `__new__()` -> `__init__()`. All three of those are C-slots which have to have the `(PyTupleObject *args, PyDictObject *kwargs) ` signature to be stored in the type struct.

The docs actually has a [section](http://docs.cython.org/en/latest/src/userguide/extension_types.html#instantiation-from-existing-c-c-pointers) on this - what it recommends is creating a `cdef`ed factory function (`staticmethod` or module-level) that accepts the pointer, creates your object and then returns it. You'll need to then make the class itself init with a null pointer, and make sure you handle that case safely. Good idea to do that anyway though.

Actually though, there is a good solution for your original problem - [`PyCapsule ` objects](https://docs.python.org/3/c-api/capsule.html). These are a builtin type which wrap a single `void *` pointer, letting you safely pass those through Python code. Their main purpose is to allow cross-library API use - you can store a struct of function pointers in one, then import it from a different extension module to be able to access and call those easily.

**Comment by scoder** [comment]
I think the best solution is really to make the initialisation explicit using a factory function. Cython shouldn't do any magic here to (try to) make this appear to work.
