### ISSUE TITLE
Operation only allowed in C++, Windows 10, python 3.6

### ISSUE THREAD

**Issue by hieuthehungry** [cython/cython#3016]
I tried to import a package into my Jupyter Notebook, but is given an error notification saying: Error compiling cython file. Can somebody help me resolve the problem? Thanks!

**Comment by david-cortes** [comment]
That's not nearly enough information to diagnose a problem. Please be more specific and add at a minimum:
* Which package? Is it a public package from pypi/conda?
* What's the full error message? (use backticks to display as code within github)
* What's your setup? (Python version, Cython version, OS, other relevant info)

Also if you are importing a package it should not be compiling anything.

**Comment by samaingw** [comment]
So, I'll try here to make a guess work, based on the issue's title.

If I understand you correctly, you have somewhere a cython compilation which is taking place, and you have the `Operation only allowed in C++` error.

If so, it is due to the fact the code you're compiling is using new/del statements on cppclass object pointers, without cython being invoked in c++ mode.

Fix: pass the `--cplus` option to cython.

I do not understand too why you have a cython compilation when importing a package.

**Comment by scoder** [comment]
Closing since the description is so unclear that it's impossible to work on.
