### ISSUE TITLE
Inline C code within PYX for single-source compilation

### ISSUE THREAD

**Issue by coderforlife** [cython/cython#3051]
See #556 for one version of this.

This would be a great feature that I have wanted many times. There are several situations where I need like 10 lines of C or C++ code to bridge something that Cython cannot quite do and thus have to add a separate file for. Would be wonderful to have single-source capability. Sad to see no response has been made here. One suggested way to do this is like:

```
cdef extern from _:
    """
    C or C++ code goes here in this string. Gets included as if it had been in a header file (instead of using _ above).
    """
    # Then the normal extern definitions go here.
```

There is already a `cdef extern from *:` so `cdef extern from _:` shouldn't be so bad. However you do have to add the requirement for a string showing up as the first thing in the block. The string get copy-and-pasted into the generated source.

**Comment by coderforlife** [comment]
I was digging through the code to see if I could fix this myself and do a PR and it seems to already exist! (using `*` instead of `_` but I don't care about that). A little more searching and I found it in the docs as well at https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#including-verbatim-c-code

So this issue has become:
- you should close #556 and this issue.

**Comment by nevion** [comment]
@coderforlife thanks for following up, I'm happy to have learn there was a change of heart to some degree.

It looks like that's not quite a substitute though, it's more of an implementation of the entire function block inside the docstring (not at all a bad thing) and it looks like it targets pure c rather than something for instance using Eigen./includes and additional linker flags.

So I don't think #556 should be closed, but thank you for chiming in and hopefully bringing attention back to it.

**Comment by coderforlife** [comment]
Great. Didn't understand that part of the previous issue. Closing this one.
