### ISSUE TITLE
C++: classes in classes, cimport not consistent

### ISSUE THREAD

**Issue by gerion0** [cython/cython#3074]
Consider this minimal example:

foo.h
```
#pragma once

#include <iostream>

struct Foobar {
        struct LongName {
                void foo() {
                        std::cout << "foo" << std::endl;
                }
        };

        static LongName get() {
                return Foobar::LongName();
        }

};
```

foo.pxd
```
#cython: language_level=3

cdef extern from "foo.h":
    cdef cppclass Foobar:
        cppclass LongName:
            void foo()

        @staticmethod
        LongName get()
```

foo.pyx
```
from foo cimport Foobar

def my_func():
    cdef Foobar.LongName bla
    bla = Foobar.get()
    bla.foo()
```

This works so far. However, this does not work:

foo1.pyx
```
cimport foo

def my_func():
    cdef foo.Foobar.LongName bla
    bla = foo.Foobar.get()
    bla.foo()
```
foo2.pyx
```
from foo cimport Foobar
from foo cimport Foobar.LongName as LongName
# alternative, also not working:
# from foo.Foobar cimport LongName as LongName

def my_func():
    cdef LongName bla
    bla = Foobar.get()
    bla.foo()
```
While this works:

foo3.pyx
```
from foo cimport Foobar

ctypedef Foobar.LongName LongName

def my_func():
    cdef LongName bla
    bla = Foobar.get()
    bla.foo()
```

For me, this feels like C++ class in C++ class is not consistent. Is it possible to support also the long nested name (`foo.Foobar.LongName`)?

**Comment by scoder** [comment]
A `cimport` from a class cannot work (only from modules, as in Python), but the other examples look reasonable to me. PR welcome to make them work.

**Comment by PyBDIME** [comment]
### Keybase proof

I hereby claim:

  * I am pybdime on github.
  * I am pybdime (https://keybase.io/pybdime) on keybase.
  * I have a public key ASBu0GEsVjWJ1My8iuP1W1sKChVSWSjKWYyuIY1UtB8uPgo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "01206ed0612c563589d4ccbc8ae3f55b5b0a0a15525928ca598cae218d54b41f2e3e0a",
      "host": "keybase.io",
      "kid": "01206ed0612c563589d4ccbc8ae3f55b5b0a0a15525928ca598cae218d54b41f2e3e0a",
      "uid": "95fd537ee40d9b30c9b89608c2505419",
      "username": "pybdime"
    },
    "merkle_root": {
      "ctime": 1568093944,
      "hash": "eb49fef8882de5dc775e028abdf6905b3b03bc0b64b7bf7dd80d23cf2c333670e418efc1cbfff518243caac1c82d81becd5147b3a53bc8b2d4d30e588630bb64",
      "hash_meta": "72a25751098e59e759f9fa74f3dcffcc75b493d54300a71d94234a2da84aaed3",
      "seqno": 6321099
    },
    "service": {
      "entropy": "hozT+YRdXYR5Q91BuAQUJfF2",
      "name": "github",
      "username": "pybdime"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"
  },
  "ctime": 1568093954,
  "expire_in": 504576000,
  "prev": "32c8b205919427a42a0ddcea3c8c7368cf86e48536fc752f2bf2b1684ef5236a",
  "seqno": 6,
  "tag": "signature"
}
```

with the key [ASBu0GEsVjWJ1My8iuP1W1sKChVSWSjKWYyuIY1UtB8uPgo](https://keybase.io/pybdime), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgbtBhLFY1idTMvIrj9VtbCgoVUlkoylmMriGNVLQfLj4Kp3BheWxvYWTESpcCBsQgMsiyBZGUJ6QqDdzqPIxzaM+G5IU2/HUvK/KxaE71I2rEIEz598ObyjAAvUiplD5t60ae9Kzn4w2Q9F/OjbJk0TjbAgHCo3NpZ8RAlcPlNZSZcMIxYi6C9d829P6cEnO88Axzmeuct/cLN7193qF842bK8crQpWXFtY+zlXvmeaari8Qf/pGlyHMkCqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIEMCNG9h/DoL+cguWwfPW74PMNGo6kElIKmmVKFPMzmro3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/pybdime

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id pybdime
```

**Comment by nguyensy12** [comment]
### Keybase proof

I hereby claim:

  * I am nguyensy12 on github.
  * I am synguyen (https://keybase.io/synguyen) on keybase.
  * I have a public key ASBLhI9TV4b-ybm4HBmmJvYsiAja48hEJuUvuJrL-vH0Pgo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "01204b848f535786fec9b9b81c19a626f62c8808dae3c84426e52fb89acbfaf1f43e0a",
      "host": "keybase.io",
      "kid": "01204b848f535786fec9b9b81c19a626f62c8808dae3c84426e52fb89acbfaf1f43e0a",
      "uid": "3bd9e895c78f7d7896be5a11ac3c7219",
      "username": "synguyen"
    },
    "merkle_root": {
      "ctime": 1568096693,
      "hash": "abc72e80a25a950f885f4cedff026bebc1c302bed370749686c5445d714fb9991bda1b0bbaae5adce05bdd40973f3e45f138d6f61b86929cfc7344300ee141c0",
      "hash_meta": "0cbdb706697e6782d8d569ae140e3d207d94e07b750bb2fb63f7945c7f0709d1",
      "seqno": 6328633
    },
    "service": {
      "entropy": "k2skRY8ppaIys3UtqKIR9FXx",
      "name": "github",
      "username": "nguyensy12"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"
  },
  "ctime": 1568096717,
  "expire_in": 504576000,
  "prev": "edb6b65f24bf063e5b1fa5c70d7328be2f0a2d2b62b9c9996885b2b587254ae0",
  "seqno": 5,
  "tag": "signature"
}
```

with the key [ASBLhI9TV4b-ybm4HBmmJvYsiAja48hEJuUvuJrL-vH0Pgo](https://keybase.io/synguyen), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgS4SPU1eG/sm5uBwZpib2LIgI2uPIRCblL7iay/rx9D4Kp3BheWxvYWTESpcCBcQg7ba2XyS/Bj5bH6XHDXMovi8KLStiucmZaIWytYclSuDEICVLAXdfIBTOtAgAWDBSjy439qwaWHmhcS7RmaNiRd5mAgHCo3NpZ8RA0HBtAhsIUfc08ueHrQ38THOiC03cOXaLckhDmDz1yucj7A/j8b9z4Qh7yF4SXlujUbph0e4FU3xpN/bfm1PXCahzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIAB9SjV1fws6IZllwjQ1w5SvzIk5XqrGt4NtTK36t/4yo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/synguyen

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id synguyen
```

**Comment by PhenyoMaboyoboyo** [comment]
What am I supposed to do
Follow the link?

On Sep 10, 2019 08:36, "nguyensy12" <notifications@github.com> wrote:

Keybase proof

I hereby claim:

   - I am nguyensy12 on github.
   - I am synguyen (https://keybase.io/synguyen) on keybase.
   - I have a public key ASBLhI9TV4b-ybm4HBmmJvYsiAja48hEJuUvuJrL-vH0Pgo

To claim this, I am signing this object:

{
  "body": {
    "key": {
      "eldest_kid":
"01204b848f535786fec9b9b81c19a626f62c8808dae3c84426e52fb89acbfaf1f43e0a",
      "host": "keybase.io",
      "kid": "01204b848f535786fec9b9b81c19a626f62c8808dae3c84426e52fb89acbfaf1f43e0a",
      "uid": "3bd9e895c78f7d7896be5a11ac3c7219",
      "username": "synguyen"
    },
    "merkle_root": {
      "ctime": 1568096693,
      "hash": "abc72e80a25a950f885f4cedff026bebc1c302bed370749686c5445d714fb9991bda1b0bbaae5adce05bdd40973f3e45f138d6f61b86929cfc7344300ee141c0",
      "hash_meta":
"0cbdb706697e6782d8d569ae140e3d207d94e07b750bb2fb63f7945c7f0709d1",
      "seqno": 6328633
    },
    "service": {
      "entropy": "k2skRY8ppaIys3UtqKIR9FXx",
      "name": "github",
      "username": "nguyensy12"

    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"

  },
  "ctime": 1568096717,
  "expire_in": 504576000,
  "prev": "edb6b65f24bf063e5b1fa5c70d7328be2f0a2d2b62b9c9996885b2b587254ae0",
  "seqno": 5,
  "tag": "signature"
}

with the key ASBLhI9TV4b-ybm4HBmmJvYsiAja48hEJuUvuJrL-vH0Pgo
<https://keybase.io/synguyen>, yielding the signature:

hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgS4SPU1eG/sm5uBwZpib2LIgI2uPIRCblL7iay/rx9D4Kp3BheWxvYWTESpcCBcQg7ba2XyS/Bj5bH6XHDXMovi8KLStiucmZaIWytYclSuDEICVLAXdfIBTOtAgAWDBSjy439qwaWHmhcS7RmaNiRd5mAgHCo3NpZ8RA0HBtAhsIUfc08ueHrQ38THOiC03cOXaLckhDmDz1yucj7A/j8b9z4Qh7yF4SXlujUbph0e4FU3xpN/bfm1PXCahzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIAB9SjV1fws6IZllwjQ1w5SvzIk5XqrGt4NtTK36t/4yo3RhZ80CAqd2ZXJzaW9uAQ==


And finally, I am proving ownership of the github account by posting this
as a gist.
My publicly-auditable identity:

https://keybase.io/synguyen
From the command line:

Consider the keybase command line program <https://keybase.io/download>.

# look me up
keybase id synguyen

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cython/cython/issues/3074?email_source=notifications&email_token=ANEJZKOXTFA2F4VZZ75PNWLQI457PA5CNFSM4IKTDENKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6KAA3A#issuecomment-529793132>,
or mute the thread

**Comment by scoder** [comment]
@PhenyoMaboyoboyo: please ignore the spam.

**Comment by PhenyoMaboyoboyo** [comment]
Thanks

**Comment by da-woods** [comment]
Should be fixed in https://github.com/cython/cython/commit/85945aae8ad42440fc3bf5f7c9be64a0a68b2952
