### ISSUE TITLE
Allow cimporting classes and functions by just defining there names?

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3134]
This would make it a lot easier to work with classes and functions that have lots of arguments and properties.
What I'm suggesting would look something like this.
`module.pyx`
```cython
cdef class example:
 cdef int a,b
 cpdef get_ints(self):
  return (self.a, self.b)
```

`module.pxd`
```cython
cdef class example
```

`othermodule.pyx`
```cython
from module cimport example
cdef example x=example()
ex.a=20
x.b=40
print(x.get_ints())
```

This way, the declaration is taken from one file, nothing has to be changed in two places.
What could also work is adding a new decorator, which allows cimporting of whatever it's used on.
For example:
```cython
import cython
@cython.export
cdef class example:
 int a,b
```

This would allow cimporting the example class without a .pyx file.

**Comment by scoder** [comment]
You can `cimport` from a `.pyx` file, if you enable the feature via a compiler option.
https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#Cython.Compiler.Options.cimport_from_pyx

Apart from that, if your class (+attribute) declaration is in the `.pxd` file instead of the `.pyx` file, then this works, without a decorator. And it makes it clear what is exported and what isn't. That can be annoying at times, but it can also be an advantage.

Closing this ticket, since I can't really see what to further improve here.
