### ISSUE TITLE
CPython create_autospec does not work with cyfunctions 

### ISSUE THREAD

**Issue by dhiltonp** [cython/cython#3143]
Cython functions are not compatible with unittest.mock's `create_autospec` and asyncio's `iscoroutinefunction` when imported into a CPython module.

I'm not super familiar with the inner workings of cython and how it integrates with cpython, but getting the functions to work seems like the responsibility of cython, not cpython.

----------

CPython's unittest.mock uses FunctionTypes, a tuple with 2 objects, to determine if an object is callable for the purposes of automatically creating a mock object.

https://github.com/python/cpython/blob/master/Lib/unittest/mock.py#L2715

Should Cython patch FunctionTypes to also include cyfunction types? Or is there a better way of making this change?

----------

Additionally, CPython's `asyncio.iscoroutinefunction` cannot determine that a cythonized function is async. 

[iscoroutinefunction](https://github.com/python/cpython/blob/ae239f6b0626e926613a4a1dbafa323bd41fec32/Lib/asyncio/coroutines.py#L164) looks for one of two things: [inspect saying it's a coroutine](https://github.com/python/cpython/blob/ae239f6b0626e926613a4a1dbafa323bd41fec32/Lib/inspect.py#L189) or the function having `_is_coroutine` assigned to a specific object (internal use).

I think the best way to do this is to make `_has_code_flag(obj, CO_COROUTINE)` return True for cython functions.

---------------

Pointers on what to modify in cython's code base are welcome!

**Comment by fornellas** [comment]
Exactly the same issue for TestSlide's [StrictMock](https://testslide.readthedocs.io/en/2.0.2/strict_mock/index.html#coroutine-functions-async-def), [mock_callable()](https://testslide.readthedocs.io/en/2.0.2/mock_callable/index.html) / [mock_async_callable()](https://testslide.readthedocs.io/en/2.0.2/mock_async_callable/index.html).

**Comment by scoder** [comment]
> Should Cython patch FunctionTypes to also include cyfunction types?

IMHO, no. Cython can't know all tools and places where some code tries to decide what is a function and what isn't. Instead, tools like `unittest.mock` should use appropriate ABCs or duck typing for their needs, as one would also do for everything else in Python. If you want to know if an object is callable and what arguments it takes, *do not* check if it's a function. Instead, use `callable()`, the `inspect` module, and/or look at its special attributes and methods.

Since there already is a ticket for the `async` part, I'll close this ticket as "won't fix" – unless someone convinces me that what I write above is wrong. :)
