### ISSUE TITLE
typeid failed on fused types

### ISSUE THREAD

**Issue by thautwarm** [cython/cython#3203]
```cython
# cython: language=c++
# cython: language_level=3str
from libcpp.typeinfo cimport type_info
from cython.operator cimport typeid
cdef fused C: 
   int 
   object 
cdef const type_info* i32 = &typeid(int) 
cdef f(C x): 
    cdef const type_info* a = &typeid(C) 
    return a  == i32 
     
def g(x): 
   return (x, f(x)) 
```

**Comment by scoder** [comment]
It's generally helpful in bug reports to also show the error message that results, as well as other relevant information, such as the code that was generated. Providing this information reduces the time that others need to plan to invest in order to investigate the issue. Basically, when I have limited time and an issue seems more costly to look into than what I currently can (or want to) invest, I look at other issues first.

**Comment by thautwarm** [comment]
Okay, will do this
