### ISSUE TITLE
cython-mode.el runs into a endless loop.

### ISSUE THREAD

**Issue by yssource** [cython/cython#3218]
spacemacs freezes, when opening cython-mode files, such as .pyx, .pxd #12740
https://github.com/syl20bnr/spacemacs/issues/12740

**Comment by lesteve** [comment]
More precisely (as noted in syl20bnr/spacemacs#12740), this is the function `cython-current-defun` that never finishes in some cases (I would guess non-Python syntax). For completeness this was a problem in my setup because I had `which-function-mode` enabled which means that opening a Cython file would hang once my cursor was on such a problematic line.

To reproduce:
```
# test-cython.pyx
cdef void test():
    cdef double my_var
```

Go to the second line of `test-cython.pyx` and `M-:` `(cython-current-defun)` will never finish.

**Comment by yssource** [comment]
Thanks.
I also turn off the `which-function-mode` for `cython-mode` as a workaround for myself.
