### ISSUE TITLE
Dictionary unpacking doesn't create a copy

### ISSUE THREAD

**Issue by malcolmvr** [cython/cython#3227]
With Python, executing the following code:

```
o = {'a': 1, 'b': 2}
o2 = {**o}
o2['a'] = 3
print(o['a'], o2['a'])
```

results in `(1, 3)` being printed.

When compiled with Cython `(3,3)` is printed.

If the code is changed to:

```
o = {'a': 1, 'b': 2}
o2 = {**o, 'c': 4} # changed
o2['a'] = 3
print(o['a'], o2['a'])
```

Then the Cython compiled version behaves the same as the Python-interpreted version. Cython seems to be taking a shortcut and not creating a copy of the object.

**Comment by pengwk** [comment]
@da-woods Are there any plans to fix it?

**Comment by da-woods** [comment]
I don't think anyone's currently working on it. A PR would be welcome. It probably isn't too difficult to fix - I suspect it is just a case of removing an optimization that shouldn't really be there.

In the short-term you could probably work around it by explicitly calling `dict(d)` rather than `{**d}`

**Comment by pengwk** [comment]
I have checked that there is no problem with the above code, and also initiated a pull request to fix the problem I mentioned before. @da-woods
