### ISSUE TITLE
function __module__ variable wrong with PEP420 namespace packages

### ISSUE THREAD

**Issue by xzy3** [cython/cython#3260]
I'm having a problem with a cython module and pickle. I think I've tracked it down to the fact that the `__module__` variable for the function is wrong. I'm using a PEP420 native namespace package. I'm using the master branch checked out just a few minutes ago.

```Python-console
Python 3.7.0 (default, Aug 15 2018, 09:03:42)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
>>> cython.__version__
'3.0a0'
>>> import cdcdvh.pyseqdist.cDistance
>>> cdcdvh.pyseqdist.cDistance.edit_distance.__module__
'pyseqdist.cDistance'
```

**Comment by scoder** [comment]
It seems that namespace packages are not being considered when calculating the fully qualified module names. This is handled by the package detection machinery in `Cython/Utils.py`.

Note, however, that it's not entirely obvious how to interpret [PEP 420](https://www.python.org/dev/peps/pep-0420/) when it comes to *compiling* a module from a specific *file path*. There is no import going on in this case, and the module search path is not being looked at (and might not even contain the namespace package directory, since we're at build time).

PR welcome if there is a good way to do it, but failing that, it might turn out to be easier for users to specify the full module name in their `setup.py` script, rather than relying on namespace packages for their builds.

**Comment by xzy3** [comment]
https://github.com/pypa/setuptools/issues/97

is the setuptools discussion of this exact situation.

**Comment by scoder** [comment]
The ticket is very long, proposes multiple approaches and then splits up into further tickets. Could you please sum up their solution, so that we can see if it applies similarly to Cython?

**Comment by xzy3** [comment]
They ended up creating a new function: find_namespace_packages 

I'm actually using setuptools Extension objects in my setup script with the full module name. Given the way setuptools handled it I thought that was the most obvious way to get the correct setting. I've been trying to follow how that name moves through the Cython pipeline and why the compiler is even trying to re-derive the name from the path for the module variable. It's been a convoluted spelunking trip so far. I plan on doing an interactive debug of the compile process at work tomorrow. Holiday schedule permitting I hope to get a PR together for the issue before too long. 

I'm not sure if something else should be done with the cythonize procedure to deal with namespace packages.

**Comment by xzy3** [comment]
Sigh well. I spent a long time working on this and it has turned out to be a PEBKAC error (not surprising). I had an old version of the .so hanging around which was being found first on the lib path. I removed that and things seem to be OK now.
