### ISSUE TITLE
Please add support for std::optional

### ISSUE THREAD

**Issue by eyjohn** [cython/cython#3293]
I appreciate that there is already an issue for c++17 (https://github.com/cython/cython/issues/2206), but I was hoping that reducing the scope to a specific component of it: `std::optional` would make it easier to add earlier. 

This would of course mean that it will not be fully supported, e.g. no emplace until things like variadic template parameters are implemented. However I think most of the useful functionality here: https://en.cppreference.com/w/cpp/utility/optional can already be supported.

**Comment by jjerphan** [comment]
@eyjohn: FYI, https://github.com/cython/cython/pull/4225 introduced some support for `std::optional`.

**Comment by da-woods** [comment]
> FYI, #4225 introduced some support for `std::optional`.

#4225 is not *quite* the same: it's using `std::optional` internally to try to make C++ objects behave more like Python objects (so that they're only initialized at their first use, that kind of thing). It probably ends up providing a lot of the functionality that people would try to use `std::optional` for, but you should probably view it as a feature that happens to be implemented with `std::optional` rather than a way of exposing `std::optional`.

So PRs remain welcome for a .pxd wrapper for `std::optional` - the basics should probably be fairly straight-forward to write.

**Comment by isVoid** [comment]
Thank you very much for making this feature available! Is it possible to backport this to 0.29?

**Comment by da-woods** [comment]
> Is it possible to backport this to 0.29?

No. We really aren't backporting new features to 0.29.

However, the pxd files for the C++ standard library don't do anything special. You can just download https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/optional.pxd and use it in your project.
