### ISSUE TITLE
cgi.escape was removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [cython/cython#3309]
I just stumbled across this grepping for `cgi.escape` . I am not sure Tempita is public and documented for usage but found a usage causing `AttributeError`. `cgi.escape` was removed in Python 3.8 with https://github.com/python/cpython/pull/7662 . Usage of `html.escape` is recommended.

https://github.com/cython/cython/blob/6e72d84f43fc8f8da4ddc7695ac9f5b434788ef5/Cython/Tempita/_tempita.py#L444

```
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cython.Tempita
>>> Cython.Tempita.HTMLTemplate("a")._repr(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Cython/Tempita/_tempita.py", line 489, in Cython.Tempita._tempita.HTMLTemplate._repr
  File "Cython/Tempita/_tempita.py", line 446, in Cython.Tempita._tempita.html_quote
AttributeError: module 'cgi' has no attribute 'escape'
```

Thanks for Cython!

**Comment by auvipy** [comment]
I want to contribute on this

**Comment by scoder** [comment]
That part isn't really intended for use, more of a left-over from the original Tempita code base.
Still, PR welcome to fix this.

**Comment by mstimberg** [comment]
Note that this issue became a bit more urgent since the whole `cgi` module is now (Python 3.11) deprecated, i.e. simply importing the `Tempita` module will lead to a `DeprecationWarning`. Some CI's might turn these warnings into errors.
I'd be happy to open a simple PR that removes the `cgi` module and replaces it by `html`, but it feels a bit odd since apparently the code in `html_quote` is not used in the first place (given that it cannot be run since Python 3.8 and no one complained...).

**Comment by da-woods** [comment]
> I'd be happy to open a simple PR that removes the `cgi` module and replaces it by `html`

A PR would definitely be welcome. But I'd propose just removing it rather than replacing it since it looks unused.

**Comment by mstimberg** [comment]
I am a bit afraid of breaking something, since none of this is covered in the test suite and I have no idea what the original use case for this code is/was. If I remove the `html_quote` function that uses `cgi.escape`, this would not only mean removing `html_quote`, but also `attr`, `HTMLTemplate`, and `sub_html`, since they use `html_quote` directly or indirectly. The latter two (`HTMLTemplate` and `sub_html`) are included in `__all__`, so technically part of the public API. 
As mentioned before, the `html_quote` code is broken since Python 3.8, so it is unlikely that this hurts anyone, but technically the code could still be used somewhere with `force=False` and an object that has an `__html__` attribute...
https://github.com/cython/cython/blob/6e72d84f43fc8f8da4ddc7695ac9f5b434788ef5/Cython/Tempita/_tempita.py#L436-L451

**Comment by da-woods** [comment]
The background is that Tempita was originally a generic templating tool. It was incorporated into Cython to use for templating Cython's utility code, but obviously contains quote a bit of stale code from its original general use.

My view would be to just remove `html_quote` and the stuff that depends on it. We'll quite rapidly find out if it breaks any of Cython's utility code generation (its primary use) since that is covered by the the test-suite.

A few projects (Pandas, Scipy) do use Tempita from Cython to do some code-generation of Cython code. This is also a use-case that we're keen to support better, so possibly we possibly shouldn't be too brutal removing everything that's unused. I still think it's reasonable to remove these html bits that have been broken for years.

------------------------------

With that said, I'm happy to do the removal myself if you'd rather someone else gets the blame for it!

**Comment by scoder** [comment]
+1 for removing the obviously broken HTML parts. If users employ Tempita on their side, it's for source code generation, not HTML. There are much better tools for the latter.
