### ISSUE TITLE
RELEASE 3.0 ALREADY

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [cython/cython#3325]
@scoder Stefan:

1. you keep warming up people with your talks

`Stefan Behnel - Get up to speed with Cython 3.0`
https://www.youtube.com/watch?v=lxh4lsvEBhI

`LT: Stefan Behnel: Cython 3.0`
https://www.youtube.com/watch?v=r-3o3gUre-Q

2. `cython` still have 10 blockers in 3.0 milestone:
https://github.com/cython/cython/milestone/58

which looks like about 5 more month of development
https://github.com/cython/cython/issues?q=is%3Aopen+is%3Aissue+label%3A%22P%3A+blocker%22

3. I think we are too warm already,
can you please release 3.0 now? thank you.

**Comment by scoder** [comment]
SCREAMING DOES NOT ALWAYS GET YOU WHAT YOU WANT! :o)

I freely admit that the work on Cython 3.0 has already taken very unexpectedly much longer than intended, and even than (re-)guesstimated along the way. What should I say … life.

I was considering to push out an alpha at some point, but there are still a couple of PRs and issues that I need to look through before that. Feel free to start using the master branch and reporting issues with it. Or, even better, help fixing those issues and send a PR or two.

Although I appreciate your concerns and encouragement, I'll close this ticket since it won't lead anywhere.

**Comment by Andrei-Pozolotin** [comment]
@scoder Stefan:

thank you for the feedback

> help fixing those issues and send a PR or two

it seems there is little point in committing to the project 
which makes no explicit commitments, when everything is "just the flow of life" :-)

what would you say about the following commitment:
1. say, you create a `3.0-alpha-1` milestone, with less then 5 issues in it
2. and then also promise that when that is complete you will in fact release the alpha 
3. and "release the alpha"  means within 3 days of `3.0-alpha-1` milestone completion?

? :-)

**Comment by McSinyx** [comment]
> it seems there is little point in committing to the project
> which makes no explicit commitments, when everything is "just the flow of life" :-)

While I'm as eager for Cython 3.0 as you are, I strongly disagree:  Software should be released when it is ready, and Debian is a prime example for it.  After all, maintainers are those taking responsibilities over breakage an upgrade might cause, and there are at least 40k projects just on GitHub using Cython for building (excluding those listing it in `pyproject.toml` which is not used by GitHub at the moment).  Shiny things are cool, yea, but working things are even cooler!

Since you don't want to be part of the development, which is fine--neither am I, you should let maintainers to work in their own pace.  Not every issue in 3.0 roadmap even have the direction to be solved (yet), so there is no point for rushing.

Please keep in mind that manually compiling is always an option, and as cythonized targets are not dependent on Cython, it causes no dependency hell doing so.

Happy Lunar New Year to you both!

**Comment by Andrei-Pozolotin** [comment]
@McSinyx Nguyễn:

> Since you don't want to be part of the development,

not true, I am actually considering to become part of the development,
I just want to get a better deal :-)

Chúc mừng năm mới âm lịch đến tất cả các bạn!

**Comment by auvipy** [comment]
if you contribute to close some open issue then the release will be faster :)

**Comment by Andrei-Pozolotin** [comment]
@auvipy Asif:

> if you contribute to close some open issue then the release will be faster :)

sure, true. just not good enough

here is what I propose instead: everybody makes commitment to each other, i.e.:

1. **Stefan** commits to:
* create a 3.0-alpha-1 milestone, with less then 5 issues in it
* and then also promise that when that is complete you will in fact release the alpha
* and "release the alpha" means within 3 days of 3.0-alpha-1 milestone completion

2. then "we, the people" commit to:
* **Andrei**: close at least one issue form 3.0-alpha-1 in less then 5 days
* **Nguyễn**: close at least one issue form 3.0-alpha-1 in less then 5 days
* **Asif**: close at least one issue form 3.0-alpha-1 in less then 5 days

3. lo and behold:
* no more unpredictable "flow of life"
* 3.0-alpha-1 is released in about 1 week

**Comment by auvipy** [comment]
> @auvipy Asif:
> 
> > if you contribute to close some open issue then the release will be faster :)
> 
> sure, true. just not good enough
> 
> here is what I propose instead: everybody makes commitment to each other, i.e.:
> 
>     1. **Stefan** commits to:
> 
> 
>     * create a 3.0-alpha-1 milestone, with less then 5 issues in it
> 
>     * and then also promise that when that is complete you will in fact release the alpha
> 
>     * and "release the alpha" means within 3 days of 3.0-alpha-1 milestone completion
> 
> 
>     1. then "we, the people" commit to:
> 
> 
>     * **Andrei**: close at least one issue form 3.0-alpha-1 in less then 5 days
> 
>     * **Nguyễn**: close at least one issue form 3.0-alpha-1 in less then 5 days
> 
>     * **Asif**: close at least one issue form 3.0-alpha-1 in less then 5 days
> 
> 
>     1. lo and behold:
> 
> 
>     * no more unpredictable "flow of life"
> 
>     * 3.0-alpha-1 is released in about 1 week

I already have a lot on the plate with celery. And I do not have the need of cython 3.0 anytime soon as you need :) so its best if you can manage your time to contribute for a faster cython 3.0 release.

**Comment by scoder** [comment]
@Andrei-Pozolotin, I'm not sure I understand what incentive you expect me (or others) to have in this, but as I wrote, this ticket is closed because I don't see it getting anywhere, so I'm not going to invest any more of my time into it (which I personally consider valuable).
