### ISSUE TITLE
Cython exetension class __getattr__ not doing the same behavoir with python's class counter part

### ISSUE THREAD

**Issue by nguoihn1988** [cython/cython#3404]
I tried to make a class in python, the following code works:
From my test_loop.pyd file
```
class mockClass:
    def __init__(self,val):
        self._val = val
    def __getattr__(self,attrName):
        print('Getattr:',attrName)
        print('This work on python:',self.__dict__)
        try:
            return self.__dict__[attrName]
        except:
            raise AttributeError("Unknow ",attrName)
    def __add__(self,val):
        return mockClass(self._val+val)
    def __str__(self):
        return str(self._val)
def test_func():
    print('In test func')
    myList = [1,2,3]
    for ii,item in enumerate(myList):
        if (ii==0):
            out = mockClass(item)
        else:
            print('Add:',item)
            out += item

    return out
```
And the module works, my test.py file:
```
import test_loop
a = test_loop.test_func()
print(a)


```
But when I change the python class to cython class I got stuck in the recursive loop: the function\_\_getattr\_\_ (I tried \_\_getattribute\_\_ too) get stuck because it try to find \_\_dict\_\_, which is, again, require function \_\_getattr\_\_.

```
cdef class mockClass:
    cdef int _val
    def __init__(self,val):
        self._val = val
    def __getattr__(self,attrName):
        print('Getattr:',attrName)
        print('This work on python:',self.__dict__)
        try:
            return self.__dict__[attrName]
        except:
            raise AttributeError("Unknow ",attrName)
    def __add__(self,val):
        return mockClass(self._val+val)
    def __str__(self):
        return str(self._val)
```

**Comment by McSinyx** [comment]
There are a few things to keep in mind here:

1. [Extension types](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html) isn't a normal Python type, as thus you should not expect it to always work in the same way.  For instance, many decorator would not work without weird hacks on the Cython side.
2. In extension types, `cdef` attributes are only visible to Cython code, unless specified otherwise (`readonly` or `public`).
3. `__dict__` doesn't exist in an extension type unless you declare it.
4. Never, ever, ever use bare `except` while doing magic, unless you know exactly what you're doing.
5. `__getattr__` is invoked when `AttributeError` is raised, hence the infinite recursion.
6. Last but not least, please don't use camelCase for class names.

**Comment by nguoihn1988** [comment]
1. ok, I just assume that they want to make extension type as close as python class possible, and newbie user (like me) usually assume so. And I think it's useful to have somewhere stating that there are differences. 
2. Yes I know so I tried to make some kind of getter/setter function to modify this from python. 
3. I didn't know that, thank you. 
4. I know it's look silly but it's a reduced code. 
5. Yes, I know, but I didn't know is __dict__ not existed in extension class, so I thought it was there but __getattr__ somehow can't get it. 
6. Why?

**Comment by McSinyx** [comment]
Since adding `__dict__` should solve the original issue (I hope), shouldn't this be closed?  Answering to (6), by convention camelCase should never be used in Python code at all, and in case to keep consistency, camelCase in other languages is often used for methods, which will eventually cause confusion if used as a class name.

**Comment by nguoihn1988** [comment]
Yes, I will close it. Manually adding __dict__ initialization in __cinit__ did solve the problem. I wanted to be able to switch code easily from Python to Cython. 
I reopened because I want to know about camelCase, I never heard of that.
