### ISSUE TITLE
ioctl.ioctl() not usable from cython

### ISSUE THREAD

**Issue by Flameeyes** [cython/cython#3457]
I'm trying to rewrite a wrapper from custom C to Cython, and I need to use `ioctl()`.

If I use the `posix.ioctl.ioctl()` function, I get an error:

```
Error compiling Cython file:
------------------------------------------------------------
...

    io_hdr.sbp = sense
    io_hdr.mx_sb_len = len(sense)
    io_hdr.timeout = 1800000

    result = ioctl(fid.fileno(), SG_IO, &io_hdr)
                                       ^
------------------------------------------------------------

linux_sgio/linux_sgio.pyx:135:40: Cannot convert 'sg_io_hdr_t *' to Python object
```

The shortened version of the sources would be:

```
from posix.ioctl import ioctl

def foo(fid):
    cdef sg_io_hdr_t io_hdr

    ioctl(fid.fileno(), SG_IO, &io_hdr)
```

**Comment by TeamSpen210** [comment]
You need to use `cimport`, not `import`. You're currently trying to import a regular Python function, which can't be called since a pointer isn't a Python object. `cimport` loads the C-definitions from a `.pyx`/`.pyd` [file](https://github.com/cython/cython/blob/master/Cython/Includes/posix/ioctl.pxd), adding the `#include` to the outputted C file and treating the functions with the appropriate semantics.

**Comment by Flameeyes** [comment]
Ouch, I need to get more coffee and re-read this more carefully next time. Indeed it works fine, thanks!
