### ISSUE TITLE
'myproject.alembic.versions.5fd6d5c5385c_init' is not a valid module name

### ISSUE THREAD

**Issue by tassoneroberto** [cython/cython#3464]
I receive this exception while `cythoning` an `alembic` file:
```bash
myproject/alembic/versions/5fd6d5c5385c_init.py:1:0: 'myproject.alembic.versions.5fd6d5c5385c_init' is not a valid module name
```
I tried to rename the file adding a character at the beginning (e.g. `f5fd6d5c5385c_init.py`) and the error disappeared. This means that the problem is related to the filename. More precisely the problem comes when the filename starts with a number.

**Comment by da-woods** [comment]
This seems correct - module names can't start with a number? It's more likely to be a bug in alembic if it's generating names that start with a number.

It's possible they're only designed to be used as a script rather than imported in which case it might be OK. If that's the case you should probably be using Cython with the `--embed` option to generate something callable rather than importable.

**Comment by scoder** [comment]
> they're only designed to be used as a script rather than imported

Yes. And I recommend against compiling them. That's way too much overhead and these scripts are extremely unlikely to be CPU bound themselves.
