### ISSUE TITLE
Is it possible to cast "PyObject*" to "object" without incrementing refcount?

### ISSUE THREAD

**Issue by AndreiPashkin** [cython/cython#3471]
Let's suppose I have a C function that returns a NEW reference to `PyObject`. And then I want to call it and return it's result from a function that returns `object`. Currently if I simply do something like this:
```
def pyfunc():
    return <object>PyDict_New()
```
There will be refcount increment in the generated `pyfunc()` code for the returned dict which is undesirable.

My question is - is there a canonical solution to this problem?

**Comment by scoder** [comment]
You should _really_ use `return {}` instead.

Apart from that, the whole point of `object` is to be refcounted. That is the difference to `PyObject*`, which is a pointer.

My guess is that you declared `PyDict_New()` as returning a `PyObject*`. That is incorrect. It returns an owned reference, i.e. `object`.

**Comment by scoder** [comment]
Please ask this kind of question on the cython-users mailing list in the future. The bug and issue tracker is only for tracking bugs and issues.

**Comment by AndreiPashkin** [comment]
@scoder 
> Apart from that, the whole point of object is to be refcounted. That is the difference to PyObject*, which is a pointer.

Makes sense.

> My guess is that you declared PyDict_New() as returning a PyObject*. That is incorrect. It returns an owned reference, i.e. object.

I ended up implementing this solution.

**Comment by scoder** [comment]
Sorry for insisting, but I was quite serious about this bit, actually:

> You should really use `return {}` instead.

In this case, it happens to translate into the same C code as calling `PyDict_New()`, but using normal Python syntax and idioms in Cython code helps avoiding human mistakes (like the one that lead to this ticket), keeps the code easier to read and more maintainable, and allows Cython to generate _more_ efficient code in many cases. It's really a win-win-win approach.

Only hand-tune your code if you really know and can prove in actual numbers that it's worth the added complexity. That applies to Cython in the same way as Python.

And, if you ever find a situation where you can write better C code than what Cython generates, consider improving Cython, so that all Cython users can benefit from it.

**Comment by AndreiPashkin** [comment]
@scoder 
> You should really use return {} instead.

I used `PyDict_New()` as an example of a function that returns a new reference, in reality I call another function from some user-made extension.

What would you say about functions like `PyTuple_GET_ITEM()`? Is it normal to use them? I've found out that writing them by hand in Cython files gives slight speed advantage.

**Comment by scoder** [comment]
> What would you say about functions like PyTuple_GET_ITEM()? Is it normal to use them? I've found out that writing them by hand in Cython files gives slight speed advantage.

Have you tried `@boundscheck(False)`? That's more likely to make a difference here than the reference counting.
