### ISSUE TITLE
Change in behaviour with %-formatted aligned string with tuple interpreted vs compiled

### ISSUE THREAD

**Issue by LordAro** [cython/cython#3476]
With the following testcase:
```python
print("str: '%08s'" % (""))
print("str: '%08s'" % ("",))
```

When run with python (3.8):
```
 $ python3 foo.py
str: '        '
str: '        '
```

When compiled with cython (0.29.15):

```
 $ cython --embed -3 foo.py && gcc foo.c -lpython3.8 -o foo
 $ ./foo
str: '        '
Traceback (most recent call last):
  File "foo.py", line 2, in init foo
    print("str: '%08s'" % ("",))
ValueError: '=' alignment not allowed in string format specifier
```

Something to do with the tuple is making it very unhappy...
Possibly related to #3092 ?

**Comment by scoder** [comment]
Yes, related to #3092. 

The difference between the two lines is that only the tuple case is being optimised, because the single-argument-non-tuple case is not easy to optimise (it _might_ still receive a tuple at runtime, especially since the real type is usually unknown and the argument is almost never a constant as in your simple example).

Both seem easy to fix. PR welcome.

**Comment by nanlliu** [comment]
is it something a beginner can do? any help tho? much appreciated!
