### ISSUE TITLE
Fused Type + Memoryview Parameter Throws unused-function Warning on Master

### ISSUE THREAD

**Issue by WillAyd** [cython/cython#3481]
Credit to @tacaswell for originally finding in https://github.com/pandas-dev/pandas/issues/33224

Using this as a minimum reproducible example:

```python
ctypedef fused number_t:
    int
    float

def add_one(number_t[:] arr):
    cdef Py_ssize_t i

    for i in range(len(arr)):
        arr[i] = arr[i] + 1
```

Compilation using Cython master will throw the following warning

```sh
cytest.c:3476:18: warning: ‘__pyx_pf_6cytest_8__defaults__’ defined but not used [-Wunused-function]
 static PyObject *__pyx_pf_6cytest_8__defaults__(CYTHON_UNUSED PyObject *__pyx_self) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

No warning is thrown using 0.29.14

From what I can tell, it seems to be specific using a fused type and a memoryview together in the function signature - changing the parameter type to say just `int[:]` does not throw a warning

**Comment by WillAyd** [comment]
Happy to debug - any pointers on where to start though? Stepping through the Pipeline I think the `__defaults__` node is already present by the time we get to `Cython.Compiler.ParseTreeTransforms.AnalyseExpressionsTransform`

**Comment by WillAyd** [comment]
Nice! Can confirm that it starts with #3366

**Comment by scoder** [comment]
@da-woods agreed that there's something wrong with the setup of the newly added default argument. I think it's correct that the getter is not used here (it's not a dynamic default argument value, for which it would be needed), so the bug is that the getter function is being generated. Some condition missing somewhere that would prevent that.

**Comment by WillAyd** [comment]
On the code generation side I've noticed that `self.defaults_getter` is assigned as `generate_function_definitions` is called for the `add_one` method in the example above. 

Excuse my ignorance if this is a dumb question, but would that not point to more of an issue with parsing (i.e. that a defaults_getter is assigned to the node) than code generation?

**Comment by WillAyd** [comment]
Perhaps also related, in the call to `PyCFunctionNode.analyse_default_args` there is the following branch:

https://github.com/cython/cython/blob/f364d6dd54eb879171fdb98dd744cb571edd4d6a/Cython/Compiler/ExprNodes.py#L9268

Though `add_one` doesn't provide default args or kwargs, `default_kwargs` is actually a list at this point containing a `CArgDeclNode` with name `_fused_sigindex`

**Comment by da-woods** [comment]
I'm not quite sure I understand the first comment - it looks to me like `defaults_getter` is set up using `PyCFunctionNode.analyse_default_args` and then used in `generate_function_definitions`. Both well after the parsing stage.

> Though add_one doesn't provide default args or kwargs, default_kwargs is actually a list at this point containing a CArgDeclNode with name _fused_sigindex

What's happened here is that a `add_one` needs to decide which version of the fused function to call. To do that it uses some generated Cython code (made in `FusedNode.py`). That generated Cython code uses a default argument with the name `_fused_sigindex` - that's an implementation detail that should be hidden from the user, but that's why the name has appeared.

None of which really tells you how to get rid of it I'm afraid.

**Comment by WillAyd** [comment]
First comment is probably me making a mess of semantics - I saw that the "analyze" call falls under the `ParseTreeTransforms.AnalyseExpressionsTransform ` part of the pipeline so just assumed that was still considered a "parsing" stage but probably not

I think I understand your comment; so at this point in the pipeline is there no way to disambiguate how `add_one` is defined (i.e. without default arguments) versus how the implementation may choose to dispatch to the appropriate fused functions that do contain a default argument?

**Comment by scoder** [comment]
I was guessing that there was just some inconsistent condition somewhere. Let's see if #3491 fixes it.
