### ISSUE TITLE
`$ cythonize -i file.pyx` broken?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3485]
In a `Python 3.8.2` `venv` with a `python3 setup.py install` from a branch that's even with `cython:master`, `$ cythonize -i somefile.pyx` seems to be invariably failing with silent segfaults for me.

It prints out the "`Cythonizing {filename}`" message, and then segfaults after a second or so. It doesn't segfault if it just skips the compilation, so the file has to be updated or `cythonize` has to be run with `-f`.

I tried deleting Cython from `site-packages`, but I haven't tried using a fresh `venv`, a full VM, or anything like that.

It happens for me in a `Python 2.7.17` `venv` too.

~~Building through `distutils` with `$ python3 setup.py build_ext --inplace` seems to work fine.~~

`python3 setup.py build_ext --inplace` has since also broken, so I suspect its maybe something with my system or `venv`, even though the system `cythonize` works fine.

I'll try a fresh `venv` and repository at some point, but this issue can probably just be closed in the meantime if it's not immediately reproducible.

**Comment by scoder** [comment]
Yes, when you switch from a release to a branch build, you'll have to clean your environments from time to time. Otherwise, you can easily end up with a mix of Cython compiled modules from different git revs, all thinking that they are the same version and can share the same ABI module. With major changes coming into the code base, that can easily lead to incompatibilities, all sorts of weird behaviour and crashes.
