### ISSUE TITLE
@cython.cfunc should reject dunder methods

### ISSUE THREAD

**Issue by ram-bv** [cython/cython#3503]
Stefan Behnel wrote:

> No. "@cython.cfunc" declares a function or method as a pure C function,
> without a Python interface to it, and for methods, it only applies to
> extension types and not regular Python classes.
> 
> It's interesting that Cython allowed you to set it on the "`__iter__`" method
> which cannot, in fact, be a C method because it's one of Python's special
> methods. We should disallow that.

**Comment by 0dminnimda** [comment]
I wonder what was the origin of this, any context?
```cython
@cython.cclass
class G:
    @cython.cfunc
    def __iter__(self) -> cython.int:
        return -1
```
or
```cython
class G:
    @cython.cfunc
    def __iter__(self) -> cython.int:
        return -1
```
produce reasonable errors, so I'm wondering what is the example for the described behavior?

**Comment by da-woods** [comment]
https://groups.google.com/g/cython-users/c/japoe4kYO9A

Reading through that issue again - I think what probably happened was that they applied the decorator and then ran it in Python (rather than recompiling with Cython). Since the Shadow.py version of cfunc is a no-op it didn't generate an error.

I'll close this because the decorator behaves correctly when applied in Cython, and I don't think we want to start adding checks to the Shadow.py stubs.

Thanks @0dminnimda
