### ISSUE TITLE
Fix inheritance of generic types (PEP-560)

### ISSUE THREAD

**Issue by scoder** [cython/cython#3537]
it seems like #3518 did not entirely fix this issue -- there will be an error if you try to inherit from the subscripted class.

For example, with the following in `example.py`, and building the same way as above:
```python
from typing import Generic, TypeVar

T = TypeVar("T")

print(Generic[T])

class MyGeneric(Generic[T]):
  pass
```

will give:
```python
>>> import example
typing.Generic[~T]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.py", line 7, in init example
    class MyGeneric(Generic[T]):
TypeError: __init__() takes 3 positional arguments but 4 were given
```

_Originally posted by @nikhilmishra000 in https://github.com/cython/cython/issues/2753#issuecomment-616874842_

**Comment by scoder** [comment]
What needs to be done:
- copy tests from CPython
- fix the implementation in `ObjectHandling.c` according to what CPython does here.

**Comment by GrosFap** [comment]
Hello, I have also this bug, is someone working on it ?

**Comment by scoder** [comment]
@GrosFap not that I know of. Help, investigations and PR(s) all welcome. See my comment just above.

**Comment by wyfo** [comment]
I've started to investigate some weeks ago, and I found that this issue was cause by the lack of handling for `__mro_entries__` (I would have won some time by better reading https://github.com/cython/cython/issues/2753#issuecomment-616928891)
In fact, in Cython, there is no equivalent of `__build_class__`, where `__mro_entries__` is evaluated.
That's why i'm not sure @scoder that a modification of `ObjectHandling.c` would be enough to add this mecanism in class building.

**Comment by scoder** [comment]
@wyfo see the `Py3ClassCreate` utility code in `ObjectHandling.c`.

**Comment by wyfo** [comment]
I can't remember if I'd already looked at this, but the signature is kind of similar to `__build_class__`, so I feel like I was kind of blind at that time … I'm looking at it right now, and indeed, if we insert an equivalent of CPython `update_bases`, it could do the job.
I will try to do it this weekend (but I don't promise anything, cause I find the quite hard to get into the code and I haven't find the documentation I need — for instance, looking for a simple way to copy a tuple, have to juggle between Cython and CPython code to come up with `PyObject *orig_bases = __Pyx_PyTuple_FromArray(((PyTupleObject*)bases)->ob_item, PyTuple_GET_SIZE(bases))` — I'm very new to CPython/Cython)

**Comment by da-woods** [comment]
@wyfo Don't do `PyObject *orig_bases = __Pyx_PyTuple_FromArray(((PyTupleObject*)bases)->ob_item, PyTuple_GET_SIZE(bases))` - we try to use the C API functions and avoid accessing semi-private details such as `ob_item`. That kind of detail tends to break compatibility with things like PyPy.

Is there a good reason you have to copy it? Under most circumstances tuples should be immutable so there's no advantage to a separate copy. If you *really* do have to copy it then it might be better to do `PyTuple_New` then a loop where you set elements.

**Comment by nekokatt** [comment]
If anyone can give me guidance on where exactly to start with this, I'd be more than happy to try and piece a fix together for this, since per #3794, this is one of the main reasons my project which has around 30kloc cannot be Cythonized on the current master version of Cython.

I haven't ever worked on this codebase though so I am not entirely sure on where I need to be looking for this.

**Comment by da-woods** [comment]
@nekokatt As said above, this is most likely a change to the "Py3ClassCreate" utility code: https://github.com/cython/cython/blob/aa8b0d9b89030c0b9ace5698ae5131c623acefa4/Cython/Utility/ObjectHandling.c#L1034 (I've linked to the broad section). This C code is largely just copied into each generated Cython file.

We currently don't handle `__mro_entries__` according to PEP-560 so it's largely a case of working out what stage that should be called at and calling it.

The change will then need some tests, which are probably best done by copying the [cpython tests](https://github.com/python/cpython/blob/d437012cdd4a38b5b3d05f139d5f0a28196e4769/Lib/test/test_genericclass.py) as much as possible. We already have [the equivalent file](https://github.com/cython/cython/blob/c0ceabe1ee0904477ed0b0b9371ae43915d7bd2f/tests/run/test_genericclass.py) but the MRO tests were omitted since they weren't yet supported.

**Comment by gst** [comment]
and I'm getting: 

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "try_generic.py", line 18, in init try_generic
    print(Generic[T])
TypeError: 'type' object is not subscriptable
>>> 
```

**Comment by gst** [comment]
I have the issue with the latest versions (2.* and 3.*)..
