### ISSUE TITLE
Migrate NumPy declarations to the NumPy project

### ISSUE THREAD

**Issue by scoder** [cython/cython#3573]
The NumPy project should maintain the NumPy `.pxd` declarations on their side.
See https://github.com/numpy/numpy/issues/11803#issuecomment-417837512

This seems to imply that we will need to keep shipping a legacy version on our side. TBD.

Things to do:
- make it easy and safe for the NumPy project to maintain the declarations on their side
- make it clear for users which version is used
- try to avoid inconsistencies that lead to difficult to debug problems on user side
- try to avoid breakage or hard dependencies on either side

**Comment by mattip** [comment]
NumPy has been shipping the older, non-`@property` version of the `pxd` since numpy/numpy#12284 which landed in v1.18, released in January 2020. Once Cython 3.0 is released, NumPy can upgrade immediately to the version with the `@property` decorator. 

I am not sure what the backward support story is for Cython + NumPy. According to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), July 2021 is the earliest possible date for deprecating 1.17, but we are still getting reports of people building older, supposedly deprecated NumPy versions. It is tricky to retroactively limit the highest version of Cython used to build NumPy (although the sdist package does not require Cython).

**Comment by scoder** [comment]
The main thing that I would like to avoid is that users have installed both Cython and NumPy, their build picks either of the two declarations that they ship (Cython for legacy reasons), and both API declarations disagree in some way. That would be difficult for users to understand and debug.

OTOH, we could assume on our side that if the NumPy provided declarations cannot be found on the Python search path, then it's probably because either 1) NumPy is not installed or 2) the version of NumPy is < 1.18. In both cases, picking up the (then potentially outdated) declarations that Cython still provides would probably be ok.

IIRC, then Cython already prefers the Python search path over its own shipped libraries. We could leave it at that, and just add a marker to the generated C files like `/* BROUGHT TO YOU BY LEGACY NUMPY DECLARATIONS */` or so. :)

**Comment by mattip** [comment]
> Cython already prefers the Python search path over its own shipped libraries. We could leave it at that, and just add a marker to the generated C files like /* BROUGHT TO YOU BY LEGACY NUMPY DECLARATIONS */ or so. :)

xref gh-2910 that enabled prefering a builtin NumPy pxd to the one Cython provides, with a mechanism for overriding via `include_directories` if desired. I like the idea of somehow marking the generated C files, do you have an idea how to do it?

**Comment by scoder** [comment]
> marking the generated C files, do you have an idea how to do it?

See 81a8955 :)

**Comment by scoder** [comment]
Ok, now that NumPy will [eventually](https://github.com/numpy/numpy/pull/16162) have its own `numpy/__init__.pxd`, what is the next step? If users have a NumPy version with its own declarations installed, then those should get picked up instead of Cython's. Good. But if NumPy wants to use C properties in it, then it would depend on users having Cython 3.0 installed on their side and using it for their own code, because Cython 0.29.x would reject the properties as invalid syntax.

It's probably not easy for NumPy to force users into switching from Cython 0.29 to 3.0. I mean, it won't break much, but it's also not all free for much of the existing code out there, I would guess.

Cython 3.0 will be released later this year (if nothing really bad gets in the way), but users may still continue using the 0.29 series for a while (or even older versions), until they notice how cool Cython 3 is. :)

I guess it's up to NumPy then to decide when to start pushing their users.

**Comment by scoder** [comment]
Yet another thought – we could allow a Cython version marker in `.pxd` files that would let older Cython versions ignore them (once we ship the versioning support as a feature in 0.29).

Seems like a good idea in any case.

**Comment by da-woods** [comment]
I was wondering about something like `filename.cython-30.pxd`. i.e. kind of what CPython does with .pyc and .so files.

**Comment by scoder** [comment]
Yes, that's a good idea. Also, having to look _into_ the file in order to understand that it's not relevant is a lot of overhead that an extension could avoid.

**Comment by scoder** [comment]
> Numpy could use the weaker earlier version of C properties

The problem is that C properties are implemented in Cython 3.0, not in NumPy. Cython 0.29.x and earlier will reject them as an error. Thus, the different .pxd file versions, where different Cython versions would then pick up their right one.

**Comment by da-woods** [comment]
> The problem is that C properties are implemented in Cython 3.0, not in NumPy. Cython 0.29.x and earlier will reject them as an error.

OK. I'd thought the "just pick out the name of the first function call" version was in 0.29, but it looks like I was wrong about that.

**Comment by scoder** [comment]
Versioned pxd files are implemented in #3577.

**Comment by scoder** [comment]
Ok, anything else to be done?

I think the pxd-versioning should allow NumPy to start shipping and using the properties from day one, without creating hard dependencies. The only difference between the two versions (Cython/NumPy) that I'm aware of is that the properties in Cython are read-only, whereas the struct fields are writable. The rest should be the same now (AFAICT).

@mattip, do you see anything else that we could do?

**Comment by mattip** [comment]
LGTM, thanks, although I am not sure how the versioning should be factored into our workflow.

**Comment by da-woods** [comment]
I think the idea is: if/when Numpy decides to use the `@property cdef` accessors rather than calling accessing the struct directly then this will only work with Cython 3.0+. In that case Numpy should call its file __init__.cython-30.pxd so that the file is only found by Cython 3.0+.

Cython 0.29.x will continue to work because it has its own numpy pxd files.

If Numpy doesn't want to use `@property cdef` accessors then it doesn't need to change anything.

**Comment by mattip** [comment]
Numpy released versioned pxd files in the latest 1.19.2 release. Thanks for the extensive help with that. 

Before closing this issue, will the next 3.0 release sync with the latest version? I noticed the 3.0a6 release is missing `check_size ignore` in `ctypedef extern class numpy.ufunc`. That somehow slipped by in the 0.29 releases, which caused the warning to be emitted, see [this comment](https://github.com/numpy/numpy/pull/432#issuecomment-689846159). 

Probably can be traced back to me, sorry, which is surprising since the motivation for adding the `check_size` feature was `numpy.ufunc` in the first place :(

**Comment by jbrockmendel** [comment]
xref #3825 porting a recent edit in numpy's pxd file here

**Comment by jakirkham** [comment]
Is there anything still to do here?

**Comment by mattip** [comment]
At some point it would be nice to drop the Cython versions of NumPy `pxd` files and use the files provided by NumPy.

Numpy has had its own usable `pxd` files (including versioning for Cython3) since the 1.19.2 release. But that is not old enough: python3.8 is pinned to NumPy 1.17 in the [oldest-supported-numy](https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg#L49) repo. Even though python3.8 will be dropped from [NumPy support on April 14, 2023](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), it still will not be [EOL until ~October 2024](https://peps.python.org/pep-0569/#lifespan).

**Comment by jakirkham** [comment]
Since the status here was last discussed...

* Python 3.8 reached EOL
* Cython's main NumPy bindings were dropped: https://github.com/cython/cython/pull/5842
* Cython 3.0 came out (including the aforementioned removal)
* Some work began on removing the remaining vestiges
  * https://github.com/cython/cython/pull/5967
  * https://github.com/cython/cython/pull/6075

Anything else that still needs tracking here?

**Comment by scoder** [comment]
> * Cython 3.0 came out (including the aforementioned removal)

Not quite. The removal is scheduled for Cython 3.1.

I've created https://github.com/cython/cython/issues/6449 to track the remaining deprecation (and removal) of `numpy/math.pxd`. I think we can close this ticket now.

**Comment by jakirkham** [comment]
Ah should have been looking at the `3.0.x` branch instead of `main`
