### ISSUE TITLE
Pure python mode for C++ collections

### ISSUE THREAD

**Issue by matjazmav** [cython/cython#3610]
Is it possible to use pure python mode to use C++ collections (for example `vector`)?

**Comment by scoder** [comment]
Not currently. This is difficult, because there is no Python representation of them that Python could use when the code is not compiled. Could you explain what your use case is?

A pretty good Python replacement for `vector` is Python's `array` module, BTW. You can use memoryviews with them as well.

This seems somewhat related to #3416.

**Comment by da-woods** [comment]
Presumably the [augmented pxd](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#augmenting-pxd) approach would work for things like class members/function arguments? And you [might now](https://github.com/cython/cython/pull/3507) be able to do something with a typedef in the augmented pxd and then an alternative `if not cython.compiled: vector_int = list` that you could use in decorators or annotations

It's difficult to see how this would really work though.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/1489b16a2d2b67eed47d085f2a11840fb8527453 (mostly)

**Comment by 0dminnimda** [comment]
> This is difficult, because there is no Python representation of them that Python could use when the code

the other idea is to not rely on alternatives that python might serve, but to wrap `vector` with `extern` + python class for handling `PyObjects` and maybe some special explicit transformations, and then deliver its compiled version as part of cython package that could be accessed in pure python

**Comment by 0dminnimda** [comment]
if someone will write this then they should consider python typing system, while all elements of vector will be `PyObject` we should allow only one declared type (for simplicity, we may omit possibility to use inherited types).
That's al should be done to match real behavior of vector, and not introduce wrong behavior (tho if the goal is to compile, we may shouldn't care, because wrong behavior will be cathead by compiler)

**Comment by 0dminnimda** [comment]
and we probably can be ok with all that slowdown while translating `PyObjects` to C types, because pure python scripts (i think) usually used as fallback if compiled version is not working.

**Comment by 0dminnimda** [comment]
@scoder what do you think about [it](https://github.com/cython/cython/issues/3610#issuecomment-882122274)?

**Comment by scoder** [comment]
> > This is difficult, because there is no Python representation of them that Python could use when the code
> 
> the other idea is to not rely on alternatives that python might serve, but to wrap `vector` with `extern` + python class for handling `PyObjects` and maybe some special explicit type transformations / behavior handling, and then deliver its compiled version as part of `cython` package that could be accessed in pure python

Not sure if that's really worth the effort. I anyone wants to implement a Python shim for this, fine, sure. But I'd rather base this on a Python list or deque than C++ vector. I don't see an advantage of complicating such an implementation by moving back and forth between `object` and `PyObject*`.
