### ISSUE TITLE
gil is required to iterate over unicode

### ISSUE THREAD

**Issue by Berserker66** [cython/cython#3729]
```
    cdef char letter
    cdef unicode key
    for letter in key:
        pass
```
`Calling gil-requiring function not allowed without gil`

it should be possible to iterate over borrowed references of a unicode string in C chars, right?
In my case a c++ string would be sufficient, as the data is guarenteed to be alphanumerical

**Comment by scoder** [comment]
> it should be possible to iterate over borrowed references of a unicode string in C chars, right?

Getting at the Unicode character buffer is not necessarily possible/valid without holding the GIL.

**Comment by Berserker66** [comment]
Any particular reason why? isn't it already mapped continous memory that could be read from?

**Comment by scoder** [comment]
The memory is not the problem. Asking the CPython API for the pointer to the memory might be. In the worst (although unlikely) case that the Unicode string isn't fully initialised yet (e.g. because it came from the Win32 or `wstr` API), it can even trigger a data conversion, which definitely requires the GIL.

**Comment by Berserker66** [comment]
Ah. unfortunate. Well, since ascii is sufficient for my case I guess I'll just map the unicode with gil into a char* array and use that later without gil. Thanks for clarifying.
