### ISSUE TITLE
ENH: cpython.time to expose stdlib time.localtime etc

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#3733]
There is a `libc.time` available from which I _think_ I can patch together something equivalent to https://github.com/python/cpython/blob/master/Modules/timemodule.c#L490, but itd be nice to have a canonical version exposed directly.

**Comment by scoder** [comment]
Probably not a complete replacement, given that CPython's `time` module provides different timer sources. But a simple look-alike seems like a nice idea.

**Comment by jbrockmendel** [comment]
I'll see if that patching-together approach works out.  Are the `libc` cimports reliable cross-platform?

**Comment by scoder** [comment]
>  Are the libc cimports reliable cross-platform?

Most, but not all of them. We have more in the Cython declarations than are strictly portable, because it doesn't hurt to have them there. They only appear in C code when users make actual use of them, so it's their choice. It may be obvious for some of the declared functionality, but in the end, you better look it up.

**Comment by scoder** [comment]
Apparently, some struct fields are platform specific. I get this on Windows:
```
time_pxd.c(5597): error C2039: 'tm_zone': is not a member of 'tm'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_wtime.h(23): note: see declaration of 'tm'
time_pxd.c(5600): error C2039: 'tm_gmtoff': is not a member of 'tm'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_wtime.h(23): note: see declaration of 'tm'
```
This comes from the struct-to-dict conversion of `tm`, which tries to copy all fields. There isn't currently a mechanism to say "copy this field only if it exists on this platform".

**Comment by da-woods** [comment]
It looks like they `tm_zone` and `tm_gmtoff` probably just shouldn't be in https://github.com/cython/cython/blob/master/Cython/Includes/libc/time.pxd since they aren't part of the C standard

**Comment by da-woods** [comment]
Maybe the thing to do is define `tm` in the .pxd file with only the standard fields, and `gnu_tm` (or some similar name) with a c-name of `tm` with the extended list of fields? It might break some existing code, but not in a way that's too hard to fix?

**Comment by scoder** [comment]
Yeah, [apparently](https://stackoverflow.com/questions/58443953/does-struct-tm-store-time-zone-information-as-its-data-member), it's a GNU specific extension. The usual way we deal with those is to add them to the struct if it's reasonable, because it doesn't normally hurt to let Cython think they are there as long as users don't write time into their code. But struct-dict conversion makes this … annoying.

In this case, I would remove the fields. We can add them in some other .pxd file if someone wants them. Does that sound reasonable?

**Comment by scoder** [comment]
Closing again with 1a6bba9.

**Comment by da-woods** [comment]
> There isn't currently a mechanism to say "copy this field only if it exists on this platform".

It would be possible to implement this mechanism in the struct-to-dict converter functions in C++11. I'm not really convinced it's a good idea to have the behaviour vary so much depending on the compiler, but it could be done if there was a real use for it.
