### ISSUE TITLE
Incorrect return type assumed for "repr()" builtin function with "language_level=3"

### ISSUE THREAD

**Issue by LordAro** [cython/cython#3736]
Cython version 0.29.21

```python
def f() -> str:
    return repr('')
```
with `cython -3 -o foo.c foo.py`
results in an error:

```
Error compiling Cython file:
------------------------------------------------------------
...
def f() -> str:
    return repr('')
              ^
------------------------------------------------------------

foo.py:2:15: str objects do not support coercion to unicode, use a unicode string literal instead (u'')
```

As far as I'm aware, repr() returns a string, so there shouldn't be any issue here? Wrapping it `str(repr(''))` works fine.

**Comment by LordAro** [comment]
Doesn't have an issue with it when using `-2` either

**Comment by scoder** [comment]
Thanks for the report. The return type of `repr()` was declared as `str`, which is technically correct, but then wasn't adapted to `language_level=3`, where it should have been `unicode`.

I've removed the return type declaration so that it now returns `object`. That's less helpful but prevents failures like in your example.
