### ISSUE TITLE
Requesting Cython `intern` `str`s

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3823]
The usual mechanism of calling `intern` (now `sys.intern`) on `str`s seems to work fine. Though it looks like Cython has a [mechanism to `intern` constant `str`s globally]( https://github.com/cython/cython/blob/9c26b302791515f608d4b200f692dcec9f066229/Cython/Utility/ModuleSetupCode.c#L1130-L1131 ). What's less clear (at least to me) is how one can tell Cython to mark `str`s in this table to be `intern`ed. Is there a way to do this?

**Comment by da-woods** [comment]
@jakirkham For a user it should happen automatically any time you create a string constant in your code (so there's no extra mechanism to control it). If you have something that should be interned but isn't then report it I think

For a developer writing utility code for use internally in Cython you can use `PYIDENT("contents of string")` or `PYUNICODE("contents of string")`. But this isn't exposed to users (and shouldn't be too)

**Comment by da-woods** [comment]
I'll close this because I don't think it makes sense as a feature request: Cython does this automatically for most string constants and keeps a handle to the string constants so it can generate new references to them quickly. For anything that you want to intern that Cython's somehow missed you can use the normal Python intern mechanism (but obviously won't get the advantage of Cython being able to look it up quickly pretty much by definition).

The only place we could add an element of user control is in choosing when to expand string arithmetic. Somewhere between `'abc'*1000000` and `'abc'*2` Cython decides not to expand the string into a single constant to avoid caching massive amount of memory. I'm not sure that's a common enough concern to justify adding new compiler directives.
