### ISSUE TITLE
[BUG] Bad reference counting when assigning a memory view to itself

### ISSUE THREAD

**Issue by jmd-dk** [cython/cython#3827]
**Describe the bug**
The code generated when assigning a memory view `a` to itself,  `a = a`, does not function correctly with regards to reference counting. When doing this outside of a function, an `UnboundLocalError` is raised the next time `a` is used. When doing this inside a function, a segfault occurs.

**To Reproduce**
```cython
import numpy as np

cdef int[::1] a
a = np.zeros(1, dtype=np.intc)
print('before bad assignment:', a[0])
a = a
print('after bad assignment:', a[0])
```

**Expected behavior**
The above should of course print
```
before bad assignment: 0
after bad assignment: 0
```
In actuality only the first line is written, as the code fails on the last `a[0]` lookup. When doing this outside of a function, we get
```
UnboundLocalError: local variable 'a' referenced before assignment
```

**Environment**
 - OS: Linux Mint 19.3
 - Python version: 3.8.2
 - Cython version: 0.29.16

**Additional context**
Looking at the generated C code, the problematic `a = a` statement turns into
```C
__PYX_XDEC_MEMVIEW(&__pyx_v_a, 1);
__PYX_INC_MEMVIEW(&__pyx_v_a, 0);
__pyx_v_a = __pyx_v_a;
```
I'm not familiar with the details of `__PYX_XDEC_MEMVIEW` and `__PYX_INC_MEMVIEW`, but I presume they decrement and increment the reference count of `__pyx_v_a` (i.e. `a`). Removing these two lines and keeping only the bottom one fixes the issue.

One can of course just as well remove all three lines, since `__pyx_v_a = __pyx_v_a` is guaranteed to be a no-op (it will be optimized away by the C compiler anyway).

**Comment by scoder** [comment]
Thanks for the report. Indeed, this looks wrong. It should incref _before_ the decref in an assignment, for exacly this reason. Probably easy to fix, just an ordering in the code generation of the assignment (`SingleAssignmentNode` in `Nodes.py`). PR welcome. Tests go into `tests/memoryview/memslice.pyx`, somewhere near the top (since it's pretty basic).

> When doing this outside of a function, we get `UnboundLocalError`

That seems surprising. There are no local variables outside of a function. Are you saying that this is the result of the module level code that you show above?

> One can of course just as well remove all three lines

Sure, but it's not worth doing in Cython, because a) no real code would benefit from it and b), as you wrote:

> it will be optimized away by the C compiler anyway

**Comment by da-woods** [comment]
> It should incref _before_ the decref in an assignment, for exacly this reason

I tried this patch yesterday and it didn't fix it... At that point I got a bit stuck. But I don't think it's quite as simple as it looks.

> That seems surprising. There are no local variables outside of a function. Are you saying that this is the result of the module level code that you show above?

This was my result too - `UnboundLocalError` when the code is run at module scope, segmentation fault inside a function.

**Comment by jmd-dk** [comment]
> [`UnboundLocalError`] Are you saying that this is the result of the module level code that you show above?

Surprisingly, yes. One does not get a `NameError`. Checking the generated code, we indeed see
```cython
if (unlikely(!__pyx_v_3bug_a.memview)) { __Pyx_RaiseUnboundLocalError("a"); __PYX_ERR(0, 6, __pyx_L1_error) }
```
when my sample code is placed at the module level. When inside a function, no `__Pyx_RaiseUnboundLocalError("a")` is generated, leading to the segfault instead.

As @da-woods writes, placing the `__PYX_INC_MEMVIEW` before the `__PYX_XDEC_MEMVIEW` does not solve the issue.

**Comment by da-woods** [comment]
I think the issue is that `__Pyx_XDEC_MEMVIEW` is actually misnamed a bit and really acts more like `Py_CLEAR`. That probably also explains why I wasn't able to get memoryviews under quite the same reference counting scheme as PyObjects.

For the sake of this bug I think we either have to identify that the two sides have the same cname and not generate the code, or we have to juggle temps like `Py_DECREF_SET`.

I wonder if the naming should be changed to match what it actually does though.
