### ISSUE TITLE
[BUG] tuple of memoryviews returned from function cannot be used for memoryview assignment

### ISSUE THREAD

**Issue by dovahcrow** [cython/cython#3897]
**Describe the bug**
Assigning a memoryview to another larger memoryview using the slice assignment is not working. 

The error is
> TypeError: must be real number, not _cython_magic_759518cb32a273d72dde521fde376d31._me

I think the error is truncated and the rest piece of the characters should be "moryview..."

**To Reproduce**
Code to reproduce the behaviour:
```cython
cimport numpy as np
import numpy as np

def bug():
    cdef:
        np.float64_t[:,:] r = np.zeros((2,10), dtype=np.float64)
    
    ret = a()
    r[0] = ret[0]
    
    return r.base
    
cdef tuple a():
    cdef:
        np.float64_t[:] buf1 = np.arange(10, dtype=np.float64)
        np.float64_t[:] buf2 = np.arange(10, dtype=np.float64)
        
    return buf1, buf2
```

Using c++ pair is not working either.

```cython

# distutils: language = c++

cimport numpy as np
import numpy as np
from libcpp.utility cimport pair

def bug():
    cdef:
        np.float64_t[:,:] r = np.zeros((2,10), dtype=np.float64)
    
    ret = a()
    r[0] = ret.first
    
    return r.base
    
cdef pair[np.float64_t[:],np.float64_t[:]] a():
    cdef:
        np.float64_t[:] buf1 = np.arange(10, dtype=np.float64)
        np.float64_t[:] buf2 = np.arange(10, dtype=np.float64)
        
    return buf1, buf2
```

This crashes the python interpreter.

**Expected behavior**
no error happens.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.8.6
 - Cython version: 0.29.21

**Additional context**

**Comment by da-woods** [comment]
This is behaving correctly. Memoryview indexing is intentionally pretty limited - it can only deal with single values on the right-hand side and doesn't attempt to handle slice copies.

Therefore:

    r[0] = 0  # fine
    r[0] = ret[0]  # won't work

You need to copy the contents of `ret[0]` manually (i.e. in a loop). The problem is with the assignment, not with returning memoryviews as a tuple.

-------

Putting memoryviews inside a `std::pair` definitely won't work. Memoryviews need some reference counting and as soon as they're in a C++ container Cython can't track that.

**Comment by scoder** [comment]
Doesn't `r[0][:] = ret[0]` or `r[0, :] = ret[0]` work? Like NumPy arrays, memory views use broadcasting on slice assignments. That's now what you want here.

However, I would rather pass the output view(s) into the function (e.g. `a(r[0], r[1])`) and write into them directly, rather than returning newly created arrays and copying the results over afterwards.

**Comment by dovahcrow** [comment]
@scoder @da-woods Thanks for your replies! Now I understand why `std::pair` won't work. 
@scoder great suggestion! I definitely should try this.

**Comment by dovahcrow** [comment]
@scoder No. Neither `r[0][:] = ret[0]` nor `r[0, :] = ret[0]` worked.
By compiling with cython -a, I got this.
![image](https://user-images.githubusercontent.com/998606/98323660-2969e900-1f9f-11eb-8ab3-a32594baff04.png)

I suspect the error comes from this line

```c
__pyx_t_6 = __pyx_PyFloat_AsDouble(__pyx_t_4)
```
where Cython tries to convert a memoryview into double.

**Comment by da-woods** [comment]
I don't think memoryviews have ever done slice-to-slice assignments. They've only done "fill a slice with a single value" assignment (which is what's happening here)

**Comment by dovahcrow** [comment]
@da-woods yes you are right. Assigning `ret[0]` to a `cdef np.float64_t[:] mview` and then slice assign `r[0,:] = mview` works. However, `r[0,:] = <np.float64_t[:]>ret[0]` won't work with error `Can only create cython.array from pointer or array`.
