### ISSUE TITLE
[ENH] CPython 3.9 Windows and macOS wheels

### ISSUE THREAD

**Issue by domdfcoding** [cython/cython#3916]
Would it be possible to have Python 3.9 wheels for Windows and macOS too?

Related to #3868:

> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. In my code, I would like to do [...]
> 
> ```
> $ python3.9 -m pip install cython
> ```
> 
> I'd like this to be super fast.
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen, including code examples if applicable.
> 
> I'd like pip to install Cython wheels with Python 3.9.
> 
> **Describe alternatives you've considered**
> 
> It is possible to install Cython with `--install-option="--no-cython-compile"`, but that doesn't work in situations where Cython is a dependency.

Thanks

**Comment by scoder** [comment]
It doesn't really make much of a difference, but yes, I'll upload them when I get to it. Definitely for the next 3.0 release.
(Note that binary wheels are not necessarily faster for one-shot installations, unless they are already cached locally, because the binary wheels are larger and may thus in fact take longer to download than to install and run.)

**Comment by johnthagen** [comment]
Just as a note, as of `3.0.6a6` these are still not included: https://pypi.org/project/Cython/3.0a6/#files

Wasn't sure how close the final release was.
