### ISSUE TITLE
Order of destruction/finalization of cdef class attributes

### ISSUE THREAD

**Issue by shwina** [cython/cython#3946]
I am writing a `cdef class` whose attributes need to be deallocated in a specific order. It would be very helpful if you could help answer the following questions (even if the answer is just "that's not defined!" 😄)

* When an instance of a `cdef class` is deallocated, are its attributes destroyed/finalized in a specific order?
* When is `__dealloc__` called in relation to attribute destruction? (before or after?)

In the example below, I wrote a `cdef class Baz` with two C++ attributes and two Python attributes. These were my observations about its destruction behaviour:

1. First, the `__dealloc__` method of the cdef class is invoked.
2. Next, any destructors of C++ attributes are (manually) invoked _in the order they are declared_.
3. Next, `Py_CLEAR()` is invoked on Python attributes _in the order they are declared_.

Does the above sound accurate? Is any of this behaviour guaranteed by Cython?

## Example

```cython
# foo.pyx

cdef extern from *:
    """
    #include <iostream>
    #include <string>

    class Foo {
       public:
        Foo() = default;
        Foo(std::string name): name(name){}
        ~Foo() {
            std::cout << name << std::endl;
         }
       private:
         std::string name;
    };
    """
    cdef cppclass Foo:
        Foo() except +
        Foo(string name) except +

class Bar:
    def __init__(self, name):
        self.name = name

    def __del__(self):
        print(self.name)

cdef class Baz:
    cdef object one
    cdef Foo two
    cdef object three
    cdef Foo four

    def __cinit__(self):
        self.one = Bar("one")
        self.two = Foo("two")
        self.three = Bar("three")
        self.four = Foo("four")

    def __dealloc__(self):
        print("__dealloc__")
```

```python
In [1]: from foo import Baz

In [2]: x = Baz()
two
four
four

In [3]: del x
__dealloc__
two
four
one
three
```

**Comment by da-woods** [comment]
We usually try to direct support questions to the cython-users mailing list rather than the bug/issue tracker.

With that said - `__dealloc__` before the C attributes are destroyed is definitely defined, since `__dealloc__` is designed to allow you to clean up C/C++ level attributes. Python objects can end up cleared early by the GC if they form reference cycles so you shouldn't rely on them being available in `__dealloc__` (see http://docs.cython.org/en/latest/src/userguide/extension_types.html#disabling-cycle-breaking-tp-clear). C++ objects in order of definition sounds plausible but I wouldn't rely on it - if you care about the order then you should be enforcing it manually.
