### ISSUE TITLE
PyLong_AsLongLongAndOverflow not exposed

### ISSUE THREAD

**Issue by dvarrazzo** [cython/cython#3980]
Why functions such as `PyLong_AsLongLongAndOverflow` not exposed?

https://github.com/cython/cython/blob/30fc474830b4a5beb88cdc53a31797ed794cddb8/Cython/Includes/cpython/long.pxd#L92

I'm playing with them and they seem working ok.

**Comment by da-woods** [comment]
This is the pull request they came from https://github.com/cython/cython/pull/1661

According to the author:

> Functions that are not supported by all versions that cython supports are commented but also included.

I think they should be uncommented though - it doesn't do any harm to expose functions that aren't supported on every version since no C code is generated for them unless the user uses them.. So I'm sure a PR doing that would be welcome.

**Comment by dvarrazzo** [comment]
I assume Python 2.7 is now supported by all Cython versions, right?

About to submit a MR, thank you.
