### ISSUE TITLE
Switch readthedocs to show stable branch by default

### ISSUE THREAD

**Issue by itamarst** [cython/cython#4010]
Right now https://cython.readthedocs.io shows documentation for the "latest" version of the code, which is apparently an alpha? You can configure the project to show "stable" docs by default, and that way users will see the documentation for latest stable release automatically. It's in the settings somewhere, you can set what branch to identifier to show by default, and "stable" is one of the options.

**Comment by scoder** [comment]
The `stable` docs don't seem very up to date, but yeah, I'd like to have it show both. Not necessarily `stable` by default in the current state, since people should rather use 3.0 than 0.29.x. The reason why 3.0 is marked as alpha is that it's not feature complete yet, not that it's necessarily unstable.

**Comment by leofang** [comment]
Would be great to show both indeed.

**Comment by matusvalo** [comment]
@da-woods  can we close this issue since https://github.com/cython/cython/pull/4583 is merged?
