### ISSUE TITLE
[BUG] Cython 0.29.22 with Jupyter Notebook --name fails to compile

### ISSUE THREAD

**Issue by danielhanchen** [cython/cython#4033]
After upgrading from 0.29.21 to 0.29.22 on a Windows 10 machine with GCC 9.2 [MingW],
Cython fails to compile a Jupyter Notebook snippet with the --name / -n tag ie:
```
%%cython --force --name Compiled_Name
# cython: c_string_type=unicode, c_string_encoding=utf8
# distutils: language = c++
# distutils: extra_compile_args = -O0 -pipe -std=c++2a -fopenmp
# distutils: include_dirs = .
# distutils: extra_link_args = -fopenmp -fstack-protector
```

However, when removing the --name tag, everything works fine.

The fail message includes GCC ignoring `#pragma omp ***`, and saying how `std::filesystem` is not linked properly.

I downgraded back to 0.29.21, and everything works fine.

**Comment by da-woods** [comment]
At least on Linux+Python 3.8 I can't reproduce this based on the short example you posted here. However I suspect the problem is Windows specific.

The full error message would probably be helpful - not just your summary of it.

I'm not 100% sure what the status of Windows+MingW is - my impression is that it doesn't work on any modern version of Python (because the C standard library doesn't match the one that Python was built with), however it's been a long time since I tried it personally.

**Comment by danielhanchen** [comment]
Oh lolll don't worry about it anymore.
Weirdly I forgot the good ol Windows fix - Restart it ....

It seems to work again with 0 errors.

Oh I use https://nuwen.net/mingw.html GCC 9.2, and just follow the formal Cython Distutils procedure [ie set compiler = mingw]. Sadly Conda's version of MingW is outdated (GCC 5 or something).
