### ISSUE TITLE
[ENH] Customize location of .so file generated by Cython

### ISSUE THREAD

**Issue by xuliang-st** [cython/cython#4262]
I was wondering if there's a way in which setup.py could create the .so file in the desired place by itself without manually copying and pasting it in the location.

**Comment by scoder** [comment]
This seems more a question about distutils/setuptools and not Cython.
Closing as "support question" (for which we have the cython-users mailing list) and otherwise not a Cython issue.

When you ask in other places, I suggest adding a more detailed description of what you want to achieve, peferrably giving an example. What is your "desired place" ? Is that inside or outside of your project tree? Are you asking for a dedicated build directory or something else? Did you run "setup.py --help" to find out the available options? Does "setup.py build_ext -i" do what you want, or do you want something else? That's not clear to me from what you write.
