### ISSUE TITLE
[BUG] Core dump occurs in code compiled using 3.0a6.

### ISSUE THREAD

**Issue by xuliang-st** [cython/cython#4263]
**Describe the bug**
Core dump occurs in code compiled using 3.0a6.
![image](https://user-images.githubusercontent.com/81795429/124347165-b0965c00-dc15-11eb-909c-92d608c91441.png)
model_infer_api and logger It's my .so file.When import gevent and my .so files,A coredump is generated.
![image](https://user-images.githubusercontent.com/81795429/124347285-65307d80-dc16-11eb-96d0-457a7e7e7431.png)

**Environment (please complete the following information):**
 - OS:  Linux-Ubuntu
 - Python version [3.7.5]
 - Cython version [3.0a6]

**Comment by da-woods** [comment]
The problem is likely with your file (which you don't show) - I doubt the import alone is enough to cause a segmentation fault.

In order for anyone to help you, you need to provide enough information to reproduce it (edit this post and I'll reopen it).

Most likely the error is in your code and it is not a Cython bug. In this case you would be better asking on the cython-users mailing list instead

**Comment by xuliang-st** [comment]
> The problem is likely with your file (which you don't show) - I doubt the import alone is enough to cause a segmentation fault.
> 
> In order for anyone to help you, you need to provide enough information to reproduce it (edit this post and I'll reopen it).
> 
> Most likely the error is in your code and it is not a Cython bug. In this case you would be better asking on the cython-users mailing list instead


It's not the problem with my files. I tried compiling with 3.0.0a8 and there was no segmentation fault.

**Comment by scoder** [comment]
> I tried compiling with 3.0.0a8 and there was no segmentation fault.

Thanks for testing that. And happy that it's fixed in the latest release.

**Comment by xuliang-yyds** [comment]
> Thanks for testing that. And happy that it's fixed in the latest release.

I want to know what causes the coredump?I tried to debug it to no avail.I hope to have your help.Thanks ~

**Comment by xuliang-yyds** [comment]
Excuse me, which tag‘s cython version is the official version and which is the alpha version?

**Comment by da-woods** [comment]
> I want to know what causes the coredump?I tried to debug it to no avail.I hope to have your help.Thanks ~

You can run it in the debugger. Compile your module with `CFLAGS=-Og python setup.py...` and then run `gdb python` followed by `run service/main.py`

It will end up stepping through the C code so it may be tricky to follow, but that's how I'd find the bug.

Otherwise keep removing lines from your file until you find the one that makes it crash.

> Excuse me, which tag‘s cython version is the official version and which is the alpha version?

3.0.0a8 is the current alpha release leading to v3.0.0. 0.29.24 is the current non-alpha version.
