### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dequeb** [cython/cython#4269]
I'm using python 3.9 to compile a simple Qt6 "Hello World" application in Cython and py2app. It works perfectly fine under CPython 3.9. It compiles properly but fails to run in Cython and p2app.

Here are the project files:

**testLoad.pyx**:
```
import sys
from PyQt6.QtWidgets import QMessageBox, QApplication

def main():
    app = QApplication(sys.argv)
    QMessageBox(text="Hello World").exec()

if __name__ == "__main__":
    main()
```
***main.py***:

```
import testLoad
from logging import basicConfig

def main():
    testLoad.main()

if __name__ == '__main__':
    main()
```

and **setup.py**:

```
""""
Usage:
    python setup.py py2app
"""

from setuptools import setup
from Cython.Build import cythonize
from Cython.Distutils import build_ext


setup(
    name='test',
    # Include additional files into the package using MANIFEST.in
    include_package_data=True,
    app= ['__main__.py'],
    data_files=[],
    cmdclass = {'build_ext': build_ext},
    ext_modules = cythonize(["testLoad.pyx"], language_level=3),

    setup_requires=['py2app'],
    options={
             'cython': {"language_level":"3"}
            },
    install_requires=[
        "Cython"
    ],
    entry_points={
        "console_scripts": [
            "testLoad = __main__:main"
        ]
    },
)
```

When I run the program, I get this error on the console:

```
erreur  17:04:44.035551-0400    test    MTLIOAccelDevice bad MetalPluginClassName property (null)
erreur  17:04:44.047081-0400    test    +[MTLIOAccelDevice registerDevices]: Zero Metal services found
```

**Environment:**
 - macOS 11.4
 - Python version 3.9
 - Cython version:  0.29.23

**Comment by dequeb** [comment]
see also related issue on p2app at: https://github.com/ronaldoussoren/py2app/issues/359

**Comment by scoder** [comment]
I have no idea how py2app works, but this sounds like something to discuss on a mailing list first. Very few people read bug tracker issues, so you're unlikely to get helpful advice here. Try a broader forum like the python-list mailing list or something that's more focussed on py2app specific issues.

If it turns out that it's really something specific to Cython generated modules (and not, say, extension modules in general or some setuptools issue or whatever), then you can try the cython-users mailing list, which also has a relatively large audience.

**Comment by scoder** [comment]
BTW, did you try keeping the main module as a Python script and only importing a Cython compiled module from that?

**Comment by dequeb** [comment]
I did it and the issue is in the way py2app bundle the application. Close this request. I will do the follow up with py2app team.
