### ISSUE TITLE
[ENH] Allow compile-time conditionals

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4287]
**Is your feature request related to a problem? Please describe.**
Pure python version of
```cython
IF "there is a chance":
    from __future__ import braces
ELIF 6 + 9 + 6 * 9 != 69:
    wocky_slush = "yummy"
ELSE:
    print("delicious spam")
```

**Describe the solution you'd like**
Suggestions:
#### 1) `cython.X`
```python
if cython.conmpile_time(condition):
    ...
elif cython.conmpile_time(condition):
    ...
else:
    ...
```

#### 2) `with`
```python
with cython.conmpile_time:
    if condition:
        ...
    ...  # regular conditional syntax
```

#### 3) `with` + `cython.X`
Thought it looks quite ugly 
```python
with cython.IF(condition):
    ...
with cython.ELIF(condition):
    ...
with cython.ELSE:
    ...
```

#### 4) comment
```python
if condition:  # cython: compiled
    ...
elif condition:
    ...
else:
    ...
```

**Comment by scoder** [comment]
I never considered this a good feature to have. Many people misunderstand what it's good for, the syntax is everything but beautiful, and there are fairly few use cases, really. We should try to hard to get along without it.

**Comment by 0dminnimda** [comment]
> the syntax is everything but beautiful

probably, except for the comment. but the comment is not really Cython style I guess

**Comment by da-woods** [comment]
The trouble is you can't actually do a whole lot with these - you can get whether its Windows/Mac/Linux, and the Python version, but that's basically the only thing that you can make decisions on with `DEF` and `IF`. You can't use them to access C defines for example.

And they break the general rule that the .c file you generate should not depend on the system you run it on (because it's quite frequent to distribute Cython-generated .c files with pip).

Pretty much the only useful thing is to `DEF` a static array length, and that's rarely necessary.

**Comment by jbrockmendel** [comment]
the use cases that come to mind for this look a lot like the use cases for tempita

**Comment by robertwb** [comment]
As well as being *very* limited and somewhat ugly, these'd be hard to emulate in pure Python. E.g. imagine

```
a = "global value"
def foo():
  IF condition:
    a = "local value"
  print(a)
```

I agree that most usecase for these constructs would be better handled by code generation or a template engine (or just normal Python branching).

**Comment by 0dminnimda** [comment]
> I agree that most usecase for these constructs would be better handled by code generation or a template engine (or just normal Python branching).

well, most of the time I think pure python mode is used as a fallback when a compiled version is not available

> ```
> a = "global value"
> def foo():
>   IF condition:
>     a = "local value"
>   print(a)
> ```

Does it change if you use cython or pure python? These are just conditions that are simply executed at compile time, they should work exactly as well during interpretation, the interpreter will just waste time calculating them.

**Comment by scoder** [comment]
> > I agree that most usecase for these constructs would be better handled by code generation or a template engine (or just normal Python branching).
> 
> well, most of the time I think pure python mode is used as a fallback when a compiled version is not available

"Pure Python mode" should be the normal way to use Cython for many, if not most, people in the future. You should only resort to Cython specific constructs for use use cases where there's no other way. And whether there's no other way may also change in the future.


> > ```
> > a = "global value"
> > def foo():
> >   IF condition:
> >     a = "local value"
> >   print(a)
> > ```
> 
> Does it change if you use cython or pure python?

Yes. Cython evaluates the condition before looking at the declarations. If `condition` is true, `a` will become a local variable through the assignment. Otherwise, it will be the global variable. If the condition is evaluated at runtime (and, thus, in Python), it would always be the local variable.

**Comment by scoder** [comment]
In lack of a real use case, and noting that most people agree that there are better solutions for this, I'll close this ticket as "won't fix".

Please direct future discussions of this topic to the [cython-users](https://groups.google.com/d/forum/cython-users) mailing list first, where we can try to find alternatives for specific needs.

**Comment by scoder** [comment]
I created https://github.com/cython/cython/issues/4310 to discuss whether this feature can be deprecated and removed completely.

**Comment by jbrockmendel** [comment]
A use case that can be accomplished with tempita but can be made more pythonic is something like

```
cdef myfunc(foo, bar, bint condition):
    [...]

myfunc1 = cython.cpartial(myfunc, condition=True)
myfunc2 = cython.cpartial(myfunc, condition=False)
```

Purely speculative: cpartial might be implemented by shimming an `inline` into `myfunc` and then defining

```
cdef myfunc1(foo, bar):
     return myfunc(foo, bar, True)
```

and then the compiler might do the rest?
