### ISSUE TITLE
[BUG] PyCode_New and PyCode_NewWithPosOnlyArgs are going away in 3.11

### ISSUE THREAD

**Issue by gvanrossum** [cython/cython#4365]
See https://bugs.python.org/issue45122

The appropriate *internal* C API is _PyCode_New, which takes a struct containing various (sometimes optional) arguments. We will try not remove fields from the struct (but it *is* an internal API).

You might also want to see if PyCode_NewEmpty does what you want.

Stefan Behnel is aware of this.

**Comment by gvanrossum** [comment]
Update: It's probably better to use PyCode_NewEmpty followed by code.replace(): https://docs.python.org/dev/library/types.html#types.CodeType.replace

**Comment by scoder** [comment]
Turns out, the problem with `PyCode_NewEmpty()` is that it takes `char*` arguments, not Python strings…

**Comment by gvanrossum** [comment]
Do you need help finding a better way?

**Comment by da-woods** [comment]
If we were going down the `.replace` route (which is a Python call) then we could equally do a direct call to the `types.CodeType` constructor? They should have similar overhead, right?

I guess it is a de-optimization from what we have now, but it avoids the need to have a global code object that's then replaced repeatedly.

**Comment by scoder** [comment]
> If we were going down the `.replace` route (which is a Python call) then we could equally do a direct call to the `types.CodeType` constructor? They should have similar overhead, right?

Yeah, we could call `PyCode_Type` (or its `tp_new()`), but that would require passing almost all arguments into it, so we'd still depend on the exact signature (or at least the list of required arguments, if we pass keyword arguments as a dict).

`.replace()` is a somewhat simple vectorcall with only the keyword arguments that we really need. But it requires keyword arguments (although we can prepare the constant keyword name tuple) and Python object arguments, which slows things down. Probably not as much as calling the type with a full dict, though.

Since we're caching code objects, I think we can afford adding a bit of overhead to their creation. It slows down the module import a little bit, as well as first-time creations at need. Profiling [already uses](https://github.com/cython/cython/blob/aea4e6b84b38223c540266f8c57093ee2039f284/Cython/Utility/Profile.c#L310) `PyCode_NewEmpty()` and we might be able to tweak [traceback creation](https://github.com/cython/cython/blob/aea4e6b84b38223c540266f8c57093ee2039f284/Cython/Utility/Exceptions.c#L721) into using that, too, with a bit of code duplication for newer Python versions.

Although the fact that we currently pass the function name and file name as  a `char*` into both of these internally seems like completely unnecessary overhead here – we have the Unicode string lying around anyway. The only issue is injecting the C code line into the "function name", to show it in tracebacks. If that's disabled, then `PyCode_NewEmpty()` would work there, as it currently stands, but would no longer work for us the next time we optimise the traceback creation overhead. (There's code out there that uses exceptions extensively and not just for exceptional cases.) Function object creation uses the constant Unicode string objects.

So, it's either slow, Python-level keyword arguments (calling `PyCode_Type` or `.replace()`), or fast, version specific C code (calling `_PyCode_New()`). Sounds like a familiar tradeoff. :)

The usual way to deal with this in Cython is to implement both and add a feature switch that different Python implementations and users can enable or disable. I'll see what I can come up with.

**Comment by da-woods** [comment]
> > That's too bad. With the new struct initializations it's actually more
> > usable and more stable going forward.
> 
> Why not move Cython to generate C99 code?

Assuming you mean the "designated initializer" syntax (e.g. `S s = { .filename = "a.txt", .some_number = 5 };`) that's a c++ problem. It's only just been introduced in C++20, and in a fairly cut-down form. So even if we wanted to generate C99 code, it'd need to be in the overlap between C and C++.

**Comment by scoder** [comment]
>Why not move Cython to generate C99 code? It's been over 20 years....
>Also, 3.0.0 would be a great time for such a change, I'd say.

That's for Cython 3.1, which will remove support for Python 2.7 and its requirement for ancient msvc versions.

**Comment by gvanrossum** [comment]
Can you please follow up on the cpython tracker with an explanation of what you need from us?

**Comment by ericsnowcurrently** [comment]
(repeat of question in [#4414](https://github.com/cython/cython/pull/4414#issuecomment-966579444))

Will this also be fixed for `0.29.x`?  I can help if needed.

**Comment by markshannon** [comment]
OOI, why does Cython need to create code objects at all?

**Comment by TeamSpen210** [comment]
There's two uses. First, they're generated in order to be able to inject fake traceback frames, so you'll get the `pyx`'s filename and line number showing up. That could be replaced by an official method of doing that sort of thing. Secondly, Cython optionally (and soon by default) produces a custom type for its functions, which emulates as many attributes as possible of pure-Python functions including`__code__` - arg counts, variable names, etc. That way code introspecting sees as little difference as possible. In both cases `co_code` and several other fields are blank, they're not actually executable ever.

**Comment by da-woods** [comment]
They are also used in line-tracing profiling.

Both the traceback and the linetracing could both easily use `PyCode_NewEmpty` without losing anything, although tracebacks are currently implemented with `PyCode_NewWithPosOnlyArgs` (or it's dubious 3.11 substitute workaround).

The "introspection" code objects attached to cython functions do set as many attributes as possible. But I don't think they're absolutely _needed_.

**Comment by markshannon** [comment]
If you could come up with an API that expresses what you need, that would be a big help. 
Just a back-of-an-envelope sort of thing, don't be too precise for now.

**Comment by minrk** [comment]
> Closing this by merging #4414. I'm sure there will eventually be a better way to do this, but for now, and for the time being, it doesn't fail to compile any more.

Since the PR comment had `and #4365` instead of `and fixes #4365` this wasn't auto-closed by #4414, though it looks like it was meant to.
