### ISSUE TITLE
[ENH] Include statement in class body

### ISSUE THREAD

**Issue by gentlegiantJGC** [cython/cython#4437]
**Is your feature request related to a problem? Please describe.**
I have a problem that I have outlined in the mailing list (linked below) that would be greatly simplified if I could use the include statement within the body of a class.
https://groups.google.com/g/cython-users/c/FJzP0x9DTPM
The docs say that the include statement "cannot ... be used outside of the module scope, such as inside ... class bodies."
https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#the-include-statement-and-include-files
The compiler throws an error as is expected.

What is the reasoning behind this?

I have tried modifying the code to allow it to work within class bodies and in the cases I have tested it it seems to work just fine.
The modification is to add "c_class" to the tuple on this line
https://github.com/cython/cython/blob/719553db360261c082386cc2a81d5937861a6990/Cython/Compiler/Parsing.py#L2340

**Describe the solution you'd like**
I would like to know the reasoning why the include statement is not allowed in a class. The docs say it isn't but don't explain why it isn't.
If there is a reason why it isn't it would be great if there was a way to monkey patch just that tuple rather than the whole function since it works in the case I need it in.

**Describe alternatives you've considered**
The only alternative to the problem outlined above is to manually copy the code (50-100 lines) about 12 times which will become problematic to maintain.

**Comment by da-woods** [comment]
> I would like to know the reasoning why the include statement is not allowed in a class

I don't claim to know exactly why (that code was present in the first commit of Cython when it was forked from Pyrex...) but I'd guess the limitations are mainly about keeping it testable and readable. For example, it isn't obvious to me what level of indentation included class-scope code should be at, or if it matters.

I'm not sure we're keen to expand the "include" mechanism - it was largely replaced by using .pxd files in most causes so is mainly a legacy feature.

In terms of alternatives - I suspect you're better using a string substitution preprocessing step instead. Scipy uses Cython's "tempita" language for this in a few places (e.g. https://github.com/scipy/scipy/blob/701ffcc8a6f04509d115aac5e5681c538b5265a2/scipy/sparse/_csparsetools.pyx.in).

**Comment by scoder** [comment]
For as good as my memory serves me for something that was apparently decided 14 years ago, I think our main reasons back then were that `include` is really one of those last-resort features (like cnames) that users should avoid when possible, and that therefore should be restricted to simple cases that are easy to reason about. There were probably also a couple of semantic uncertainties that we didn't want to dive into.

I don't feel like that situation has fundamentally changed.

As @da-woods suggests, it seems that code generation is a better way to get what you want (it usually is). [cdef dataclasses](https://github.com/cython/cython/pull/3400) are another feature (not merged yet) that you might want to look into.

**Comment by scoder** [comment]
I'll close this ticket as "won't fix". I don't think we want to extend `include`, as long as there are (better) alternatives.

**Comment by gentlegiantJGC** [comment]
Thanks for the responses. Is there any documentation for the tempita language?

I can see there is a bit at the top of this file
https://github.com/cython/cython/blob/master/Cython/Tempita/_tempita.py

This seems to be more detailed and looks the same as your format but isn't managed by you.
https://pyrocore.readthedocs.io/en/latest/tempita.html

It also looks like I need to write some code to compile the template code to cython.

**Comment by da-woods** [comment]
I think it probably is the same thing (and that Cython includes a copy of it, and hasn't modified it significantly), however it predates my involvement in Cython so I don't _really_ know. I don't think we've documented it ourselves because we're mainly treating it as an internal tool (and it's just that scipy have decided to use it because it's there)

You're obviously free to use any string manipulation tool of your choice if you don't like this one!

Scipy (https://github.com/scipy/scipy/blob/f4c9ca25c1839a6737221f74d712da3cdb667369/scipy/_build_utils/tempita.py) and Numpy (https://github.com/numpy/numpy/blob/6375448923b97f3b7bbc21e1cab13b6eab3822c9/tools/cythonize.py) have both written tools to compile the template code as part of the build process so you might look to borrow them (note that Numpy includes its own copy of tempita)

**Comment by scoder** [comment]
We mainly decided for Tempita because it's a single-file template engine that was easy to use without adding a dependency, and supports running arbitrary Python code along the way, so it's not limited by anything. You can also Cython-compile it to make it faster. :)

It's pretty much in the state it was back in 2008(?), with only minor Py3 related adaptations.

Regarding the usage, we [really just do](https://github.com/cython/cython/blob/fa8db66368a9527c8df441a0bbfee714eb795930/Cython/Compiler/Code.py#L627-L638) `_tempita.sub(code, **vars)`. That's it.
