### ISSUE TITLE
Cython doesn't properly optimize cython classes used in cython only code

### ISSUE THREAD

**Issue by L1nkus** [cython/cython#4543]
```
import time
cdef class Num:
    cdef int n
    def __init__(Num self, int n):
        self.n = n
    def __add__(Num self, Num oth):
        return Num(self.n + oth.n)
    cdef inline Num add(Num self, Num oth):
        return Num(self.n + oth.n)
    cdef inline Num add2(Num self, Num oth):
        cdef Num ret
        ret = Num.__new__(Num)
        ret.n = self.n + oth.n
        return ret
    def __repr__(self):
        return str(self.n)

cdef cythfun():
    # cdef int i, n
    cdef Num num, res
    i = 0
    n = 10000000
    num = Num(1)
    res = Num(0)
    while i < n:
        res = res.add(num)
        i += 1
    print(res)

cdef cythfun2():
    # cdef int i, n
    cdef Num num, res
    i = 0
    n = 10000000
    num = Num(1)
    res = Num(0)
    while i < n:
        res = res.add2(num)
        i += 1
    print(res)

cdef cythop():
    # cdef int i, n
    cdef Num num, res
    i = 0
    n = 10000000
    num = Num(1)
    res = Num(0)
    while i < n:
        res += num
        i += 1
    print(res)

cdef cythpy():
    # cdef int i, n, num, res
    cdef int num, res
    i = 0
    n = 10000000
    num = 1
    res = 0
    while i < n:
        res += num
        i += 1
    print(res)

def rawpy():
    i = 0
    n = 10000000
    num = 1
    res = 0
    while i < n:
        res += num
        i += 1
    print(res)

t = time.time()
cythfun()
print(f"cythfun: {time.time() - t}")

t = time.time()
cythfun2()
print(f"cythfun2: {time.time() - t}")

t = time.time()
cythop()
print(f"cythop: {time.time() - t}")

t = time.time()
cythpy()
print(f"cythpy: {time.time() - t}")

t = time.time()
rawpy()
print(f"rawpy: {time.time() - t}")

"""
10000000
cythfun: 0.7377910614013672
10000000
cythfun2: 0.3947124481201172
10000000
cythop: 0.7799794673919678
10000000
cythpy: 0.26244568824768066
10000000
rawpy: 0.39959073066711426
"""
```

The Cython version with a cython class fails to even do better than the pure unannotated version.

In C++ on the other hand:
```
#include <bits/stdc++.h>
using namespace std;

class Num {
public:
    int n;
    Num (int n) : n(n) {}
    Num operator+(const Num &oth) {
        return Num(n + oth.n);
    }
    Num & operator+=(const Num &oth) {
        n += oth.n;
        return *this;
    }
};

void fun1() {
    volatile int i = 0;
    volatile int n = 10000000;
    Num num = 1;
    Num res = 0;
    while (i < n) {
        /* res = res + num; */ // equivalent code / time.
        res += num;
        ++i;
    }
    printf("%d\n", res.n);
}

void fun2() {
    volatile int i = 0;
    volatile int n = 10000000;
    int num = 1;
    int res = 0;
    while (i < n) {
        res += num;
        ++i;
    }
    printf("%d\n", i);
}

int main(){
    {
        auto start = chrono::steady_clock::now();
        fun1();
        auto stop = chrono::steady_clock::now();
        auto diff = stop - start;
        printf("fun1: %f\n", chrono::duration <double, milli> (diff).count());
    }
    {
        auto start = chrono::steady_clock::now();
        fun2();
        auto stop = chrono::steady_clock::now();
        auto diff = stop - start;
        printf("fun2: %f\n", chrono::duration <double, milli> (diff).count());
    }
/*
10000000
fun1: 22.503149
10000000
fun2: 22.042093
*/
}
```
As seen in https://godbolt.org/z/zv85EMPdv the code for fun1 and fun2 is equivalent.

Due to this issue, Cython code that uses simple classes (e.g. for a fixed precision Decimal, or some pair) is inefficient compared to it's potential, or C equivalent code.

**Expected behaviour**
Running time of `cythop` and `cythpy` should be the same.

**Environment**
 - Linux 5.15.10
 - Python 3.10.1
 - Cython 0.29.26

**Comment by da-woods** [comment]
* It's possible that Cython actually does reasonably well at inferring the types for rawpy (I haven't looked at the generated code), so it may not be as "raw" as you think.
* `cythop` would probably do notably better if you defined `__iadd__` (it'd avoid memory allocations)
* You might gain something by using `@cython.freelist(8)` on the class (8 is arbitrary though, but probably a sensible number) - it'll remove some memory allocation, and is ideal for these short-lived instances.

I'm not quite sure what you expect here... A `cdef class` is a Python class so _does_ need reference counting, and _does_ need allocating. It's never going to beat just using C integers directly.

I guess in principle Cython could spot that the instance can never be returned and allocate it on the heap and skip the reference counting. But that's quite hard to prove - it probably involves inspecting into member functions for example. And it'd need to know that `print` doesn't keep a reference too.

I'll close this as "wontfix" because I'm not sure what we can do (but obviously concrete suggestions are welcome!). You might look at defining `cppclass` instead?

**Comment by L1nkus** [comment]
@da-woods 
Makes sense. Thanks for the suggestions, they helped. (esp. `cppclass`, which was what I was after)
