### ISSUE TITLE
[BUG] pyximport uses deprecated "imp" module

### ISSUE THREAD

**Issue by scoder** [cython/cython#4560]
Replace it with `importlib` or whatever seems appropriate and modern.

**Comment by matusvalo** [comment]
I was looking into the problem and pyximport uses more deprecated components - e.g. we are implementing find_module hook which is deprecated from 3.10 [1]. Since we still need do compatibility magic (`importlib` cannot be used in python 2.7), maybe it will be easier to total refactor of pyximport rather than trying to fit `importlib` to old way of importing. (We will keep old pyximport for 2.7 support)

[1] https://docs.python.org/3/library/importlib.html#importlib.abc.Finder.find_module

**Comment by scoder** [comment]
>total refactor of pyximport rather than trying to fit `importlib` to
>old way of importing. (We will keep old pyximport for 2.7 support)

Sounds good to me. We could have a _pyximport2 and a fresh _pyximport3 module, and then have pyximport itself only import the right one. We would drop the ...2 version in Cython 3.1 then, and stick with the clean new module. So that's a good preparation.

**Comment by mattip** [comment]
Right, this will cause a conflict with #4625, so waiting is prudent. The split between pre- and post-python3.5 there will allow the newer version to use `os.path.common`.
