### ISSUE TITLE
[ENH]

### ISSUE THREAD

**Issue by Bechokk** [cython/cython#4586]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. In my code, I would like to do [...]
```cython
# add use case related code here
```

**Describe the solution you'd like**
A clear and concise description of what you want to happen, including code examples if applicable.
```cython
# add a proposed code/syntax example here
```

**Describe alternatives you've considered**
```cython
# add alternative code/syntax proposals here
```

**Additional context**
Add any other context about the feature request here.

**Comment by 0dminnimda** [comment]
Can we collectively report those users, who just create empty / fictitious issues? It also seems that cython isn't the only target for them.
See https://github.com/github/docs/issues/14448

**Comment by da-woods** [comment]
@0dminnimda you're can do - there's a "report user" button on their profile. For a single bad post we should probably assume a mistake, so only report users that are doing it repeatedly.

**Comment by 0dminnimda** [comment]
@da-woods i already did, but what usually matters is number of reports ... I mean, it was 3 consecutive issues from one user, and now the next one ... And as you can see in closed github docs issues, they're using  different accounts, so that's pretty sus. In the end it's not our choice, gihub workers still will look into that by themselves.
