### ISSUE TITLE
[BUG] Assigning an incorrect variable type from a pointer of a different type

### ISSUE THREAD

**Issue by website-reader** [cython/cython#4599]
Problem:
Assigning a variable or passing a variable from a pointer of an imcompatible type

System:
openSUSE Leap 15.2 64 bit linux
Linux localhost.localdomain 5.3.18-lp152.106-default #1 SMP Mon Nov 22 08:38:17 UTC 2021 (52078fe) x86_64 x86_64 x86_64 GNU/Linux
Python 2.17.8
Cython version 3.0.0a10

Warning Message:
```
63263:[sagelib-9.4] build/cythonized/sage/calculus/ode.c:6333:26: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
```

Source code:
```cython
        cdef gsl_odeiv_system sys
        if type:               # The user has passed a class with a compiled function, use that for the system
            sys.function = c_f_compiled
            sys.jacobian = c_jac_compiled
#         (<ode_system>self.function).the_parameters = self.params
            sys.params = <void *> self.function
        else:                  # The user passed a python function.
            sys.function = c_f
            sys.jacobian = c_jac
            sys.params = <void *> wrapper
```
Object code:
```c
    /* "sage/calculus/ode.pyx":519
 *         cdef gsl_odeiv_system sys
 *         if type:               # The user has passed a class with a compiled function, use that for the system
 *             sys.function = c_f_compiled             # <<<<<<<<<<<<<<
 *             sys.jacobian = c_jac_compiled
 * #         (<ode_system>self.function).the_parameters = self.params
 */
    __pyx_v_sys.function = (void *) __pyx_f_4sage_8calculus_3ode_c_f_compiled;
```

Problem:

The problem is that the pointer for `c_f_compiled` is obviated and has been coerced to a void pointer type (`void*`) and a void pointer assigned to `__pyx_v_sys.function`

The class definition has
```cython
  ctypedef struct gsl_odeiv_system:
    int (* function) (double t,  double y[], double dydt[], void * params)
    int (* jacobian) (double t,  double y[], double * dfdy, double dfdt[], void * params)
    size_t dimension
    void * params
```

So it appears that the use of (`void*`) is invalid and it should have read (`function*`) instead, matching the class definition.
------------------------------------------------------------------------------------------------------------------------------

Warning Message:
```
63456:[sagelib-9.4] build/cythonized/sage/combinat/designs/subhypergraph_search.c:2644:64: warning: passing argument 4 of ‘qsort’ from incompatible pointer type [-Wincompatible-pointer-types]
```

Source Code:

```c
    trace_hypergraph64(&h1,n,&tmp1)
    qsort(tmp1.sets,h1.m,sizeof(uint64_t *),cmp_128_bits)
```

Object Code:

```c
 /* "sage/combinat/designs/subhypergraph_search.pyx":281
 *     """
 *     trace_hypergraph64(&h1,n,&tmp1)
 *     qsort(tmp1.sets,h1.m,sizeof(uint64_t *),cmp_128_bits)             # <<<<<<<<<<<<<<
 * 
 *     cdef int i1,i2
 */
  qsort(__pyx_v_tmp1.sets, __pyx_v_h1.m, (sizeof(uint64_t *)), (void *) __pyx_f_4sage_8combinat_7designs_20subhypergraph_search_cmp_128_bits);
```

Problem:
        argument #4, which is cmp_128_bits is the wrong pointer type to the qsort routine. Looking in the C-std, we find that qsort wants an integer compare function signature.
  function in arg #4, NOT a (`void*`) pointer. This is definitely wrong! It is expected to be an integer compare function.

**Comment by da-woods** [comment]
So in the ODE one:

```
cdef int c_f_compiled(double t, double *y, double *dydt, void *params):
```

is assigned to a function pointer of type

```
int (* function) (double t, const double y[], double dydt[], void * params) 
```

So essentially one of the argument types is losing a constant. This looks like something that could be fixed in Sage but not Cython (although it may be there for good reason - previous versions of Cython didn't handle constants too well).

The `qsort` example is similarly missing a const on the pointer types.

-----------------------------------------------------------------

I'm really not sure why Cython is generating the `(void*)` casts - it doesn't seem to be on any toy examples I can construct which leads me to think you may not actually be compiling with Cython 3.10

**Comment by scoder** [comment]
> Cython 3.10

We're not there yet. ;-)

**Comment by scoder** [comment]
But yeah, I would also suggest making sure that you are using the latest Cython 3 release, and then start cleaning up and modernising the code in Sage. I also suggest enabling `-Werror` in both Cython and the C compiler to make sure you are not missing warnings that should be errors. Then you can still disable certain warnings selectively, but with an allow list instead of having them pass silently be default.

**Comment by scoder** [comment]
Closing this, as I don't see anything obvious that we should change in Cython.
