### ISSUE TITLE
python.h missing when building with gcc

### ISSUE THREAD

**Issue by hands0me-maN** [cython/cython#4816]
**Describe the bug**
I was building the .c file generated by cython with gcc and I got the following error on macOS:
fatal error: 'Python.h' file not found
#include "Python.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated. 

**Expected behavior**
just on macOS zsh with apple clang 12.0.-

**Environment (please complete the following information):**
 - OS: [macOS]
 - Python version [3.10.2]
 - Cython version [0.29.18]

**Comment by da-woods** [comment]
Yes you need to tell it the include path. This is expected. The documentation recommends some ways to build Cython modules that handle this for you: https://cython.readthedocs.io/en/latest/src/quickstart/build.html

Please ask further support questions on the [Cython user's mailing list](https://groups.google.com/g/cython-users) instead of here.
