### ISSUE TITLE
[BUG] __del__ does not work with final

### ISSUE THREAD

**Issue by gentlegiantJGC** [cython/cython#4995]
### Describe the bug

Support for Python's `__del__` dunder method was added fairly recently however it does not work if the final decorator is applied to the class.

### Code to reproduce the behaviour:

```cython
# mod.pyx
cimport cython


cdef class DelTest1:
    def __del__(self):
        print("deleting1")


@cython.final
cdef class DelTest2:
    def __del__(self):
        print("deleting2")
```

```py
# main.py
from mod import DelTest1, DelTest2
t = DelTest1()
del t
# deleting1 is printed here
t = DelTest2()
del t
# deleting2 should be printed here but is not
```

### Expected behaviour

I would expect the `__del__` method to be called upon deletion of the object regardless of whether the class is marked as final or not.

### Environment

OS: Windows
Python version: 3.9.13
Cython version: 3.0.0a11

**Comment by da-woods** [comment]
I suspect what's happening is that the `final` lets it deduce that it doesn't need to generate `tp_dealloc`. But this is now wrong because `tp_dealloc` is ultimately responsible for calling `__del__`.

**Comment by da-woods** [comment]
https://github.com/cython/cython/blob/3424926e9c8f03061b55516d2516a9f98999399e/Cython/Compiler/ModuleNode.py#L1680-L1698

It looks like it's specifically checked for. I think that was because it was originally only necessary to call the `__del__` when there might be Python classes that inherit. Now that `cdef class`es can also define `__del__` the check needs to be relaxed a little
