### ISSUE TITLE
error：Operation only allowed in c++

### ISSUE THREAD

**Issue by 3dsfgs** [cython/cython#5050]
I have a. pyx file. I put it in the pycharm directory. I wrote a demo.py To compile the .pyx file, I run python demo py build_ ext --inplace --cplus
report errors：gco_python.pyx:82:4: Operation only allowed in c++
I want to use the def cut_from_graph()  in visual studio2019.
![image](https://user-images.githubusercontent.com/87112362/192274322-d0c4b0f9-5112-4e36-9850-7c4e6cf3eeae.png)
![image](https://user-images.githubusercontent.com/87112362/192274264-ba19018f-2076-475c-a3f2-6b12982cb9b7.png)
demo.py
![image](https://user-images.githubusercontent.com/87112362/192274426-ae8691b4-095a-4975-8954-b135a021f8ad.png)

Please tell me what to do,thank you.

**Comment by 3dsfgs** [comment]
![image](https://user-images.githubusercontent.com/87112362/192275186-0f1e8ec2-1efd-469f-bc43-2da62e055a2d.png)

**Comment by da-woods** [comment]
A screenshot of code really unhelpful - if we want to investigate this we'd have to retype the whole thing. Please post code as actual text.

With that said, setup.py calls cython itself (and you haven't specified the language there) so that's most likely your problem.

In future, please ask support questions on the cython-users mailing list rather than the bug tracker.
