### ISSUE TITLE
[ENH] provide command line option for enabling legacy noexcept propagation

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5088]
### Is your feature request related to a problem? Please describe.

As mentioned in https://github.com/cython/cython/pull/4670#issuecomment-1279918128 introducing default exception propagation in #4670 can introduce compatibility issues for cython users.

### Describe the solution you'd like.

New command line option should be provided enabling legacy noexcept propagation as default:

```
cython -X noexcept ...
```

**Comment by scoder** [comment]
While, on the one hand, this would probably keep users from fixing their code and benefiting from the new, safer behaviour, on the other hand, forcing users to make the complete switch before they can migrate to Cython 3.0 isn't going to help anyone. Disabling the new behaviour does not degrade existing code bases in any way, it just keeps them as buggy as they are.

This new option does not reduce the burden for the migration, though. In order to migrate even just one single function, users will have to remove the option again, and then adapt the entire module, as well as potentially starting with other modules that call into the one at hand. So, the risk is high that users just add the option and leave it there, lacking the time to migrate.

It would be nice if we could continue to issue the warnings if the option is provided. In any case, the option would probably have to be separate from the `noexcept` function modifier, so this should de detectable.

So, it feels difficult to actually help users with the migration by providing some kind of intermediate steps. It seems the migration is either all or nothing. And this option keeps it at nothing. I understand the need, but it would be great to have something that actually helps migrating instead.

**Comment by h-vetinari** [comment]
> It would be nice if we could continue to issue the warnings if the option is provided. In any case, the option would probably have to be separate from the `noexcept` function modifier, so this should de detectable.

That sounds feasible though, as we have the information about the CLI flag completely separately from the parsing?

That way it wouldn't reset the migration to "nothing", it would just be one more warning users will eventually need to heed before they _really_ get broken by the removal.

**Comment by jjerphan** [comment]
As a maintainer of a library using Cython, I think it is sensible to have a temporary `-X` option to enable the legacy `noexcept` propagation for a few release only and instructions to let users adapt their code base to use the new `noexcept` propagation.

**Comment by matusvalo** [comment]
> This new option does not reduce the burden for the migration, though. In order to migrate even just one single function, users will have to remove the option again, and then adapt the entire module, as well as potentially starting with other modules that call into the one at hand. So, the risk is high that users just add the option and leave it there, lacking the time to migrate.

Hmm as long as I understand this option can be enabled on per-file bases. So users can put it to all files and gradually remove it. But I am not sure if this is good approach for users or not...

**Comment by matusvalo** [comment]
EDIT: If there will be agreement between Cython maintainers that we won't go this direction, I am not against closing this issue without the fix.

**Comment by da-woods** [comment]
The main advantage of the per-file basis is that I think anything else would be hard to do with the current implementation.

I don't think it's terrible for users. I'm sure a lot will just turn it on for their existing code and forget about it. But it does at least provide a solution to not break everything immediately

**Comment by jakirkham** [comment]
cc @shwina (in case you have thoughts on this)
