### ISSUE TITLE
[ENH]  How to make the py file  to the pyx file more pythonlity?

### ISSUE THREAD

**Issue by NocoldBob** [cython/cython#5090]
### Is your feature request related to a problem? Please describe.

In my code, I would like to do [...]
```cython
# add use case related code here
```
I want to make my code from py to pyx,in this way ,I find that work is hard and not pythonlity. I read the paper and some wiki ,have no good idea.

### Describe the solution you'd like.

I hope that cython can provide such a new function in the new version to facilitate the rapid conversion from python files to cython code, or reduce the migration work.

### Describe alternatives you've considered.

I have seriously considered this problem. If you can analyze the syntax of python code, and then use the syntax of python to generate code, you can reduce the complexity from python to cython to a certain extent.

**Comment by da-woods** [comment]
At the simplest level there is no complexity: almost all valid py files should be valid Cython files (there's all small amount of introspection that doesn't work).

So just feed your .py file into Cython. If you have useful type annotations then that's even better.

I'm closing this because it doesn't really seem like a concrete proposal - I'm really not sure what you're proposing that Cython do.

**Comment by da-woods** [comment]
Beyond that I think it's probably a documentation problem. (At least some) people clearly do find getting started with Cython a bit overwhelming. Which suggests that our "getting started" guide isn't pitched at the right level, or has acquired too much complexity. Or similar.

**Comment by da-woods** [comment]
> I read the paper and some wiki ,have no good idea.

Neither of those are great places to start though. Have a look at https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html and https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html
