### ISSUE TITLE
[BUG] nthreads seems to be ignored

### ISSUE THREAD

**Issue by rnestler** [cython/cython#5100]
### Describe the bug

I try to compile multiple python modules using
```
"ext_modules": cythonize(
                    module_list=[
                        Extension(
                            "*",
                            ["foo/**/*.py"],
                            define_macros=[("CYTHON_TRACE", "1")],
                        )
                    ],
                    exclude=[
                        "foo/**/main.py",
                        "foo/**/__init__.py",
                        "foo/**/server.py",
                    ],
                    language_level=3,
                    nthreads=multiprocessing.cpu_count(),
                    compiler_directives={
                        "linetrace": True,
                        # We don't have correct enough type information to enable this.
                        "annotation_typing": False,
                    },
                ),
```

When I then run the build step with `poetry install` I only ever see one `cc1` process running.

### Expected behaviour

I'd expect that there are 16 concurrent compilers running (which is what multiprocessor.cpu_count() returns on my machine)

### Environment

OS: Linux
Python version 3.9.15
Cython version 3.0.0a11

**Comment by da-woods** [comment]
I'm not completely sure (because the build system is a bit of a mystery) but I think the cythonize command only really handles the conversion of .pyx/.py files into .c files. Actually invoking the C compiler is left to distutils/setuptools and Cython doesn't really have much control of it.

Therefore, I think that `nthreads` only parallelizes running Cython and not the C build. That isn't necessarily hugely helpful because the C build is usually the slower bit.

**Comment by scoder** [comment]
The `-j N` parallelisation of the distutils `build_ext` command is configured in `build_ext` itself, not in the `Extension` objects that `cythonize()` returns. Thus, Cython doesn't have any control over the build parallelisation of `distutils` (nor `setuptools`).

In your case, it seems to be within the responsibility of `poetry` to make the extension build run efficiently in parallel.

It does seem annoying that you *additionally* have to tell Cython to also parallelise the C code generation. OTOH, `setuptools` has some support also for building Cython extensions directly, without calling `cythonize()` first. That seems an appropriate place to provide parallel calls into both Cython *and* the C compiler. If you call `cythonize()` yourself (which seems reasonable, given the amount of configuration that you pass into it), then I think it's also acceptable to call explicitly for parallel processing.

I'll close this issue since I don't see much that Cython could do better here (at least at the moment).
