### ISSUE TITLE
[BUG] Incorrect type inference for floats

### ISSUE THREAD

**Issue by trevor-pope** [cython/cython#5202]
### Describe the bug

According to the [docs](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#types):

> int, long, and float are not available for static typing and instead interpreted as C ``int``, ``long``, and ``float`` respectively

The following code snippet infers `attr` to be a Python object instead of a float.
```python
import cython

cdef class Test:
    cdef float attr

    @cython.infer_types.verbose(True)
    cdef float test(self):
        attr = self.attr
        return attr
```
Looking at the c code that is generated, cython seems to think that `self.attr` is a double at first instead of a float: `PyFloat_FromDouble(__pyx_v_self->attr);`

The inference is correct when the type is a `double` or an `int`. Is this a bug or am I misinterpreting the docs? 

### Environment

OS: Windows
Python version 3.10.2
Cython version 3.0.0a11

**Comment by da-woods** [comment]
I think this is probably a bug:

```
attr = self.attr
```

Here we're initializing `attr` with a known C float, so `attr` should be inferred as a C float.

There might be a good reason for it but it definitely looks wrong at first glance.

**Comment by scoder** [comment]
Ok, sorry, I misread the bug description then (too many `attr` names in the example).

It might have to do with the fact that we often infer C double for Python float. I'm not so sure if the user intention is clear here. If you do any arithmetic on the variable afterwards, you'd probably end up with a C double value instead of a C float value at some point, unless you're very careful typing literals as C float instead of C double.

In any case, inferring the `attr` variable as Python float object in your example seems wrong. We should at least infer a C floating point type for it, preferably C float.

**Comment by trevor-pope** [comment]
Apologies for the crude example. This might be a better one:

```cython
cdef class Rectangle:
    cdef float x_len, y_len

    @cython.infer_types.verbose(True)
    cdef float get_area(self):
        area = self.x_len * self.y_len
        return area
```
`area` is inferred to be a Python object, despite being the product of two floats.

**Comment by da-woods** [comment]
Right - I've had a look into this properly. It seems that in the "safe" type analysis mode `double -> double` because it'll exactly match the representation of the Python float type anyway (as @scoder said above). `float` isn't specifically handle. 

I've decided the best behaviour is probably to infer it to `double` because that should give the same answer as you get if it was inferred as a Python object. I can be persuaded for either option though

**Comment by scoder** [comment]
> I've decided the best behaviour is probably to infer it to `double` because that should give the same answer as you get if it was inferred as a Python object. I can be persuaded for either option though

I think that if a user chooses explicitly to type a variable or attribute as C `float`, then making a C `double` from that during type inference seems wrong. As I said, it might still happen if you write something like
```cython
x = a_c_float * 1.2
```
since `1.2` is a C `double` literal here and not a C `float`, so that we'd infer `x` as the wider spanning type C `double`. But that's different from inferring C `double` for `y` in
```cython
cdef float x
y = x  # no arithmetic here - why should we change the type?
```

**Comment by da-woods** [comment]
My logic was that if you do any arithmetic it's fairly easy to lose precision compared to the "Python" answer. Which seemed analogous to the overflow protection on `int`. With that said, I don't feel hugely strongly (and it's less dramatically different to `int`) so I've switched it
