### ISSUE TITLE
[BUG] int(pystr) depends on if pystr is declared as str vs object

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#5216]
### Describe the bug

I have a function whose argument is a python string object:

```
cdef myfunc(object pystr):
      cdef:
            int idx
      
      idx = int(pystr[-1])
      return idx
```

As written, the function works fine.  If I change `object pystr` to `str pystr` then `int(pystr[-1])` maps e.g. "1" to 49 (i.e. `chr("1")`) instead of 1.  If I do `int(pystr[-1:])` I get 1 as expected.

### Code to reproduce the behaviour:

```cython
# example code
```

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]

**Comment by scoder** [comment]
Thanks for the report. With `language_level=3str` (and Cython's 3.0 master branch), I get the same correct code for the two cases:
```c
  /*     idx = int(pystr[-1])             # <<<<<<<<<<<<<<    (object pystr)
 */
  __pyx_t_1 = __Pyx_GetItemInt(__pyx_v_pystr, -1L, long, 1, __Pyx_PyInt_From_long, 0, 1, 1); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 5, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = __Pyx_PyNumber_Int(__pyx_t_1); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 5, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __pyx_t_3 = __Pyx_PyInt_As_int(__pyx_t_2); if (unlikely((__pyx_t_3 == (int)-1) && PyErr_Occurred())) __PYX_ERR(0, 5, __pyx_L1_error)
```
```c
 /*      idx = int(pystr[-1])             # <<<<<<<<<<<<<<    (str pystr)
 */
  __pyx_t_1 = __Pyx_GetItemInt(__pyx_v_pystr, -1L, long, 1, __Pyx_PyInt_From_long, 0, 1, 1); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 12, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = __Pyx_PyNumber_Int(__pyx_t_1); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 12, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __pyx_t_3 = __Pyx_PyInt_As_int(__pyx_t_2); if (unlikely((__pyx_t_3 == (int)-1) && PyErr_Occurred())) __PYX_ERR(0, 12, __pyx_L1_error)
```
However, with `language_level=3` (and also with `unicode pystr`), I get this for the `str` / `unicode` case:
```c
  /*     idx = int(pystr[-1])             # <<<<<<<<<<<<<<    (unicode pystr)
 *       return idx
 */
  __pyx_t_1 = __Pyx_GetItemInt_Unicode(__pyx_v_pystr, -1L, long, 1, __Pyx_PyInt_From_long, 0, 1, 1); if (unlikely(__pyx_t_1 == (Py_UCS4)-1)) __PYX_ERR(0, 12, __pyx_L1_error)
```
This seems an unfortunate side effect of optimising unicode item access into reading a single Py_UCS4 integer value for the character, and then optimising `int()` of a C integer into a (redundant) cast, given that the result is then assigned to a C int variable.

I'm not sure where exactly this should be fixed. Maybe calling `int()` (and `float()` alike) on a `Py_UCS4` value should *always* "parse" the Unicode digit instead of just converting the integer value to a plain C integer? That seems a simpler rule than figuring out that the `Py_UCS4` type was just inferred here and treating it differently from explicitly (user) typed `Py_UCS4` values.

To me, it feels that a `Py_UCS4` value should generally behave more like a Unicode character than a C integer.
