### ISSUE TITLE
Cython 3.0: how to migrate from cython.floating ?

### ISSUE THREAD

**Issue by neutrinoceros** [cython/cython#5288]
Attempting to compile yt with Cython 3.0.0b1, I'm getting an error for every occurence of `import cython.floating`. Namely
```
Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport cython
      cimport cython.floating
              ^
      ------------------------------------------------------------

      yt/utilities/lib/vec3_ops.pxd:2:8: 'cython.floating' is not a valid cython.* module
```

I found no mention of this change in the [migration guide](http://docs.cython.org/en/latest/src/userguide/migrating_to_cy30.html), so what is the expected response ?

**Comment by neutrinoceros** [comment]
I think I found the solution myself, replacing
```
import cython.floating
```
with
```
from cython cimport floating
```
appears to be working (and is backward compatible).

**Comment by da-woods** [comment]
You worked out the right way to get at `cython.floating`. I'm a little worried that `import cython.floating` used to work. That was probably never intended since it wasn't supposed to look like a module. But it's definitely a backwards compatibility concern if other people have used it

**Comment by mattip** [comment]
maybe a fake package with instructions for properly changing code would help people fix their code

**Comment by da-woods** [comment]
Or even just changing the error message to:

```
'cython.floating' is not a valid cython.* module. Did you mean to for 'from cython import floating' instead?
```

**Comment by scoder** [comment]
The thing that changed here is that we are now validating the `cython.*` names. We didn't do that (properly) before, so an unknown module like `cython.floating` just slipped through. This is not different from `import cython.addyourowntypohere`. The import never did anything, it just fails now because we detect at compile time that there is no such module. Users should fix up their code. You shouldn't do "import collections.defaultdict` either.

The correct fix is also not to write `from cython import floating` instead, but to remove the import entirely. As soon as you `import cython`, `cython.floating` is a valid attribute of it. You don't need to say `import os.walk` in order to use `os.walk()`.

**Comment by neutrinoceros** [comment]
> The correct fix is also not to write from cython import floating instead, but to remove the import entirely. As soon as you import cython, cython.floating is a valid attribute of it. You don't need to say import os.walk in order to use os.walk().

Right, but in some instances we are dealing with 13yrs old code that has been using `floating` as a name instead of `cython.floating`, so replacing the import is still the less invasive fix, I think ?

**Comment by scoder** [comment]
> code that has been using `floating` as a name instead of `cython.floating`

It couldn't, since there was no import for that. It's like you can't use `defaultdict` unless you import it from `collections`, in one way or another. If there's code where this worked before (somewhere, in another project), then that code had a separate `import` statement in some place. The `import` statement that you showed really did nothing.
