### ISSUE TITLE
Opinion: Cython 3 should drop py27/py34 so that annotations can be used

### ISSUE THREAD

**Issue by rickmark** [cython/cython#5321]
### Describe your issue

Hey All,

I know that Cython 3 is getting near complete, but working in the codebase is pretty unapporachable at this time due to the complex types used (nodes) and the lack of the ability to navigate with type annotations.  In order to use the typing annotations, py35 would be required.  I think its a value trade off of the usefulness of Cython going forward and the ability to gain contributions to drop support for those versions (they will forever be able to use prior versions of cython).

almost no one relies on 3.4 that cant move to 3.5, so the question is how much effort tradeoff there is in supporting 2.7 (which - is end of life)

**Comment by da-woods** [comment]
I think the plan remains to drop those versions very shortly after Cython 3.  I.e. we've said that Cython 3 will be the last release to support 2.7 and we'd like to stick to it.  I think we're all looking forward to clearing out the Python 2 legacy code.

This may be an unpopular opinion, but personally I kind of dislike too many annotations in Python code. They're kind of nice for simple arguments (on the level of `a: str`, or `node: Node`), but even `Optional[Node]` is about the limit of complexity for me.  For me an argument doesn't have to be very polymorphic for the annotation to turn into pure useless noise.

So personally, I kind of hope they're used in a pretty restrained way in the Cython code-base. There's a lot of places where annotating Cython will pretty pretty simple, but there's quite a few places where it won't be, and I hope people won't feel the need to.

**Comment by rickmark** [comment]
Yeah I think one of the better places is where things like duck typed tuples so you do not have to gist an entire method to understand the expected type… “pos” position arguments are a good use case

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scoder** [comment]
> For me an argument doesn't have to be very polymorphic for the annotation to turn into pure useless noise.

I agree. Several arguments are so ubiquitous (e.g. `pos`, `node`, `scope` or `type`) that I'd rather not clutter the signatures with type annotations for them. That would be really annoying. Their names are so short and clear enough that they'd suffer from additional (annotation) screen space. And the remaining arguments, well, not sure if they are worth adding annotations. Some might be, but I'd generally prefer seeing less here than more.

I don't think the Py2 support is the reason why Cython does not use annotations in its code base.

**Comment by scoder** [comment]
Closing since 3.0 will not change anything here.

**Comment by scoder** [comment]
> Old style comment annotations can be used in older python versions.

… which doesn't mean that adding comment clutter is any better than adding annotation clutter. I'm fine with adding type annotations sparsely where they help and do not harm the readability. I'd like to avoid adding them where they get in the way.

**Comment by 0dminnimda** [comment]
> If we only add them to places where no-one ever looks, bloating their signatures won't hurt much. :)

IMO that is pointless without annotating other code

> If you don't know that `analyse_types()` is passed a `Scope`, then you probably don't know what `analyse_types()` does and how it works, and should rather read its documentation.

Point of annotations is provide part of the documentation to be immediately accessible and checked by other tools

> Just because you are able to pass a value of the right type into a function does not mean that you are doing something reasonable already. And just knowing what type you have in your hands does not enable you to do something sensible with it right there.

I agree and annotations do not claim to check that code is sensible they just check for possible runtime errors in the typechecking time, ahead of running the code, thus enable you to fix typos or errors incorrect use of function, like passing the wrong type, immediately 

One thing is that if you're so against annotations in the code, cython can ship annotations like typeshed ships them - in separate pyi files

Also the initial work of typing the whole repo can be done easily using `pyannotate` and running our exhaustive test suit to give it the runtime type information

**Comment by scoder** [comment]
> > If we only add them to places where no-one ever looks, bloating their signatures won't hurt much. :)
> 
> IMO that is pointless without annotating other code

I'm not sure why you say that. A large part of my work on Cython is in these methods (in subtypes). I expect that to be similar for new contributors.


> cython can ship annotations like typeshed ships them - in separate pyi files

No, please. That is a huge mess. We'll just permanently forget to update them and have CI failing each time just for that. It's bad enough that we have `.pxd` files next to the `.py` files that we compile – I permanently forget to update those, too. (BTW, they contain type information already. I would guess that PyCharm Professional and the like should be able to pick them up.)


> Also the initial work of typing the whole repo can be done easily using `pyannotate`

I don't think automatic annotation tools will help with adding type annotations selectively to a couple of important methods. They certainly cannot decide where they don't get in the way for human readers. We simple *know* what types go into these methods since the argument names are obvious. We can add type annotations by hand.

**Comment by 0dminnimda** [comment]
From what I know `pyannotate` uses runtime information, so no need to *know* anything
The only concern is that if we need to force some type to be different from one that `pyannotate` - what to do then

And I can definitely see the problem with keeping two or even more files in sync, which also suggests the idea of merging them, since most of the cython syntax is covered with cython-python annotations

> I'm not sure why you say that. A large part of my work on Cython is in these methods (in subtypes). I expect that to be similar for new contributors.

I guess I am not quite sure what methods are you talking about
