### ISSUE TITLE
pyMSVC

### ISSUE THREAD

**Issue by kdschlosser** [cython/cython#5348]
### Describe your issue

I am the author of pyMSVC and I just noticed the link in the Cython documentation. I went and checked the insights for that repository and over the last 30 days there were 59 visitors that were referred by the Cython documentation. I know it's not a huge number and hopefully it has helped some of those people.

I have not had a need to make any changes with the library at all. Kind of a bad thing because it looks like it has been abandoned. So I wanted to make sure that you guys know it is still being maintained there hasn't been any need to update anything. no bug reports or anything like that, it just works.

I did a little bit of research to see if setuptools has been updated to sole the issues. I found that it has not been updated. over the last year there has been 2 changes to the MSVC compiler detection, one had to do with numpy and the other removed a deprecation warning. Even with all of the complaints about it not working correctly it has not been fixed.

I did however notice some comments at the top of the msvc.py file in setuptools and I actually read them and didn't just glance at them. simplified version of what it says is that it does not support Visual Studio... It only supports Visual C++ Build Tools (Visual Studio Build Tools). Those are actually 2 different things and locations of the components used to compile an extension will be different for both the registry and also the file system. This is something that is not documented for setuptools and is only found in the comments of the msvc.py file located within setuptools

so it is known, pyMSVC supports both VS and Build Tools.

I am hoping that people that are looking at the pyMSVC repo are actually using it and solving their issues with it. Has there been a decline in the number of people having failed builds on Windows?

**Comment by da-woods** [comment]
I'm going to close this because I don't know that there's anything for us to actually do here. But:

* Glad it's still maintained and we can continue to link to it!
* Presumably if it's working right then people should visit once from the Cython documentation and then never think about it again. So perhaps a huge rate of visitors isn't expected.
* If you think there's anything we can improve on the Cython documentation then please feel free to suggest it
* > Has there been a decline in the number of people having failed builds on Windows?

  I don't know to be honest - I don't remember seeing too many recently, but there was never a huge rate of issues. Possibly it is helping, but it's hard to be sure. I think using Mingw on Windows is the current poorly-documented semi-supported feature that people like to ask about.

**Comment by kdschlosser** [comment]
no worries about closing this. It was more for the purposes of keeping you guys informed that I am still maintaining the project even tho it appears to be stale. I also wanted to let you know what I had discovered about the MSVC portion of setuptools so if anyone does come asking you have some answers to give them. I did want to let you know that people have found the link in the documentation as well so it's doing it's job for the people that need it.
