### ISSUE TITLE
Suggestion and issue reports for the future of Cython

### ISSUE THREAD

**Issue by evan0greenup** [cython/cython#5407]
# Prepare to be candidate of standard library of Python

Cython is awesome project. Nowadays, almost all venv environment has Cython installed. As a result, for the demand aspect, almost everyone hope it becomes part of standard library in the future.

# Suggestion of refactoring and improvement

- The naming and style convention is not Pythonic. In python, all modules are supposed to be lower case. And so on.
- There is tree root level modules in Cython, there are `cython`, `Cython` and `pyximport`. In my suggestion, provide single root level module named `cython` and all those stuff be sub-module of it.
- Give user more control on importing pyx files. Currently, when want to import pyx file in normal python script. It need firstly `pyximport.install()` and then `pyximport.load_module(...)`, `pyximport.install()` is a global operation, there is too many side-effect for user who just want to import a single module which has only one cython function for acceleration. It would be nice to add some mechanism to load module without changing global configuration.
- `distutils` will be removed in Python 3.12, Please consider to use `setuptools` and `packaging`.
-  It would be Pythonic if make all filename, path-related variable and arguments `pathlib.Path` compatible. Currently, `pyximport` module's filename related stuff doesn't support `pathlib.Path` objects.
- Make cython packaging related stuff support modern packaging tool (like poetry).
- The last but not the least, drop support for Python 2.x , now, almost nobody use Python 2. If there is they can use Cython 0.x for their application. Python 2 historical legacy is too heavy for a project's development.

# Some personal thought

It really cannot be imagined what the would will look like if Cython disappeared. If the upstream author use Cython to accelerate their project. I would be very happy. But if let me use Cython in my codebase, I would be hesitate. Due to the issue I mentioned above. I am very worried about whether it is long-term solution.

Python is a glue language, what Cython done is making this glue stick items easier. I really hope Cython codebase become how PEP hope to be.

Every brilliant project is done by refactoring again and again.

**Comment by evan0greenup** [comment]
@scoder , What is your opinion?

**Comment by mattip** [comment]
The issue tracker is not the place for general discussion. This should have been clear from the issue template used to open new issues here. I wonder how you missed that when opening this issue? Please use the mailing list for general discussion. But since you already asked ...

> almost everyone hope it becomes part of standard library

As a NumPy maintainer, I view open source software and the base python differently. There is no special group of maintainers waiting for a package to enter the standard library in order to contribute to it, and no special funding process for making a package inside the standard library more lucrative than one outside it. Actually the opposite is true: once a package enters the standard library it is more difficult to make deep changes, its release cycle is tied to CPython's release cycle, and funding is now part of a larger CPython funding issue.

> I am very worried about whether it is long-term solution

Cython has been around for quite a while, and has shown it can grow a small community of maintainers. What would ensure its future would be sustainable funding. If your project is using cython, or for that matter, any open source software, you should be funding its maintenance. Assuming you are not already, you can do so from the "sponsor" link at the top of this page, or by any of the means listed in the [documentation](https://cython.org/#donate). If you already are finding a way to contribute or to get your employer to contribute, then thanks!

Many of the items on your "suggestions" list are in progress or have been discussed elsewhere. You might have more impact by splitting them into manageable tasks, looking in the issue tracker if any of them (like distutils or python2) have been discussed elsewhere, and either opening new issues or commenting on the existing ones.

**Comment by evan0greenup** [comment]
@mattip 

1. Whether become standard library is up to core developers. But being Pythonic is always good for a foundational library like Cython.

2. I am neither doubt about the funding capability of Cython, nor using Cython for product construction. I just using for my hobby project. I just enjoy programming. The initial of Python project is also similar. The way I contribute to Cython will be code commits and feature enhancement to Cython. But first, the project need to make contributor feel comfortable to contribute with -- coding style and naming convention. A Upper Case module name really make me feel dizzy with class name, and sometimes really easy to accidentally instancing module for instance.  

3. I just want Cython to become well-organized.

**Comment by da-woods** [comment]
> * The naming and style convention is not Pythonic. In python, all modules are supposed to be lower case. And so on.

PEP 8 also says "Some other good reasons to ignore a particular guideline: [...] To be consistent with surrounding code that also breaks it (maybe for historic reasons)
 
> * There is tree root level modules in Cython, there are `cython`, `Cython` and `pyximport`. In my suggestion, provide single root level module named `cython` and all those stuff be sub-module of it.

They're kind different things though. The `cython` module is things we want users to access (e.g. decorators to control compiler options, type annotations). The `Cython` module is our own implementation - we don't want someone who's simply using the compiler to have access to all the compiler internals. `pyximport` is a separate tool to let people have quickly compile a module for development purposes.
 
> * Give user more control on importing pyx files. Currently, when want to import pyx file in normal python script. It need firstly `pyximport.install()` and then `pyximport.load_module(...)`, `pyximport.install()` is a global operation, there is too many side-effect for user who just want to import a single module which has only one cython function for acceleration. It would be nice to add some mechanism to load module without changing global configuration.

The robust way to control importing pyx files is to write a setup script. `pyximport` is only intended to be a quick and dirty solution to help people in development.
 
> * `distutils` will be removed in Python 3.12, Please consider to use `setuptools` and `packaging`.

We've mostly changed to setuptools in the master branch. If there's anything we've missed then PRs are welcome.

> * It would be Pythonic if make all filename, path-related variable and arguments `pathlib.Path` compatible. Currently, `pyximport` module's filename related stuff doesn't support `pathlib.Path` objects.

PRs are welcome.

> * Make cython packaging related stuff support modern packaging tool (like poetry).

Yes, this is definitely something we'd like to improve. I know almost nothing about poetry personally, unfortunately

> * The last but not the least, drop support for Python 2.x , now, almost nobody use Python 2. If there is they can use Cython 0.x for their application. Python 2 historical legacy is too heavy for a project's development.

We've said that 3.0 will be the last release to support 2.x. We do intent to see that through, and then it's dropped.

------------------------------

> Nowadays, almost all venv environment has Cython installed.

That's probably not true, nor should it be true. I imagine most venv have something built with Cython installed, but that shouldn't require them to have Cython itself installed.

> As a result, for the demand aspect, almost everyone hope it becomes part of standard library in the future.

It's been discussed a few times in the past. I think the conclusion was not to do it:
* it makes it harder to add new features
* it ties Cython to the Python versioning - currently there's very little difference between Cython whichever version of Python it's installed on. If it were part of the standard library we wouldn't be able to go back and update Cython on Python 3.7 - it'd forever be fixed to what was released then.

(largely the reasons that Matti said above)

----------------------------------------------------------------------

> It really cannot be imagined what the would will look like if Cython disappeared. 

It's unlikely to disappear completely - it's open source and there's plenty of copies out there. However, as with any open-source project there's a limited number of maintainers and so it obviously isn't guaranteed that it'll be maintained forever.
It probably wouldn't be too hard for someone to keep it up-to-date with changes in the C API and working as it is now, even if the core maintainers disappeared.

**Comment by evan0greenup** [comment]
@da-woods , For NOT INTEGRATE AS STANDARD LIBRARY, now I understand, thanks for explain it to me.

But here I would like to introduce my philosophy toward open source framework (especially) Python open source framework.

Cython is different from the open source software like `vlc` and `libreoffice`, The majority of those software's user is not programmer. For Cython, all its user is experienced programmer. The core developers of projects like Cython should not restrict their user. In addition to make the software fit for majority user. It also is also need to preserve the space for geeks to hack the framework, to maximum its potential value. A good example is Python's importlib. In the old version of python, there is no importlib. The details of Python import system is so-called internals, and the majority user will not use this feature. But there it is, and it is successful. And there is a lot of such low level internals which is sharpened to become accessible to users. *Geek's inspiration* is very important. Make details get sharpened and let the advanced user explore their own way on this framework. The expected effect is like the user add features which the core developer have never imagine before. This is what the project like Cython should travel through.

**Comment by evan0greenup** [comment]
The dynamic and self-reflexion nature make Python and Python-related extension (like Cython) different from the compiled language.

**Comment by stevenleeS0ht** [comment]
In my opinion, the procedure should like this:

1. decide the expected high-level behave.
2. find the best low-level approach to achieving this goal. Until it is the best in nature (there is no better alternative approach).
3. refine the low-level stuff (data structure, low-level interface ...) to make it hackable to user.

This cycle should go again and again for to add new feature. This should be what you expect @evan0greenup .

When the behavior is not determined yet, focusing on low-level stuff is too early.

**Comment by scoder** [comment]
> * The naming and style convention is not Pythonic. In python, all modules are supposed to be lower case. And so on.

While not PEP-8, I don't see a reason to change this. We considered it back in 2007 when we forked Cython from Pyrex, and decided against it because there was little to gain for the existing code base.

> * There is tree root level modules in Cython, there are `cython`, `Cython` and `pyximport`. In my suggestion, provide single root level module named `cython` and all those stuff be sub-module of it.

I'd be fine with moving `pyximport` into a separate package. Cython doesn't depend on it in any way, and pyximport doesn't really depend on a specific Cython version. Also, I don't want to put any work into pyximport, really. And that's the reason why that wasn't done yet.

> * Give user more control on importing pyx files. Currently, when want to import pyx file in normal python script. It need firstly `pyximport.install()` and then `pyximport.load_module(...)`, `pyximport.install()` is a global operation, there is too many side-effect for user who just want to import a single module which has only one cython function for acceleration. It would be nice to add some mechanism to load module without changing global configuration.

`pyximport` is a hacked-up development tool that was built to reduce the manual compilation work while programming Cython modules. It was specifically designed as an import hook, thus the `install()` step. IDEs can probably do something better these days.

> * It would be Pythonic if make all filename, path-related variable and arguments `pathlib.Path` compatible. Currently, `pyximport` module's filename related stuff doesn't support `pathlib.Path` objects.

See my comments regarding pyximport above. If someone wants to put work into this, fine. Maybe someone could fork it and turn it into a separate PyPI project, so that we can eventually remove it from Cython's code base.

> * `distutils` will be removed in Python 3.12, Please consider to use `setuptools` and `packaging`.

There is a latent friction between the way setuptools uses Cython and Cython uses setuptools (or, rather, distutils in a few corners) since setuptools tries to use Cython at the same time Cython is using  setuptools. It's unclear what would be the best place to improve this, but I'd guess that both projects would have to move a little. As it stands, it usually works.

> * Make cython packaging related stuff support modern packaging tool (like poetry).

It's not really Cython's job to use distutils or setuptools, or other build tools and frameworks. Build tools should best integrate with Cython themselves, i.e. the other way round. Cython is only one step in a build process, a single, separate one, that these tools should execute.

> * The last but not the least, drop support for Python 2.x , now, almost nobody use Python 2. If there is they can use Cython 0.x for their application. Python 2 historical legacy is too heavy for a project's development.

Let's leave that for Cython 3.1, as planned.

**Comment by scoder** [comment]
It seems to me that this issue has been discussed and there is nothing actionable in it. At least, it's way too broad to keep it open. I'll close it.
