### ISSUE TITLE
[BUG] Shared reference between object and argument in cython function

### ISSUE THREAD

**Issue by johnstill** [cython/cython#5412]
### Describe the bug

A memoryview declared inside a function is the same reference as one of the memoryview arguments (see the minimal repro).

### Code to reproduce the behaviour:

```cython
# cython: language_level=3
import numpy as np

def bug_check(double[:, ::1] W):
    cdef Py_ssize_t n = W.shape[0]
    # W is shape (n, n) - I want another buffer W1 of the same size/shape for working space
    # This should create a new array of the same type and shape but actually W and W1 are the same reference.
    cdef double[:, ::1] W1 = np.zeros((n, n))
    print('W', id(W))
    print('W1', id(W1))   # They are the same memoryview! Updating one updates the other.
    assert id(W) != id(W1)  # fails
```

### Expected behaviour

I expect when I create new objects in the above manner they won't share underlying references or data.

### OS

Linux Cent OS 7

### Python version

3.10.11

### Cython version

I tested this with both latest stable on conda (0.29.x) and installed from source

### Additional context

I'm not sure what else to say about this - ask for any other information that may be useful and I'll gladly provide it.

**Comment by da-woods** [comment]
`id(W)` creates a short lived Python object that wraps `W` and returns the ID of that. A memoryview itself doesn't have an ID.

What you see is a fairly reasonable outcome (although not the only outcome). In CPython an ID is just a pointer converted to an `int`. So if you create a temporary Python object `id(W)`, destroy it, then create a second temporary Python object (``id(W1)`) it's pretty reasonable they'd appear to be the same since it reuses the same memory location.

`id(W) != id(W1)` ends up different because both temporary objects have to exist for the duration of the line.

So, not a bug. `id` of a memoryview simply isn't meaningful.

**Comment by johnstill** [comment]
Thank you for the rapid response and explanation.
