### ISSUE TITLE
CI stopped supporting python 2.7

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5493]
### Describe your issue

2.7 tests are failing with following message:

```
Run actions/setup-python@v3
Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
Version 2.7 was not found in the local cache
Error: Version 2.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

See https://github.com/actions/setup-python/issues/672 for details

**Comment by matusvalo** [comment]
Here is possible solution but not sure whether it is worth it: https://github.com/actions/setup-python/issues/672#issuecomment-1589120020

**Comment by scoder** [comment]
I partially got it back to work in https://github.com/cython/cython/commit/1dd1457df840c49e65f65ff1c5499b812b17cede, there's just one test failing now. Might also be an issue with the C compiler config.

**Comment by scoder** [comment]
I think I got most of it working again. I had to disable a few tests, especially on macOS, but then that's how it is. Py2.7 is legacy, I'm not going to invest weeks into bringing everything back to happy state.

Closing this ticket since we have a running CI setup again.

(It's probably still worth copying some of the changes over to 0.29.x.)
