### ISSUE TITLE
[BUG] functools.cached_property does not work on cdef classes

### ISSUE THREAD

**Issue by vyasr** [cython/cython#5523]
### Describe the bug

The `cached_property` decorator fails when used inside a `cdef class`.

### Code to reproduce the behaviour:

```cython
from functools import cached_property
cdef class A:
    @cached_property
    def x(self):
        return 1

a = A()
a.x
```

Output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
----> 1 a.x

File ...
    963     return self
    964 if self.attrname is None:
--> 965     raise TypeError(
    966         "Cannot use cached_property instance without calling __set_name__ on it.")
    967 try:
    968     cache = instance.__dict__

TypeError: Cannot use cached_property instance without calling __set_name__ on it.
```

### Expected behaviour

The above snippet should generate a working (cached) property.

According to the docs, [`__set_name__` is only called on descriptors if they are created as part of the class definition](https://docs.python.org/3/reference/datamodel.html#object.__set_name__). I suspect that the reason for this issue is that Cython is actually translating the above code into the equivalent of 
```python
from functools import cached_property
class A:
    def x(self):
        return 1

A.x = cached_property(A.x)

a = A()
a.x
```
which reproduces the issue in pure Python. The above snippet may be fixed by manually calling `A.x.__set_name__(A, "x")`, so I would guess that line needs to be added into the Cython handling of the cached property as well somewhere. 

### OS

Linux

### Python version

3.8.16 (and 3.10.2)

### Cython version

3.0.0b3 (and 0.29.36)

**Comment by TeamSpen210** [comment]
Since the decorator accesses the object's `__dict__`, it also won't work for that reason. It doesn't really provide a performance benefit for Cython code, since a regular property would have the same performance.

**Comment by vyasr** [comment]
That's a good point. You could fix that limitation as documented [here](https://cython.readthedocs.io/en/latest/src/userguide/troubleshooting.html?highlight=__dict__#writing-into-extension-types).

Why wouldn't it provide a performance benefit for Cython code? Wouldn't caching the value allow you to elide the function call and any logic in the property (for something less trivial than my example above)? Or am I misinterpreting your statement?

**Comment by TeamSpen210** [comment]
The decorator does allow you to elide the function call, but only from the Python perspective. Every attribute lookup is still a function call, it just means it only uses the builtin interpreter logic, so it's at C speeds. But for C extension classes, all attributes are accessed only through properties (since they're stored as part of the struct), so there's nothing to skip. All that `cdef public ...` does is auto-generate the implementation for you.

**Comment by vyasr** [comment]
Hmm I think you're focusing on a different piece of this than I am. Let me illustrate with an example, please correct me if you see a point where I'm misunderstanding.

Say I have a class:
```
class A:
    @cached_property
    def one(self):
        return expensive_function_that_returns_one()
```
The `one` descriptor will be defined on the class, not on each instance. The first time I do `a = A(); a.one` it will effectively do `a.one = A.one(a)`. Then, future accesses to `a.one` will be able to actually see that `a.__dict__['one'] == 1` and bypass calls to `A.one`.

Now let's switch that to a Cython class with a raw property:

```
cdef class A:
    @property
    def one(self):
        return expensive_function_that_returns_one()
```

- Accessing the attribute `A.one` automatically happens at C speeds because it's a reserved slot in the struct rather than a Python dictionary access. So yes, removing this overhead in Cython is meaningless because it's equivalent.
- The actual function call `one` is still going to happen at Python speeds because it's a Python function. AFAIK there is no way around this because you can't make `cdef` functions properties.
- The `expensive_function_that_returns_one` doesn't actually have to be an expensive function, all it needs is to be a Python (not C) function in order to introduce the usual overheads (unboxing PyObjects, etc) associated with a Python function call instead of a C function call.

If `cached_property` worked in Cython, then we could remove the overhead of both the second and third bullet points, right?

**Comment by TeamSpen210** [comment]
That would all be true normally yes, except that Cython handles `@property` decorators specially. It detects you using it (along with the standard `@attr.setter`/`@attr.deleter` variations), then puts them in the [`tp_getset`](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_getset) list in the type definition. That generates `getset_descriptor` objects, which store function pointers for the getter/setter. Those have fixed signatures, so there's no argument parsing overhead or anything, but for the setter there's type-checks/unboxing for the value of course.

Definitely calling `expensive_function_that_returns_one()` repeatedly would be wasteful, what I was meaning was to do the traditional caching in your code. Possibly Cython could just detect `cached_property` and generating that code automatically, but it might be a little awkward since you then have the same name referring to both the descriptor and the struct member. Any access in your Cython code wouldn't be able to bypass the property.

**Comment by da-woods** [comment]
I think you're right in your diagnosis of what the problem is. It probably also wouldn't be too hard to add the `__set_name__` calls and make this kind of work.

It's probably work emphasising that `cdef classes` *aren't* regular Python classes - you're trading flexibility and features for speed. There's all kinds of stuff you can do in the body of Python classes that won't work in `cdef classes` (pretty much anything that relies on order of execution, putting function definitions in `if` statements, etc.). That's just because functions and properties are statically defined at compile-time rather than dynamically at runtime (mostly).

Cython definitely tries to get regular Python-style classes to behave as close as possible to Python behaviour. But I don't think we worry too much if `cdef classes` have to deviate a bit.

Which isn't to say that it won't get fixed if it can be, but it isn't completely obvious to me that this should work.

**Comment by vyasr** [comment]
> That would all be true normally yes, except that Cython handles @property decorators specially.

OK yeah I was wondering if that was the case. I don't know the Cython internals terribly well unfortunately, thanks for the info.

>  Possibly Cython could just detect cached_property and generating that code automatically

That's what I was imagining could be done. Whether it's worthwhile or not is a different question, and as I said above I'm totally fine if Cython decides not to fix this. It would be nice to include a better error message if that's the decision, though.

> It's probably work emphasising that cdef classes aren't regular Python classes - you're trading flexibility and features for speed. 

Yup, totally fair. I was expecting this decorator to work, but not for any particularly good reason. Its implementation is certainly antithetical to the way Cython classes work given that it's exploiting the instance's `__dict__` and the relationship between descriptors on classes and instance attributes.

**Comment by matusvalo** [comment]
I think the rootcause of the problem is that Cython for cdef classes does not call `__set_name__` as described in documentation [1]:

> Automatically called at the time the owning class owner is created. 

Simple example not involving `@cached_property` based on descriptor documentation [2]

```python
# descriptor.py file
import logging

logging.basicConfig(level=logging.INFO)

class LoggedAccess:

    def __set_name__(self, owner, name):
        self.public_name = name
        self.private_name = '_' + name

    def __get__(self, obj, objtype=None):
        value = getattr(obj, self.private_name)
        logging.info('Accessing %r giving %r', self.public_name, value)
        return value

    def __set__(self, obj, value):
        logging.info('Updating %r to %r', self.public_name, value)
        setattr(obj, self.private_name, value)
```

```cython
# example.pyx file
from descriptor import LoggedAccess

cdef class Person:

    cdef public object _name
    cdef public object _age
    name = LoggedAccess()
    age = LoggedAccess()

    def __init__(self, name, age):
        self.name = name
        self.age = age
```

Compiling and using example.pyx will trigger an error:
```python
>>> from example import Person
>>> p = Person('John', 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.pyx", line 11, in example.Person.__init__
    self.name = name
  File "/home/matus/dev/cython/test/example.py", line 17, in __set__
    logging.info('Updating %r to %r', self.public_name, value)
                                      ^^^^^^^^^^^^^^^^
AttributeError: 'LoggedAccess' object has no attribute 'public_name'
```

In contrast same example in python works:

```python
from descriptor import LoggedAccess

class Person:

    name = LoggedAccess()
    age = LoggedAccess()

    def __init__(self, name, age):
        self.name = name
        self.age = age
```

[1] https://docs.python.org/3/reference/datamodel.html#object.__set_name__
[2] https://docs.python.org/3/howto/descriptor.html

**Comment by matusvalo** [comment]
OK I was able to fix example above by adjusting `__pyx_pymod_exec_pyxpyx` as follows:

```c
   /* "pyxpyx.pyx":7
  *     cdef public object _name
  *     cdef public object _age
  *     name = LoggedAccess()             # <<<<<<<<<<<<<<
  *     age = LoggedAccess()
  *·
  */
   __Pyx_GetModuleGlobalName(__pyx_t_3, __pyx_n_s_LoggedAccess); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 7, __pyx_L1_error)
   __Pyx_GOTREF(__pyx_t_3);

   __pyx_t_2 = __Pyx_PyObject_CallNoArg(__pyx_t_3); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 7, __pyx_L1_error)
   __Pyx_GOTREF(__pyx_t_2);
   if (PyObject_HasAttrString(__pyx_t_2, "__set_name__")) {
       PyObject_CallMethod(__pyx_t_2, "__set_name__", "Os", (PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_k_name);
   }
   __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
   if (__Pyx_SetItemOnTypeDict((PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_n_s_name, __pyx_t_2) < 0) __PYX_ERR(0, 7, __pyx_L1_error)
   __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

   /* "pyxpyx.pyx":8
  *     cdef public object _age
  *     name = LoggedAccess()
  *     age = LoggedAccess()             # <<<<<<<<<<<<<<
  *·
  *     def __init__(self, name, age):
  */
   __Pyx_GetModuleGlobalName(__pyx_t_2, __pyx_n_s_LoggedAccess); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 8, __pyx_L1_error)
   __Pyx_GOTREF(__pyx_t_2);
   __pyx_t_3 = __Pyx_PyObject_CallNoArg(__pyx_t_2); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 8, __pyx_L1_error)
   if (PyObject_HasAttrString(__pyx_t_3, "__set_name__")) {
       PyObject_CallMethod(__pyx_t_3, "__set_name__", "Os", (PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_k_age);
   }
   __Pyx_GOTREF(__pyx_t_3);
   __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
   if (__Pyx_SetItemOnTypeDict((PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_n_s_age, __pyx_t_3) < 0) __PYX_ERR(0, 8, __pyx_L1_error)
   __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
```

The change is adding lines - they ensures that `__set_name__` method is called:
```c
   if (PyObject_HasAttrString(__pyx_t_3, "__set_name__")) {
       PyObject_CallMethod(__pyx_t_3, "__set_name__", "Os", (PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_k_age);
   }
```
and
```c
   if (PyObject_HasAttrString(__pyx_t_3, "__set_name__")) {
       PyObject_CallMethod(__pyx_t_3, "__set_name__", "Os", (PyObject *)__pyx_ptype_6pyxpyx_Person, __pyx_k_age);
   }
```
