### ISSUE TITLE
Scikit learn wheel failing to compile on Debain

### ISSUE THREAD

**Issue by mayuresh-quartic** [cython/cython#5548]
### Describe the bug

Describe the bug
Wheel is failing to compile
Previously it was working with same versions

<img width="1364" alt="Screenshot 2023-07-20 at 09 59 07" src="https://github.com/cython/cython/assets/104883828/0a552e87-02a2-4eb6-85a0-733108ef036f">

<img width="1369" alt="Screenshot 2023-07-20 at 09 59 30" src="https://github.com/cython/cython/assets/104883828/cb032973-e3d4-47e5-b880-d4ccc2391fb6">

### Code to reproduce the behaviour:

pip version 22.0.4, 23.1.2
Python 3.9.5

gcc is already the newest version (4:8.3.0-1).

### Expected behaviour

scikit-learn should compile and install properly

### OS

Linux (Debain)

### Python version

3.9.5

### Cython version

3.0.0

### Additional context

scikit-learn==0.23.1
scipy==1.7.0
numpy==1.22.0
joblib==1.2.0
threadpoolctl==3.1.0

pip version 22.0.4, 23.1.2
Python 3.9.5

gcc is already the newest version (4:8.3.0-1).

https://github.com/scikit-learn/scikit-learn/issues/26865
https://github.com/scikit-learn/scikit-learn/issues/26858

**Comment by da-woods** [comment]
It'll be to do with the `cpow` directive. By design `**` of two ints now returns a double where it returns an int before. To turn it back use `cpow(True)`.

This is an expected incompatibility that'll have to be updated in scikit learn.

As an aside, pictures of text are a terrible way to present text. Please post the error message as text in future if possible.

**Comment by da-woods** [comment]
It also looks like you're using an old version of scikit learn and this is sorted in recent versions: https://github.com/scikit-learn/scikit-learn/issues/26858
