### ISSUE TITLE
Use Python 2-compatible syntax in documentation?

### ISSUE THREAD

**Issue by imphil** [cython/cython#5566]
### Describe your issue

I see code like `from __future__ import print_function` repeatedly in Cython documentation (e.g., https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html). Of course Cython still works with Python 2, but would it make sense to assume Python 3 for general documentation snippets? 

I would expect that Python 2 users (at this point in time) know what they're doing to keep their (probably legacy) code bases up and running, i.e., these users are not the primary audience for the documentation.

I'm happy to do a PR, just want to make sure I get your input first.

**Comment by scoder** [comment]
In Cython 3.0, we test the documentation with Py2, so these compatibility quirks are still needed.

We're going to remove Py2 support in Cython 3.1, so these parts will be removed along the way. We'll probably start working on Cython 3.1 once the amount of bug reports for 3.0 goes down. Many projects probably haven't started their migration yet.

I'll close this ticket since it's an obvious part of the 3.1 roadmap.
