### ISSUE TITLE
Generated cached builtins from a fixed list rather than looking up in the interpreter

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5591]
> Just checking Python's builtins isn't right, though. They can change with new Python versions (e.g. when new exceptions are added, like the heap of detailed I/O exceptions in Py3.4), so you'd get different warnings when you run Cython in different Python installations.

> We should check against a fixed set of builtin names, and update that regularly.

_Originally posted by @scoder in https://github.com/cython/cython/issues/5589#issuecomment-1666430772_

See https://github.com/cython/cython/blob/6776c96f66fc799c62be4d6d4022903a5e36cbb2/Cython/Compiler/Symtab.py#L1186C13-L1186C13 for where we do it.

This is more important in Symtab (where it affects code generation) than in the issue this was first discussed in (where it would effect warnings only)

**Comment by SauravChittal** [comment]
Hello, I wanted to help with this issue. I'm new to open source, where would be a good place to start @da-woods ? Thank you!

**Comment by da-woods** [comment]
It's really just replacing one line of code in Symtab.py (linked in the question). You want to test against a list of class names (should probably live in Cython/Compiler/Builtin.py).

Take the list of names from the most recent version of Python you can

**Comment by rakeshcj** [comment]
Hi @da-woods is the issue still open ?. If its still open can you please assign it to me.

**Comment by scoder** [comment]
> is the issue still open ?. If its still open can you please assign it to me

Feel free to send a PR.

**Comment by alexandrasp** [comment]
hey @scoder / @da-woods 

I tried to fix this issue and opened PR #6043 . I added the `builtins` set in  `Builtin.py` as recommended, but this creates a circular import, so I let the list of class names in `Symtab.py`. I still need to write some tests or even test this change properly, could you give me some guidance? The default test suite was executed.

**Comment by scoder** [comment]
I just noticed one issue with this approach. When new builtins are added and users refer to them in their code, we will generate code to look them up at module init time. On Python versions that don't have them, this will fail. Even if users were referring to them conditionally, e.g. based on a Python version check, the module import will still fail because we are always looking up the builtins that we find, not just the ones that are actually (conditionally or not) used at runtime.

Maybe we should have a second list of builtins for which we ignore lookup failures at module init time, and then allow those globals to be `NULL` and check for that on use.

**Comment by scoder** [comment]
> I added the `builtins` set in `Builtin.py` as recommended, but this creates a circular import, so I let the list of class names in `Symtab.py`.

Given that the `uncachable_builtins` list is in `Code.py`, I'd say move the complete list of builtins just before that.

**Comment by scoder** [comment]
Closed by https://github.com/cython/cython/pull/6043/
I moved the actual set from Symtab.py into Code.py in https://github.com/cython/cython/commit/4bc10b9f41c29cfc8c093b6d7c2505894c6e40ca
