### ISSUE TITLE
CO_OPTIMIZED, CO_NEWLOCALS don't exist in Limited API

### ISSUE THREAD

**Issue by aws-taylor** [cython/cython#5611]
### Describe the bug

https://github.com/cython/cython/blob/db995de3d24fe463a4121ab9acb94c968d4f25b3/Cython/Compiler/ExprNodes.py#L10001

CO_OPTIMIZED and CO_NEWLOCALS do not exist in the limited API. As a result, code that attempts to use CYTHON_LIMITED_API will end up with a compile warning or error. A naive fix is simply to materialize the values, something like:

`flags = [ str(inspect.CO_OPTIMIZED), str(inspect.CO_NEWLOCALS)]`. 

This just moves the goal post though - the surrounding `__Pyx_PyCode_New` also does not exist in the limited API. It's not clear what the correct way to suppress or patch PyCode related symbols is.

**Comment by da-woods** [comment]
I'm fairly sure this is fixed in https://github.com/da-woods/cython/tree/limited-api-with-py-limited-api-cdef-clas (which I'll submit as a PR as soon as https://github.com/cython/cython/pull/5550 is merged). So be patient and it'll appear.

(As you note, there isn't a great solution since we do need the actual values of these. `__Pyx_PyCode_New` isn't a problem though - we can emulate that in the limited API and that'll be in #5550)

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/e1d9c5a03af7a7c723022acfed18f3ea1d1b10c7 (although not completely satisfactorily - I'll create a follow-up issue to improve it)
