### ISSUE TITLE
[ENH] Refactor complex.pxd to use limited API

### ISSUE THREAD

**Issue by aws-taylor** [cython/cython#5630]
### Describe your issue

In https://github.com/cython/cython/blob/master/Cython/Includes/cpython/complex.pxd, there are references to `Py_complex`, which is opaque in the limited API. This file appears to be slurped up when cythonizing as part of `complex_type_declarations`. My cython-fu is weak, but it looks like it should be possible to make the cval an opaque object (https://github.com/cython/cython/blob/master/Cython/Includes/cpython/complex.pxd#L16C14-L16C24) and use 
[PyComplex_RealAsDouble](https://docs.python.org/3/c-api/complex.html#c.PyComplex_RealAsDouble) and friends in the implementation of `cdef inline double real(self)`, with similar implementations for other methods.

**Comment by da-woods** [comment]
I don't think we use complex.pxd unless the user does `from cpython cimport complex` or similar. From that point of view I think it's low priority because it's something the user has deliberately used rather than something they've chosen to use. It also doesn't do anything they can't do themselves (i.e. it's just a bunch of extern declarations).

We do use Cython/Utility/Complex.c which I think is what you're probably looking at. This is Cython internal utility code and should be updated. The only place I can immediately see that needs changing is

https://github.com/cython/cython/blob/d455d51bf31379f47c074e40517e24857d4d9cc0/Cython/Utility/Complex.c#L135-L146

but maybe there's something else I missed.

**Comment by scoder** [comment]
Seems worth having a guard CYTHON_USE_COMPLEX_INTERNALS, as we do for PyLong or lists.

**Comment by da-woods** [comment]
The other place that might need changing:

https://github.com/cython/cython/blob/d455d51bf31379f47c074e40517e24857d4d9cc0/Cython/Compiler/Builtin.py#L287-L289

`cval` is fine as-is because it's useless without `Py_complex` anyway, and won't generate code unless used.
`real` and `imag` will need updating.

`BuiltinProperty` now exists that'll probably help.

**Comment by da-woods** [comment]
Now that you post the code that does look like it's coming from complex.pxd. I can get it with a file consisting of

```
from cpython cimport complex
```

but it goes away if i remove it. Unless I'm missing something, you can only get that by a direct or indirect `cimport`.
The file is a mixture of
*  declarations for the complex C API declarations (which you obviously won't get access to if their outside the limited API, but Cython knowing about them doesn't generate any code and so won't hurt), 
* definitions allowing for internal access into the `PyComplexObject` structure, which obviously will never work with the limited API.

Unfortunately I don't think we currently have a good mechanism for making this kind of definition conditional, so it isn't an easy fix.

> That appears to be emitted here: https://github.com/cython/cython/blob/master/Cython/Compiler/Nodes.py#L2878

That's not hugely revealing - that's basically where any prototype for a `cdef` function will be written from.

**Comment by aws-taylor** [comment]
Aha, your comment about `cimport` was the clue I needed. I was calling:
`from cpython cimport PyBytes_AS_STRING`

In `cpython/__init__.pdx` file, this implicitly includes complex.pdx.

Changing my code to the following fixes the issue.

`from cpython.bytes cimport PyBytes_AS_STRING`

In fairness, there is a big warning in the init file:

```
# Do NOT cimport any names directly from the cpython package,
# despite of the star-imports below.  They will be removed at
# some point.
# Instead, use the correct sub-module to draw your cimports from.
#
# A direct cimport from the package will make your code depend on
# all of the existing declarations. This may have side-effects
# and reduces the portability of your code.
```

Unfortunately there appears to be a ton of examples in the wild that do this, including seemingly cython's own tutorials - https://cython.readthedocs.io/en/latest/src/tutorial/array.html

**Comment by da-woods** [comment]
Glad you got it sorted. I suspect we will need to deal with some of this stuff for the limited API and come up with a good way of making our supplied .pxd files not incompatible. But I'm inclined to put that off for later and focus on the really low-hanging stuff now.

I created an issue to remove the pattern from the documentation
