### ISSUE TITLE
[BUG] Cython 3.0.1 compile time crash: None Default Value

### ISSUE THREAD

**Issue by RaubCamaioni** [cython/cython#5643]
### Cython 3.0.1 compile time crash: None Default Value

Cython 3.0.1 crashes during compilation when None default present AND other default values in argument.
Cython 3.0.0 does not crash when None default values are present. 

Crashes in both pure python and cython code. py/pyx

Snippet of error:
```
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 846, in generate_subexpr_evaluation_code
          node.generate_evaluation_code(code)
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 837, in generate_evaluation_code
          self.generate_result_code(code)
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 8017, in generate_result_code
          self.generate_operation_code(code)
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 8576, in generate_operation_code
          self.generate_sequence_packing_code(code)
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 8084, in generate_sequence_packing_code
          code.put_incref(arg.result(), arg.ctype())
        File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 10113, in result
          self.defaults_struct.lookup(self.arg.name).cname)
      AttributeError: 'NoneType' object has no attribute 'cname'
```

### Code to reproduce the behaviour:

Compiling the following code causes cython 3.0.1 to crash. 

crash line
```
File "/tmp/pip-build-env-ywx0l3dj/overlay/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 10113, in result
          self.defaults_struct.lookup(self.arg.name).cname)
      AttributeError: 'NoneType' object has no attribute 'cname'
```

reproduce crash code
```cython
from typing import Optional

# no crash
def foo1(a: Optional[int] = None):
    return 1

# no crash
def foo(a: int = 1, b = None):
    return 1

# crash
def foo(a: int = 1, b: int = None):
    return 1

# crash
def foo(a: int = 1, b: Optional[int] = None):
    return 1
```

### Expected behaviour

The compiler should not crash if None default value is present with other default values in function argument definition. 

If default None types are not allowed, interpret as python object. 
Send compile warning to user None default value assignment not allowed.

### OS

Debian GNU/Linux 12 (bookworm) in Docker in WLS2 in windows

### Python version

3.8.17

### Cython version

3.0.1

### Additional context

Cython is amazing :).

**Comment by scoder** [comment]
Thanks for the short reproducer. I can add that this requires `language_level=3(str)` and doesn't occur with `language_level=2`, which we still use for a large part of our test suite for legacy reasons.

**Comment by scoder** [comment]
I investigated this a little and found that we generate a type check for the default argument (`None`) that then gets in the way so that we don't detect the default value as a literal any more (it's now a type checked literal) and instead generate a more complex setup for the default arguments. One unfortunate coincidence here is that the type of `int` is ambiguous between Py2 and Py3, so we coerce the `None` default value as arbitrary Python object (forgetting that it is compile time compatible with `int`) and then add the runtime type check against `int`. If `int` was a simple type like any other and not "int or long", this would be easily resolved by assigning the type `int` to the default argument.

I can add a special case for `None` when coercing it as default argument to avoid the runtime check, thus simplifying the generated C code and avoiding the problem all together.

**Comment by hughmiles-atamate** [comment]
I got the same error from this line of Python source:

`    def set_single_coil(self, slave_id: int = 0, coil_address: int = 0, coil_status: int = True) -> None:`

The code was cythoned correctly in version 3.0.0.

I changed the line to 

`    def set_single_coil(self, slave_id: int = 0, coil_address: int = 0, coil_status: bool = True) -> None:`

and it cythoned correctly in 3.0.2
