### ISSUE TITLE
Failing cdef_multiple_inheritance_nodict test when CYTHON_USE_TYPE_SPECS=1 and CYTHON_USE_TYPE_SLOTS=0

### ISSUE THREAD

**Issue by mattip** [cython/cython#5696]
### Describe your issue

Working through the failures in PyPy when `-DCYTHON_USE_TYPE_SPECS=1` (after #5594), I am [down to one](https://github.com/pypy/binary-testing/actions/runs/6155039760/job/16701328208#step:7:12901): `cdef_multiple_inheritance_nodict`. It hits this error:
> `unable to validate whether bases have a __dict__ when CYTHON_USE_TYPE_SLOTS is off (likely because you are building in the limited API). Therefore, all extension types with multiple bases must add 'cdef dict __dict__' in this compilation mode`

from [here](https://github.com/cython/cython/blob/ce1aa59ab6300e18e50c752b5c9e28a04b665060/Cython/Utility/ExtensionTypes.c#L158). Am I correct that the failure is expected, and so the test should expect to hit that message when testing this configuration?

**Comment by da-woods** [comment]
So my conclusion was that it isn't possible to use find out the dict offset without accessing `tp_dictoffset`. That definitely means you can't do it in the limited API.

I don't know whether we should make the guard

```
#if !CYTHON_USE_TYPE_SLOTS && CYTHON_COMPILING_IN_LIMITED_API
```

and just cheat and access `tp_dictoffset` directly otherwise.... (i.e. treat the macro as "avoid type slots wherever possible").

But yes - this seems like we'd currently expect it to fail. This is possibly somewhere where we could update or skip the test as well (we'll probably have to do this when we get as far as running the test in the limited api).

**Comment by scoder** [comment]
Can't type specs help here? Like in
https://github.com/cython/cython/blob/ce1aa59ab6300e18e50c752b5c9e28a04b665060/Cython/Utility/ExtensionTypes.c#L39

**Comment by da-woods** [comment]
I'd somehow missed that `__dictoffset__` seems to be available via a normal Python attribute lookup. With that in mind this should be easily fixed

**Comment by mattip** [comment]
Thanks
