### ISSUE TITLE
[BUG] enum.IntEnum objects are incompatible with `int` builtin type hint

### ISSUE THREAD

**Issue by pspacek** [cython/cython#5853]
### Describe the bug

enum.IntEnum objects are incompatible with `int` builtin type hint in Cython, but mypy and Python do not complain. See the code below.

### Code to reproduce the behaviour:

First define a new subclass of IntEnum and one helper function depending on it. The minimal example below seems silly but it's greatly simplified code from dnspython library where it makes more sense.

```cython
import enum

class RdataClass(enum.IntEnum):
    IN = 1
    CH = 3

# please note that enum.IntEnum inherits from the builtin int type
def to_text(value: int) -> str:
    return RdataClass(value).name
```

Use this module:
```
import rdataclass
print(rdataclass.to_text(dns.rdataclass.RdataClass.IN))
```

Cython throws an exception:
```
TypeError: Argument 'value' has incorrect type (expected int, got RdataClass)
```

### Expected behaviour
```
'IN'
```

### OS

Linux

### Python version

3.11.5

### Cython version

3.0.5

### Additional context

mypy 1.3.0 does not complain about this code

**Comment by scoder** [comment]
This applies to typing in Cython in general. Static typing makes no sense if you allow subtypes, because subtypes can override arbitrary behaviour of the type. So, Cython does not allow subtypes (or similar types) in order to make use of the types for optimisation purposes.

**Comment by bwelling** [comment]
I might be missing something, but "Cython does not allow subtypes (or similar types) in order to make use of the types for optimisation purposes." sounds like a statement that cython would prevent optimization if subtypes are involved.  In this case, the type checker is outright failing, which is not the same thing.

**Comment by da-woods** [comment]
So Cython has long interpreted the old style syntax of

```
cdef f(list x):
   ...
```

as "exact list" and generated code that *requires* an exact list. Because actually nothing else is useful to us - a list subclass has to be treated as a plain object.

When we decided to support annotations we followed the same rules, even though it puts us shortly out of sync with the described Python rules.

Basically Cython isn't viewing itself as a type-checker - it's viewing itself as a way of generating optimised code. We don't want to have to generate multiple paths based on the actual types so it suits Cython's goals to be strict.

If you don't want Cython to follow its annotation rules then you can use `cython.annotation_typing(False)` and it'll behave like Python and accept any object. You can apply this compiler directive as locally or as globally as you like.

(For completeness, the one exception to this "no subclassess rule is `cdef classes`, since they're generated in a way that we can make subclassess quick)

**Comment by pspacek** [comment]
Thank you for explanation. I think this can be closed.
