### ISSUE TITLE
[BUG] Dict annotation forces exact type check

### ISSUE THREAD

**Issue by lkollar** [cython/cython#5908]
### Describe the bug

The example below results in the following runtime error:

```
python -c "import example"
  File "example.pyx", line 12, in init example
    f(d)
TypeError: Expected dict, got collections.OrderedDict
```

This appears to happen because the `_Pyx_ArgTypeTest` function is called with the `exact` argument set to 1 in this case. This means that a subclass of the `Dict` type cannot be passed to the function.

### Code to reproduce the behaviour:

```cython
❯ cat example.pyx
from typing import Dict

from collections import OrderedDict

cdef f(p: Dict):
    print("foo")

d = OrderedDict()

f(d)
```

### Expected behaviour

No error.

### OS

macOS, Linux

### Python version

3.10.13

### Cython version

3.0.6

**Comment by da-woods** [comment]
This is intentional even if it differs a little from what annotations mean in other contexts. See https://github.com/cython/cython/issues/5853 for an almost duplicate. If you want to be more flexible than cython is by default then use `@cython.annotation_typing(False)` on the function (or class, or file, as needed)

I wonder if we should customize the type error though to explain this? It's clearly a source of confusion even if there's good reasons for doing it.

**Comment by lkollar** [comment]
Thanks. I think the migration guide should mention this. I checked there first and didn’t see anything mentioned. In this case this code hasn’t changed at all, but upgrading to Cython 3 broke some clients.

**Comment by da-woods** [comment]
What's changed in this case is that Cython3 now understands `typing.Dict` where it didn't before - if you'd used `dict` as an annotation then you'd see the same behaviour in Cython 0.29.x. I'll try look at providing more helpful information here.
