### ISSUE TITLE
[BUG] Segmentation fault with Walrus-Operator and same named variables

### ISSUE THREAD

**Issue by mspi92** [cython/cython#6094]
### Describe the bug

There is a Segmentation Fault in the attached example (simplified from actually failing production code).
Requirement for failure:
- Usage of Walrus Operator in an if statement.
- First If Statement does not fully evaluate
- Second If Statement uses same variable name in assignment operator.

Segmentation fault occurs because Variable gets dereferenced in the second If-condition without having a value assigned. 
The assignment doesn't happen because first If-condition doesn't get fully evaluated.

### Code to reproduce the behaviour:

```python

def problem_function():
    d = False
    a = []
    if d and (q := a):
        pass

    if q := a:
        pass
```

### Expected behaviour

No Segmentation Fault in Cythonized code

### OS

Linux

### Python version

3.11.8

### Cython version

latest master

**Comment by da-woods** [comment]
Thanks - in the short term I suspect the better solution is to treat assignment expressions as "maybe assignments" rather than "definite assignments". There's quite a few variations of cases like this where it isn't clear if they're actually run and which our flow control doesn't currently cover so working it out comprehensively is likely hard.

That'll de-optimize assignment expressions slightly but I think that's OK.

**Comment by gshmu** [comment]
walrus define variable after `or`  operate, make gunicorn crash: `[ERROR] Worker (pid:9467) was sent code 139!`
```cython
def func(cell: dict):
    if (flag := True) or ((text := cell.get("text")) and text.isdigit()):
        return True
    text = cell.get("text") or cell.get("value")
    return text
```

Expected: raise some error at lease
