### ISSUE TITLE
Pickling Error for Pyspark UDF function while using decorator.

### ISSUE THREAD

**Issue by skamdar** [cython/cython#6146]
### Describe the bug

For a globally defined function Cythonized code fails to seriealize function definition if python decorator is used to create a udf like following:

### Code to reproduce the behaviour:

```
import pyspark.sql.functions as F
@F.udf(returnType=str)
def func(x):
    return x

df.withColumn("x", func(F.col("col_name")))
```

### Expected behaviour

while following code does not give pickle error:

```
import pyspark.sql.functions as F

def func(x):
    return x

func_udf = F.udf(func, returnType=str)
df.withColumn("x", func_df(F.col("col_name")))
```

### OS

Linux

### Python version

3.9.2

### Cython version

3.0.10

**Comment by da-woods** [comment]
I tried to run both cases in Python and got

```
pyspark.errors.exceptions.base.PySparkTypeError: [NOT_DATATYPE_OR_STR] Argument `returnType` should be a DataType or str, got type.
```

so this looks like broken code before we even involve Cython.

**Comment by da-woods** [comment]
Realistically though, it's not going to work.

Both Python functions and Cython functions are pickled by name by default. That will fail (in both cases) because with the decorator `func` no longer isn't directly accessible by name - it's hidden by the result of the decorator returns.

PySpark looks to use cloudpickle. That has a bunch of special-casing for Python functions to pickle them in a different way (by serializing their byte code). That isn't possible on Cython functions.

While I have an open PR to improve pickling of Cython functions, it wouldn't work here because simple functions are still pickled by name (and that fails as described above).

**Comment by skamdar** [comment]
@da-woods I have rectified the code to make it work. Let me know if you can reproduce the issue now.

**Comment by da-woods** [comment]
> `NameError: name 'spark' is not defined`

-----------------------

I've already explained why I don't think this can work though, so I won't be spending any further time on this.
