### ISSUE TITLE
Start uploading nightly wheels

### ISSUE THREAD

**Issue by lysnikolaou** [cython/cython#6223]
### Describe your issue

Since the free-threading compatibility effort is now under way, both for Cython and for other major scientific python libraries, it might be a good idea to start uploading nightly wheels, in order to make it easier for projects to test their changes to support free-threading (and other changes obviously).

The wheels can be hosted at https://anaconda.org/scientific-python-nightly-wheels/repo. One thing to consider is whether it'll be using too many CI resources, but there's already a cron that runs once a week, so maybe we can use that to upload a nightly (we can even just change the cron to run twice a week, like NumPy does for example). Other than that, it should be relatively straightforward to set up. If you agree, I can work on it.

**Comment by da-woods** [comment]
I think this might be a sensible thing to do.

It might be worth restricting this to a non-compiled Cython wheel (e.g. built with `NO_CYTHON_COMPILE=true` environmental variable). It means only a single wheel is needed because it's just Python code.

Compiling Cython does make it slightly faster (so is probably net worthwhile for a release where many people will be using it) but that's really the only difference so doesn't seem worth it for a lightly-used nightly build.

**Comment by ngoldbaum** [comment]
Thanks for explaining that! I was wondering how I’ve still been able to get a usable wheel on the free-threading build on pypi. But of course if it’s pure-python that explains it.

**Comment by lysnikolaou** [comment]
> It might be worth restricting this to a non-compiled Cython wheel (e.g. built with NO_CYTHON_COMPILE=true environmental variable). It means only a single wheel is needed because it's just Python code.

Got it. I'll work on setting this up.
