### ISSUE TITLE
[EMH] Implement alternative versions of `Optional[...]`

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#6254]
### Describe your issue

It seems that implementing generic union types (`X | Y` and `Union[X, Y]`) are difficult to implement and are [rejected](https://github.com/cython/cython/pull/6206#issuecomment-2159949439). We can try to implement reduced version containing `None` since it is often used instead of `typing.Optional[]`. We can transform it as follows:

* `X | None` = `None | X`  -> `typing.Optional[X]`
* `X | Y | None` = `X | None | Y` = `None | X | Y` -> `typing.Optional[object]`
* `typing.Union[X, None]` = `typing.Union[None, X]` -> `typing.Optional[X]`
* `typing.Union[X, Y, None]` = `typing.Union[X, None, Y]` = `typing.Union[None, X, Y]` -> `typing.Optional[object]`

This issue is specialised version of #4631

**Comment by da-woods** [comment]
```
X | Y | None = X | None | Y = None | X | Y -> typing.Optional[object]
typing.Union[X, Y, None] = typing.Union[X, None, Y] = typing.Union[None, X, Y] -> typing.Optional[object]
```

These two aren't hugely worthwhile in Cython (because if you type something as `object` we never generate code that assumes it isn't `None`). They're harmless, but covered by the current behaviour of "annotation that Cython doesn't understand -> object"

```
X | None = None | X -> typing.Optional[X]
typing.Union[X, None] = typing.Union[None, X] -> typing.Optional[X]
```

These two are useful. Especially the one with `|` since I think that's what most people would choose to write. I have no idea how easy or hard they are to implement.
