### ISSUE TITLE
Bad use of CYTHON_LIMITED_API

### ISSUE THREAD

**Issue by dalcinl** [cython/cython#6361]
### Describe your issue

@da-woods `git blame` pointed to code you pushed in 2023. I think the way to use CYTHON_LIMITED_API may have changed. Are the following preprocessor guards still correct?

```console
$ git grep CYTHON_LIMITED_API Cython/Utility/Builtins.c
Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
```

I was about to submit a PR with a change to use __PYX_LIMITED_VERSION_HEX, but the fact that its value is not set by default confused me. 

Or perhaps what we are needing is simply something like the following
```patch
diff --git a/Cython/Utility/ModuleSetupCode.c b/Cython/Utility/ModuleSetupCode.c
index 4482e75bd..5d9e3f4f8 100644
--- a/Cython/Utility/ModuleSetupCode.c
+++ b/Cython/Utility/ModuleSetupCode.c
@@ -194,6 +194,9 @@
   #ifdef Py_LIMITED_API
     #undef __PYX_LIMITED_VERSION_HEX
     #define __PYX_LIMITED_VERSION_HEX Py_LIMITED_API
+  #else
+    #undef __PYX_LIMITED_VERSION_HEX
+    #define __PYX_LIMITED_VERSION_HEX CYTHON_LIMITED_API
   #endif
   #define CYTHON_COMPILING_IN_PYPY 0
   #define CYTHON_COMPILING_IN_CPYTHON 0
```
and then always use the value of __PYX_LIMITED_VERSION_HEX wherever needed?

**Comment by da-woods** [comment]
> Are the following preprocessor guards still correct?
> 
> ```
> $ git grep CYTHON_LIMITED_API Cython/Utility/Builtins.c
> Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
> Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
> ```

No - I think changing to `__PYX_LIMITED_VERSION_HEX` is the right thing to do.

-----------------------------------------------

Second part of the question:

* Currently `__PYX_LIMITED_VERSION_HEX` is set to `PY_VERSION_HEX` by default and `Py_LIMITED_API` if `Py_LIMITED_API` is set.
* I agree it might be a good idea (but probably isn't essential) to let you use `CYTHON_LIMITED_API` to force a specific version hex. Possibly even to let you force a lower version hex for Cython than what `Py_LIMITED_API` is set to.
* The only complication is that a lot of the time `CYTHON_LIMITED_API` is just set to 1 rather than a specific value. So we'd probably need to ignore it if it's less that `0x03070000` or something like that.

So your first change is definitely right. Something similar to your second change is probably a good idea

**Comment by dalcinl** [comment]
> No - I think changing to `__PYX_LIMITED_VERSION_HEX` is the right thing to do.

OK.

> Currently __PYX_LIMITED_VERSION_HEX is set to PY_VERSION_HEX by default and Py_LIMITED_API if Py_LIMITED_API is set.

Oh, sorry, now I see the line `#define __PYX_LIMITED_VERSION_HEX Py_LIMITED_API`

> So your first change is definitely right. Something similar to your second change is probably a good idea

OK, as soon as I have some time for it, I'll PR and as ask for your review.
