### ISSUE TITLE
[BUG] numpy `int` dtype vs `long` type raises Exception

### ISSUE THREAD

**Issue by dvezinet** [cython/cython#6384]
### Describe the bug

I define a python-accessible routine in a `.pyx` file that takes as input a `memoryview` of `long`.

Compilation goes ok

Then calling it from python with a `numpy` array of `int` raises an `Exception`

This is burried into my library, but has always worked fine till very recently.
I have tests running on Github on `Linux`, `MacOS` and `Windows` for `python` `3.8`, `3.9` and `3.10`.
They have all been passing for years on this.

But this error started showing up a few weeks ago I think, so I'm assuming it's because of a new `cython` version.

Interestingly, it only fails for one combination: `Windows` with `python 3.10`.
Please not that I have checked that with `python 3.11` the same pattern arises: only `windows` fails

![image](https://github.com/user-attachments/assets/2bccf87c-02b2-4f57-a24f-9dfdf6def9f5)

Focusing on windows only, with python 3.10, here is a comparison between the last successful run (a few weeks ago) and tis failed run, showing that only `numpy` and `Cython` have changed versions:

Test environment:

|       | Failed run                                                                             |  Last successful run           |
| --- | --------------------------------------------------------------- |-----------------------------|
|Runner | Runner version: 2.319.1                                                  | identical |
| OS |  Microsoft Windows Server 2022 `10.0.20348`  Datacenter | identical |
|Python| CPython (3.10.11)                                                            | identical |
| numpy | numpy-2.1.1-cp310-cp310-win_amd64.whl  | numpy-2.0.1-cp310-cp310-win_amd64.whl |
| Cython | Cython-3.0.11-cp310-cp310-win_amd64.whl |  Cython-3.0.10-cp310-cp310-win_amd64.whl |

### Code to reproduce the behaviour:

Define a python-accesible routine with a `long` memoryview

```cython

def routine(long[::1] foo=None):
    return
```

Compile and call it with a numpy array of `int`
```python
import numpy as np
routine(foo=np.asarray([1, 2, 3], dtype=int))
```

gives the same error with a different `dtype`
```python
routine(foo=np.asarray([1, 2, 3], dtype=np.int_))
```

### Expected behaviour

Should work without throwing exception

### OS

Microsoft Windows Server 2022 10.0.20348 Datacenter

### Python version

3.10.11

### Cython version

3.0.11

### Additional context

More context / details can be found [here](https://github.com/ToFuProject/tofu/issues/960)

**Comment by da-woods** [comment]
I don't think this is a Cython bug.

A memoryview of type `long` is asking to view an array with the C type `long`. Exactly what `long` means is determined by your C compiler. You can query (one aspect) of this with `print(sizeof(long))`.

`np.asarray(..., dtype=int)` is asking Numpy to create an array with whatever it considers an "int". You can query this by printing the `.dtype` attribute of the array.

Since you're asking Cython to create a *view*, it can't do any type conversion here because that would create a new copy. If the types don't match then all it can do is raise an error.

So somewhere along the line either Numpy has changed or your C compiler has changed. If you want reliable types then you need to use types that specify the size (i.e. `np.int64` and `libc.stdint.int64_t`)
