### ISSUE TITLE
[BUG] property methods got executed when doing auto-completion in REPL

### ISSUE THREAD

**Issue by botbotty** [cython/cython#6471]
### Describe the bug

I'm using my cython module in python REPL, find out that class methods that are marked as "property" can be executed unexpectedly when I press TAB key to perform auto-completion.

### Code to reproduce the behaviour:

```cython
# cymod.pyx:
cdef int cnt = 0

cdef class Bar:
    def __cinit__(self):
        global cnt
        cnt += 1

cdef class Foo:
    @property
    def bar(self):
        cdef Bar obj = Bar()
        return obj

def get_cnt():
    return cnt
```

```
>>> import cymod
>>> cymod.get_cnt()
0
>>> foo = cymod.Foo()
>>> cymod.get_cnt()
0
>>> bar = foo.bar
>>> cymod.get_cnt()
1
>>> foo.bar
<cymod.Bar object at 0x7f226ebdc7e0>
>>> cymod.get_cnt()
2
>>> foo.bar  <------------------------ press TAB key for several times, then press Ctrl-C
KeyboardInterrupt
>>> cymod.get_cnt()
10  <------------------------ expected to be 2
>>>
```

### Expected behaviour

```python
# pymod.py:
cnt = 0

class Bar:
    def __init__(self):
        global cnt
        cnt += 1

class Foo:
    @property
    def bar(self):
        obj = Bar()
        return obj

def get_cnt():
    return cnt
```

```
>>> import pymod
>>> pymod.get_cnt()
0
>>> foo = pymod.Foo()
>>> pymod.get_cnt()
0
>>> bar = foo.bar
>>> pymod.get_cnt()
1
>>> foo.bar
<pymod.Bar object at 0x7f226e707390>
>>> pymod.get_cnt()
2
>>> foo.bar  <------------------------ press TAB key for several times, then press Ctrl-C
KeyboardInterrupt
>>> pymod.get_cnt()
2
>>> 
```

### OS

Linux

### Python version

3.13.0

### Cython version

3.0.11

**Comment by da-woods** [comment]
This feels like it's probably a bug in Python 3.13's new repl. Cython properties for cdef classes are just set using the built-in `PyGetSetDef` rather than any special mechanism. Therefore there's really nothing we can do to change this behaviour. 

So I suggest raising this on the Python issue tracker instead.

**Comment by botbotty** [comment]
It can be reproduced with python 3.10.12

```
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import cymod
>>> cymod.get_cnt()
0
>>> foo=cymod.Foo()
>>> cymod.get_cnt()
0
>>> bar = foo.bar
>>> cymod.get_cnt()
1
>>> foo.bar
<cymod.Bar object at 0x7f12f5930850>
>>> cymod.get_cnt()
2
>>> foo.bar
foo.bar
>>> foo.bar
foo.bar
>>> foo.bar
foo.bar
>>> foo.bar
foo.bar
>>> foo.bar
KeyboardInterrupt
>>> cymod.get_cnt()
7
>>> 
```

**Comment by da-woods** [comment]
None the less, it's the Python REPL interacting with a Python `GetSetDescriptorType`. So I think it's worth raising there first.

I don't think there's a change that Cython could make to prevent this.

**Comment by da-woods** [comment]
https://github.com/python/cpython/issues/73816

**Comment by leofang** [comment]
@da-woods I found this issue after some searches. It would be nice if Cython could at least document this as a known/won't-fix issue.

This has a pretty profound impact on tab completion beyond Python's known issue (that `@property` has side effects), for all non-EOL'd Python versions (3.10+). If a cdef class has properties that could raise (as in our case where we want to raise exceptions to tell users that some features are not supported by the system), the tab completion on the entire class instance just does not work all together (see https://github.com/python/cpython/issues/88915 / https://github.com/python/cpython/pull/27401, for [bpo-44752](https://bugs.python.org/issue44752), which is being revisited in https://github.com/python/cpython/issues/112821). 

We caught this issue during manual test (because no automation would find this, since no one would anticipate that tab completion could break and design any test to catch it) on the day we planned to release 1.0 (https://github.com/NVIDIA/cuda-python/issues/2053). After going back and forth with LLM and our in-house CPython/Cython experts, our current conclusion is to avoid using plain `@property` by aliasing it, so as to control how Cython emits code for us (https://github.com/NVIDIA/cuda-python/pull/2056). 

While this should definitely be fixed on the CPython side (and we're pushing for it: https://github.com/python/cpython/pull/149577), we also need to cover all non-EOL CPython versions, so any fix on the CPython side is unfortunately considered a slow (5+ yr) track by us. If Cython can fix it for us, it'd be a much better fast track. But if not, we'd hope that at least we could get blessing from Cython core devs for the aliasing approach (which is currently [tested here](https://github.com/cython/cython/blob/401b195debacf5e790c7d081d11e85025442eb16/tests/run/cdef_class_property_decorator_T264.pyx#L60)) 🙂

**Comment by da-woods** [comment]
> It would be nice if Cython could at least document this as a known/won't-fix issue.

I'll have a look and see if I can find somewhere good to put it. The difficulty is always trying to find somewhere where it will be read, but where it doesn't scare people who just want to create a property.

> But if not, we'd hope that at least we could get blessing from Cython core devs for the aliasing approach 

If I understand correctly, you're just using the alias to create a normal Python decorator rather than a C one. I'm confident that should keep working.

The other option I can think of is to do something like

```
# module scope
property_catches = BaseException if sys.somehow_detect_if_were_in_a_repl else (,)

# In the property
try:
    ...
except property_catches:
    return None. # ?
```

Obviously one important detail is missing.

That's potentially something that either you could implement in your wrapper or that Cython could implement (maybe a bit more efficiently than you). It's probably a bit heavy to turn on by default though. I'll investigate at some point

**Comment by da-woods** [comment]
Thinking about it more, it definitely isn't *that* simple - you'd probably need to inspect the stack to work out if you were in an attempted auto-complete. Or accept some false positive weird behaviour, which might be ok for an opt in feature. I do think it's worth investigating though

**Comment by da-woods** [comment]
https://github.com/cython/cython/pull/7693 is an attempted solution for this. I'm slightly unsure whether this is the sort of thing that we really should be doing, but it at least proves it isn't too hard.
